package scaffold

import (
	"strings"
	"text/template"
)

// shaExpr is gocdnext's substitution for the short commit SHA. Passed as
// template data (not written inline) so text/template doesn't try to
// evaluate the `{{ }}` inside it.
const shaExpr = "${{ CI_COMMIT_SHORT_SHA }}"

// renderData feeds the pipeline templates. CheckUses/BuildUses are the
// `uses:` plugin refs for the detected language.
type renderData struct {
	AppName       string
	DefaultBranch string
	Registry      string
	CheckUses     string
	BuildUses     string
	CheckCmd      string
	BuildCmd      string
	HasDockerfile bool
	ShaExpr       string
	// Node without a lockfile: emit an explicit manager + non-frozen
	// install, because the plugin's `manager: auto` needs a lockfile.
	EmitManager bool
	Manager     string
	FrozenFalse bool
}

const genHeader = "# Generated by `gocdnext scaffold` — a starting point; review before committing.\n"

// build-pr: fast PR feedback (lint+test). Empty CheckCmd → an install-only
// job (the node plugin validates deps resolve) — valid, and flagged by a
// warning at detection time.
var buildPRTmpl = template.Must(template.New("build-pr").Parse(genHeader + `when:
  event: [pull_request]
stages: [ci]
jobs:
  check:
    stage: ci
    uses: {{.CheckUses}}
{{- if or .EmitManager .FrozenFalse .CheckCmd}}
    with:
{{- if .EmitManager}}
      manager: {{.Manager}}
{{- end}}
{{- if .FrozenFalse}}
      frozen: false
{{- end}}
{{- if .CheckCmd}}
      command: {{.CheckCmd}}
{{- end}}
{{- end}}
`))

// build: on push to the default branch — build, plus an image job only
// when a Dockerfile was detected. The image repo is a commented TODO;
// the scaffolder never invents a registry.
var buildTmpl = template.Must(template.New("build").Parse(genHeader + `when:
  event: [push]
  # adjust if your repo's default branch isn't {{.DefaultBranch}}
  branch: [{{.DefaultBranch}}]
stages: [build{{if .HasDockerfile}}, image{{end}}]
jobs:
  build:
    stage: build
    uses: {{.BuildUses}}
    with:
{{- if .EmitManager}}
      manager: {{.Manager}}
{{- end}}
{{- if .FrozenFalse}}
      frozen: false
{{- end}}
      command: {{.BuildCmd}}
{{- if .HasDockerfile}}
  image:
    stage: image
    uses: gocdnext/buildx@v1
    needs: [build]
    with:
      # TODO: point this at your image repository
      image: {{.Registry}}/{{.AppName}}
      tags: "1.{{.ShaExpr}}"
{{- end}}
`))

// security: universal — filesystem CVE scan + secret scan, on push and PR.
var securityTmpl = template.Must(template.New("security").Parse(genHeader + `when:
  event: [push, pull_request]
stages: [scan]
jobs:
  trivy-fs:
    stage: scan
    uses: gocdnext/trivy@v1
    with:
      scan-type: fs
  gitleaks:
    stage: scan
    uses: gocdnext/gitleaks@v1
`))

// dataFor builds the template data for a detected stack.
func dataFor(s Stack) renderData {
	d := renderData{
		AppName:       orDefault(s.AppName, "app"),
		DefaultBranch: orDefault(s.DefaultBranch, "main"),
		Registry:      "registry.example.com",
		HasDockerfile: s.HasDockerfile,
		ShaExpr:       shaExpr,
	}
	switch s.Language {
	case "node":
		d.CheckUses = "gocdnext/node@v3"
		d.BuildUses = "gocdnext/node@v3"
		d.CheckCmd = nodeCheckCommand(s)
		d.BuildCmd = s.NodeManager + " run build"
		// With a lockfile the plugin's manager:auto resolves it (cleaner,
		// frozen). Without one, auto fails — pin manager + non-frozen so
		// the pipeline runs (the detector already warned it's non-repro).
		if !s.HasLockfile {
			d.EmitManager = true
			d.Manager = s.NodeManager // "npm"
			d.FrozenFalse = true
		}
	case "go":
		d.CheckUses = "gocdnext/go@v1"
		d.BuildUses = "gocdnext/go@v1"
		d.CheckCmd = "go test ./..."
		d.BuildCmd = "go build ./..."
	}
	return d
}

// nodeCheckCommand chains the lint + test scripts that actually exist in
// package.json (via the detected manager). Empty when neither is present.
func nodeCheckCommand(s Stack) string {
	var parts []string
	if s.Scripts["lint"] {
		parts = append(parts, s.NodeManager+" run lint")
	}
	if s.Scripts["test"] {
		parts = append(parts, s.NodeManager+" run test")
	}
	return strings.Join(parts, " && ")
}

func render(t *template.Template, d renderData) (string, error) {
	var b strings.Builder
	if err := t.Execute(&b, d); err != nil {
		return "", err
	}
	return b.String(), nil
}

func orDefault(v, def string) string {
	if strings.TrimSpace(v) == "" {
		return def
	}
	return v
}
