{{- if and .Values.agent.enabled (and (not .Values.agent.tokenSecret.existingSecret) .Values.agent.tokenSecret.value) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gocdnext.agent.fullname" . }}-token
  labels: {{- include "gocdnext.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.agent.tokenSecret.value | quote }}
{{- end }}
