{{- if and .Values.agent.enabled (eq .Values.agent.engine "kubernetes") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gocdnext.agent.fullname" . }}-workspace
  labels: {{- include "gocdnext.labels" . | nindent 4 }}
spec:
  accessModes: [{{ .Values.agent.workspace.accessMode | quote }}]
  {{- with .Values.agent.workspace.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.agent.workspace.size }}
{{- end }}
