-- name: InsertPendingArtifact :one
-- Inserts a row in `pending` status ahead of the agent's upload. The
-- storage_key is generated by the caller (UUID-based) so the row's id and
-- the backend's object key are decoupled — makes it safe to retry without
-- ending up with orphan objects keyed off a stale PK.
INSERT INTO artifacts (
    run_id, job_run_id, pipeline_id, project_id,
    path, storage_key, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, run_id, job_run_id, pipeline_id, project_id,
          path, storage_key, status, expires_at, created_at;

-- name: MarkArtifactReady :execrows
-- Called after the server HEADs the storage and confirms the object is
-- there. Bumps status + records size/sha. Safe to call once; subsequent
-- calls update nothing (status already 'ready'), returning 0 rows.
UPDATE artifacts
SET status = 'ready',
    size_bytes = $2,
    content_sha256 = $3
WHERE storage_key = $1 AND status = 'pending';

-- name: ListArtifactsByJobRun :many
-- Used by server-side JobResult reconciliation to match ArtifactRef
-- entries back to their pending rows. Also used later (E2c) to expose
-- downloads to downstream jobs in the same run.
SELECT id, run_id, job_run_id, pipeline_id, project_id,
       path, storage_key, status, size_bytes, content_sha256,
       expires_at, pinned_at, deleted_at, created_at
FROM artifacts
WHERE job_run_id = $1
ORDER BY created_at;

-- name: GetArtifactByStorageKey :one
-- Single-row lookup for the JobResult confirmation path. Returns
-- ErrNoRows if the agent invented a key or the row was swept.
SELECT id, run_id, job_run_id, pipeline_id, project_id,
       path, storage_key, status, size_bytes, content_sha256,
       expires_at, pinned_at, deleted_at, created_at
FROM artifacts
WHERE storage_key = $1;

-- name: ListArtifactsByRun :many
-- Used by E2c for intra-run downloads (`needs_artifacts:` resolution).
-- Only returns ready artefacts — pending/deleting must not leak as
-- dependable to downstream jobs.
SELECT id, run_id, job_run_id, pipeline_id, project_id,
       path, storage_key, status, size_bytes, content_sha256,
       expires_at, pinned_at, deleted_at, created_at
FROM artifacts
WHERE run_id = $1 AND status = 'ready'
  AND deleted_at IS NULL
ORDER BY created_at;

-- name: GetJobRunParents :one
-- Resolves pipeline_id + project_id + agent_id for a (job_run_id,
-- run_id) pair. Used by the RequestArtifactUpload handler to authorise
-- + derive the FKs. Returns ErrNoRows if job_run_id doesn't belong to
-- the claimed run_id. agent_id is NULL when the job hasn't been
-- dispatched yet (shouldn't happen on this code path but the column
-- nullability forces us to handle it).
SELECT r.pipeline_id AS pipeline_id,
       p.project_id  AS project_id,
       jr.agent_id   AS agent_id
FROM job_runs jr
JOIN runs r       ON r.id = jr.run_id
JOIN pipelines p  ON p.id = r.pipeline_id
WHERE jr.id = $1 AND jr.run_id = $2;
