apiVersion: v2
name: gocdnext
description: Modern CI/CD orchestrator with VSM, fanout and webhook-first ingest
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - ci
  - cd
  - pipelines
home: https://github.com/klinux/gocdnext
sources:
  - https://github.com/klinux/gocdnext
