package runner

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPrepareOutputsFile_CreatesEmpty0600File(t *testing.T) {
	work := t.TempDir()
	path, err := prepareOutputsFile(work, "abcdef1234567890-1111-2222-3333-444455556666")
	if err != nil {
		t.Fatalf("prepareOutputsFile: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if info.Size() != 0 {
		t.Errorf("size = %d, want 0 (file should be empty before the plugin writes)", info.Size())
	}
	// On unix, file mode must be 0o600 — verify the bits aren't 077-leaky.
	if info.Mode().Perm() != 0o600 {
		t.Errorf("mode = %v, want 0600", info.Mode().Perm())
	}
	// Parent dir should be 0o700 and live under the agent-chosen
	// .gocdnext/outputs subtree.
	dirInfo, err := os.Stat(filepath.Dir(path))
	if err != nil {
		t.Fatalf("stat dir: %v", err)
	}
	if dirInfo.Mode().Perm() != 0o700 {
		t.Errorf("dir mode = %v, want 0700", dirInfo.Mode().Perm())
	}
	if !strings.Contains(path, filepath.Join(".gocdnext", "outputs")) {
		t.Errorf("path %q not under .gocdnext/outputs", path)
	}
}

func TestPrepareOutputsFile_TruncatesExisting(t *testing.T) {
	// Reused workspace (k8s shared-mode reuse, agent retries) — a
	// leftover file from a prior run must not contaminate this run.
	work := t.TempDir()
	jobID := "0000-1111-2222-3333"
	path, err := prepareOutputsFile(work, jobID)
	if err != nil {
		t.Fatalf("first prepare: %v", err)
	}
	if err := os.WriteFile(path, []byte("STALE=value\n"), 0o600); err != nil {
		t.Fatalf("write stale: %v", err)
	}
	if _, err := prepareOutputsFile(work, jobID); err != nil {
		t.Fatalf("second prepare: %v", err)
	}
	info, _ := os.Stat(path)
	if info.Size() != 0 {
		t.Errorf("prepareOutputsFile didn't truncate (size = %d)", info.Size())
	}
}

func TestParseOutputsFile_HappyPath_FiltersToDeclared(t *testing.T) {
	work := t.TempDir()
	path, err := prepareOutputsFile(work, "job-A")
	if err != nil {
		t.Fatal(err)
	}
	// Plugin writes MORE than the operator declared — extra keys
	// are silently dropped, the declared subset is rekeyed to
	// alias → value.
	content := `# Generated by gocdnext/semver-bump
NEXT='v1.3.0'
CURRENT='v1.2.5'
KIND='minor'
PREV_SHA='abc123'
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	declared := map[string]string{
		"next": "NEXT",
		"kind": "KIND",
	}
	out, err := parseOutputsFile(path, declared)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(out) != 2 {
		t.Fatalf("len = %d, want 2 (%v)", len(out), out)
	}
	if out["next"] != "v1.3.0" {
		t.Errorf("next = %q, want v1.3.0", out["next"])
	}
	if out["kind"] != "minor" {
		t.Errorf("kind = %q, want minor", out["kind"])
	}
	if _, leaked := out["NEXT"]; leaked {
		t.Errorf("NEXT (env name) leaked into result map; should be alias-keyed only")
	}
}

func TestParseOutputsFile_NoDeclarationSkipsRead(t *testing.T) {
	// declared=nil means "the job doesn't promise any outputs" —
	// the parser must NOT even open the file (it might not exist).
	out, err := parseOutputsFile("/no/such/path/will-not-be-opened", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if out != nil {
		t.Errorf("expected nil map, got %v", out)
	}
}

func TestParseOutputsFile_MissingDeclaredKey(t *testing.T) {
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-B")
	// Plugin wrote NEXT but operator declared `kind: KIND` — the
	// missing one fails the job.
	_ = os.WriteFile(path, []byte("NEXT='v1.0.0'\n"), 0o600)
	_, err := parseOutputsFile(path, map[string]string{
		"next": "NEXT",
		"kind": "KIND",
	})
	if err == nil {
		t.Fatal("expected error for missing declared key")
	}
	if !strings.Contains(err.Error(), "kind") {
		t.Errorf("error should cite the missing alias, got: %v", err)
	}
}

func TestParseOutputsFile_OversizedFails(t *testing.T) {
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-C")
	// Write 64KB + 100 bytes — over the cap.
	bigVal := strings.Repeat("x", outputsCapBytes)
	_ = os.WriteFile(path, []byte("BIG='"+bigVal+"'\n"), 0o600)
	_, err := parseOutputsFile(path, map[string]string{"big": "BIG"})
	if err == nil {
		t.Fatal("expected cap error")
	}
	if !strings.Contains(err.Error(), "cap") {
		t.Errorf("error should mention the cap, got: %v", err)
	}
}

func TestParseOutputsFile_BadKeyShape(t *testing.T) {
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-D")
	// `bad-key` contains a dash — not POSIX env-name; reject loud.
	_ = os.WriteFile(path, []byte("bad-key='v1'\n"), 0o600)
	_, err := parseOutputsFile(path, map[string]string{"alias": "bad-key"})
	if err == nil {
		t.Fatal("expected error for non-POSIX key")
	}
	if !strings.Contains(err.Error(), "POSIX") {
		t.Errorf("error should explain the POSIX constraint, got: %v", err)
	}
}

func TestParseOutputsFile_DuplicateKey(t *testing.T) {
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-E")
	_ = os.WriteFile(path, []byte("NEXT='v1'\nNEXT='v2'\n"), 0o600)
	_, err := parseOutputsFile(path, map[string]string{"next": "NEXT"})
	if err == nil {
		t.Fatal("expected error for duplicate key")
	}
	if !strings.Contains(err.Error(), "duplicate") {
		t.Errorf("error should mention 'duplicate', got: %v", err)
	}
}

func TestParseOutputsFile_NULByteFails(t *testing.T) {
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-F")
	_ = os.WriteFile(path, []byte("NEXT=v1\x00\n"), 0o600)
	_, err := parseOutputsFile(path, map[string]string{"next": "NEXT"})
	if err == nil {
		t.Fatal("expected NUL byte rejection")
	}
	if !strings.Contains(err.Error(), "NUL") {
		t.Errorf("error should mention NUL, got: %v", err)
	}
}

func TestParseOutputsFile_MissingFileWhenDeclared(t *testing.T) {
	// Job declared outputs but plugin DIDN'T write anything; the
	// file would be empty (we touched it pre-tasks). Test the
	// "file doesn't exist" path too — could happen if a plugin
	// `rm -rf` accidentally deleted .gocdnext/.
	_, err := parseOutputsFile("/does/not/exist", map[string]string{"next": "NEXT"})
	if err == nil {
		t.Fatal("expected error for missing file")
	}
	if !strings.Contains(err.Error(), outputsEnvName) {
		t.Errorf("error should mention GOCDNEXT_OUTPUT_FILE, got: %v", err)
	}
}

func TestParseOutputsFile_AcceptsUnquotedValues(t *testing.T) {
	// Some plugins write KEY=value without quotes — parser must
	// handle both forms.
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-G")
	_ = os.WriteFile(path, []byte("NEXT=v1.0.0\nMSG=\"with spaces\"\n"), 0o600)
	out, err := parseOutputsFile(path, map[string]string{
		"next": "NEXT",
		"msg":  "MSG",
	})
	if err != nil {
		t.Fatal(err)
	}
	if out["next"] != "v1.0.0" {
		t.Errorf("next = %q, want v1.0.0", out["next"])
	}
	if out["msg"] != "with spaces" {
		t.Errorf("msg = %q, want with spaces", out["msg"])
	}
}

func TestParseOutputsFile_SkipsCommentsAndBlankLines(t *testing.T) {
	work := t.TempDir()
	path, _ := prepareOutputsFile(work, "job-H")
	content := `# Generated by gocdnext/semver-bump
# Do not edit.

NEXT='v1.0.0'

# trailing comment
`
	_ = os.WriteFile(path, []byte(content), 0o600)
	out, err := parseOutputsFile(path, map[string]string{"next": "NEXT"})
	if err != nil {
		t.Fatal(err)
	}
	if out["next"] != "v1.0.0" {
		t.Errorf("next = %q, want v1.0.0", out["next"])
	}
}
