// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents_detail.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAgentWithRunning = `-- name: FindAgentWithRunning :one
SELECT a.id,
       a.name,
       a.version,
       a.os,
       a.arch,
       a.tags,
       a.capacity,
       a.status,
       a.last_seen_at,
       a.registered_at,
       COALESCE(SUM(CASE WHEN jr.status = 'running' THEN 1 ELSE 0 END), 0)::bigint AS running_jobs
FROM agents a
LEFT JOIN job_runs jr ON jr.agent_id = a.id AND jr.status IN ('running', 'queued')
WHERE a.id = $1
GROUP BY a.id
`

type FindAgentWithRunningRow struct {
	ID           pgtype.UUID
	Name         string
	Version      *string
	Os           *string
	Arch         *string
	Tags         []string
	Capacity     int32
	Status       string
	LastSeenAt   pgtype.Timestamptz
	RegisteredAt pgtype.Timestamptz
	RunningJobs  int64
}

// Same shape as ListAgentsWithRunning but for one row — reused by
// the /agents/{id} page. Returns ErrNoRows when the UUID is not
// an existing agent.
func (q *Queries) FindAgentWithRunning(ctx context.Context, id pgtype.UUID) (FindAgentWithRunningRow, error) {
	row := q.db.QueryRow(ctx, findAgentWithRunning, id)
	var i FindAgentWithRunningRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.Tags,
		&i.Capacity,
		&i.Status,
		&i.LastSeenAt,
		&i.RegisteredAt,
		&i.RunningJobs,
	)
	return i, err
}

const listJobsForAgent = `-- name: ListJobsForAgent :many
SELECT jr.id            AS job_run_id,
       jr.name          AS job_name,
       jr.status        AS job_status,
       jr.started_at,
       jr.finished_at,
       jr.exit_code,
       r.id             AS run_id,
       r.counter        AS run_counter,
       pl.name          AS pipeline_name,
       p.id             AS project_id,
       p.slug           AS project_slug,
       p.name           AS project_name
FROM job_runs jr
JOIN runs      r  ON r.id  = jr.run_id
JOIN pipelines pl ON pl.id = r.pipeline_id
JOIN projects  p  ON p.id  = pl.project_id
WHERE jr.agent_id = $1
ORDER BY jr.started_at DESC NULLS LAST, jr.id DESC
LIMIT $2
`

type ListJobsForAgentParams struct {
	AgentID pgtype.UUID
	Limit   int32
}

type ListJobsForAgentRow struct {
	JobRunID     pgtype.UUID
	JobName      string
	JobStatus    string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	ExitCode     *int32
	RunID        pgtype.UUID
	RunCounter   int64
	PipelineName string
	ProjectID    pgtype.UUID
	ProjectSlug  string
	ProjectName  string
}

// Recent jobs dispatched to this agent. Joined all the way up to
// the project so the table can link to the owning run/project
// without per-row lookups. LIMIT is caller-supplied to avoid
// pagination complexity for now (UI caps at 100).
func (q *Queries) ListJobsForAgent(ctx context.Context, arg ListJobsForAgentParams) ([]ListJobsForAgentRow, error) {
	rows, err := q.db.Query(ctx, listJobsForAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsForAgentRow{}
	for rows.Next() {
		var i ListJobsForAgentRow
		if err := rows.Scan(
			&i.JobRunID,
			&i.JobName,
			&i.JobStatus,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.RunID,
			&i.RunCounter,
			&i.PipelineName,
			&i.ProjectID,
			&i.ProjectSlug,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
