// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAgentByName = `-- name: FindAgentByName :one
SELECT id, name, token_hash, version, os, arch, tags, capacity, status, last_seen_at, registered_at
FROM agents
WHERE name = $1
LIMIT 1
`

func (q *Queries) FindAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRow(ctx, findAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.Tags,
		&i.Capacity,
		&i.Status,
		&i.LastSeenAt,
		&i.RegisteredAt,
	)
	return i, err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (name, token_hash, version, os, arch, tags, capacity, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, token_hash, version, os, arch, tags, capacity, status, last_seen_at, registered_at
`

type InsertAgentParams struct {
	Name      string
	TokenHash string
	Version   *string
	Os        *string
	Arch      *string
	Tags      []string
	Capacity  int32
	Status    string
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.Name,
		arg.TokenHash,
		arg.Version,
		arg.Os,
		arg.Arch,
		arg.Tags,
		arg.Capacity,
		arg.Status,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.Tags,
		&i.Capacity,
		&i.Status,
		&i.LastSeenAt,
		&i.RegisteredAt,
	)
	return i, err
}

const markAgentOffline = `-- name: MarkAgentOffline :exec
UPDATE agents
SET status = 'offline'
WHERE id = $1
`

func (q *Queries) MarkAgentOffline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAgentOffline, id)
	return err
}

const updateAgentOnRegister = `-- name: UpdateAgentOnRegister :exec
UPDATE agents
SET version      = $2,
    os           = $3,
    arch         = $4,
    tags         = $5,
    capacity     = $6,
    status       = 'online',
    last_seen_at = NOW()
WHERE id = $1
`

type UpdateAgentOnRegisterParams struct {
	ID       pgtype.UUID
	Version  *string
	Os       *string
	Arch     *string
	Tags     []string
	Capacity int32
}

func (q *Queries) UpdateAgentOnRegister(ctx context.Context, arg UpdateAgentOnRegisterParams) error {
	_, err := q.db.Exec(ctx, updateAgentOnRegister,
		arg.ID,
		arg.Version,
		arg.Os,
		arg.Arch,
		arg.Tags,
		arg.Capacity,
	)
	return err
}
