// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const doraBottleneck = `-- name: DoraBottleneck :one
WITH eligible AS (
    -- Universe = every successful, non-rollback deploy in the window. run/job/
    -- sha/PR are LEFT-joined so a deploy whose run was retention-pruned, or that
    -- has no git revision, or no matching PR, still counts (as ` + "`" + `excluded` + "`" + `)
    -- rather than vanishing — deployment_revisions outlives the run on purpose.
    SELECT dr.finished_at AS deploy_finished,
           djr.started_at AS deploy_started,
           pr.first_commit_at, pr.opened_at, pr.approved_at, pr.merged_at,
           (pr.id IS NOT NULL) AS correlated
    FROM deployment_revisions dr
    JOIN environments e ON e.id = dr.environment_id
    LEFT JOIN runs r ON r.id = dr.run_id
    LEFT JOIN job_runs djr ON djr.id = dr.job_run_id
    LEFT JOIN LATERAL (
        -- deployed commit SHA = the git material's revision in runs.revisions
        -- (non-empty branch; skips upstream). Deterministic pick by key so a
        -- multi-material run can't choose a different SHA across calls.
        SELECT rev.v ->> 'revision' AS sha
        FROM jsonb_each(r.revisions) AS rev(k, v)
        WHERE COALESCE(rev.v ->> 'branch', '') <> ''
        ORDER BY rev.k
        LIMIT 1
    ) dep ON TRUE
    LEFT JOIN LATERAL (
        -- One PR per deployed SHA — pick deterministically so mirrored repos
        -- sharing a merge SHA can't fan a deploy into multiple PR rows.
        SELECT vpr.id, vpr.first_commit_at, vpr.opened_at, vpr.approved_at, vpr.merged_at
        FROM vcs_pull_requests vpr
        WHERE vpr.merge_sha <> '' AND vpr.merge_sha = dep.sha
        ORDER BY vpr.merged_at DESC NULLS LAST, vpr.number DESC
        LIMIT 1
    ) pr ON TRUE
    WHERE dr.status = 'success'
      AND NOT dr.is_rollback
      AND dr.finished_at IS NOT NULL
      AND dr.finished_at >= current_date - make_interval(days => $1::int - 1)
      AND dr.finished_at <  now()
      AND ($2::text = '' OR e.name = $2)
      AND EXISTS (
          SELECT 1 FROM project_labels pl
          WHERE pl.project_id = e.project_id AND pl.key = $3
      )
)
SELECT
    COUNT(*) FILTER (WHERE correlated)::bigint AS correlated,
    COUNT(*) FILTER (WHERE NOT correlated)::bigint AS excluded,
    COUNT(*) FILTER (WHERE correlated AND first_commit_at IS NOT NULL AND opened_at >= first_commit_at)::bigint AS coding_sample,
    COUNT(*) FILTER (WHERE correlated AND approved_at IS NOT NULL AND opened_at IS NOT NULL AND approved_at >= opened_at)::bigint AS review_sample,
    COUNT(*) FILTER (WHERE correlated AND COALESCE(approved_at, merged_at) IS NOT NULL AND deploy_started >= COALESCE(approved_at, merged_at))::bigint AS release_sample,
    COUNT(*) FILTER (WHERE correlated AND deploy_finished >= deploy_started)::bigint AS deploy_sample,
    -- True end-to-end median (NOT the sum of stage p50s, which come from
    -- different samples). The header shows this; the bar shows the stage split.
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (deploy_finished - first_commit_at))::double precision
    ) FILTER (WHERE correlated AND first_commit_at IS NOT NULL AND deploy_finished >= first_commit_at), 0)::double precision AS total_p50_s,
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (opened_at - first_commit_at))::double precision
    ) FILTER (WHERE correlated AND first_commit_at IS NOT NULL AND opened_at >= first_commit_at), 0)::double precision AS coding_p50_s,
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (approved_at - opened_at))::double precision
    ) FILTER (WHERE correlated AND approved_at IS NOT NULL AND opened_at IS NOT NULL AND approved_at >= opened_at), 0)::double precision AS review_p50_s,
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (deploy_started - COALESCE(approved_at, merged_at)))::double precision
    ) FILTER (WHERE correlated AND COALESCE(approved_at, merged_at) IS NOT NULL AND deploy_started >= COALESCE(approved_at, merged_at)), 0)::double precision AS release_p50_s,
    COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
        ORDER BY EXTRACT(EPOCH FROM (deploy_finished - deploy_started))::double precision
    ) FILTER (WHERE correlated AND deploy_finished >= deploy_started), 0)::double precision AS deploy_p50_s
FROM eligible
`

type DoraBottleneckParams struct {
	SinceDays   int32
	Environment string
	LabelKey    string
}

type DoraBottleneckRow struct {
	Correlated    int64
	Excluded      int64
	CodingSample  int64
	ReviewSample  int64
	ReleaseSample int64
	DeploySample  int64
	TotalP50S     float64
	CodingP50S    float64
	ReviewP50S    float64
	ReleaseP50S   float64
	DeployP50S    float64
}

// Org lead-time decomposition over the trailing window: per-stage p50 across
// successful, NON-ROLLBACK deploys correlated to a pull request (deployed commit
// == vcs_pull_requests.merge_sha). Stages are consecutive: Coding (first commit
// → PR opened), Review (→ approval, only when approved_at exists), Release wait
// (approval/merge → deploy job start), Deploy (deploy job start → finish).
// Rollbacks are excluded entirely (a revert isn't new change-delivery and would
// inflate Release wait against an old approval). `eligible` = every successful
// non-rollback deploy in the window; `excluded` = those with no PR correlation
// (incl. retention-pruned runs / no git revision). Each stage exposes its own
// sample count, since p50s drop rows with missing boundaries.
func (q *Queries) DoraBottleneck(ctx context.Context, arg DoraBottleneckParams) (DoraBottleneckRow, error) {
	row := q.db.QueryRow(ctx, doraBottleneck, arg.SinceDays, arg.Environment, arg.LabelKey)
	var i DoraBottleneckRow
	err := row.Scan(
		&i.Correlated,
		&i.Excluded,
		&i.CodingSample,
		&i.ReviewSample,
		&i.ReleaseSample,
		&i.DeploySample,
		&i.TotalP50S,
		&i.CodingP50S,
		&i.ReviewP50S,
		&i.ReleaseP50S,
		&i.DeployP50S,
	)
	return i, err
}

const doraCountsGroup = `-- name: DoraCountsGroup :many
SELECT pl.value AS grp,
       COALESCE(SUM(d.deploys_success), 0)::bigint AS deploys_success,
       COALESCE(SUM(d.deploys_total), 0)::bigint AS deploys_total,
       COALESCE(SUM(d.deploys_failed), 0)::bigint AS deploys_failed
FROM project_labels pl
JOIN environments e ON e.project_id = pl.project_id
JOIN analytics_deploy_daily d ON d.environment_id = e.id
WHERE pl.key = $1
  AND ($2::text = '' OR e.name = $2)
  AND d.day >  current_date - $3::int
  AND d.day <= current_date - $4::int
GROUP BY pl.value
ORDER BY pl.value
`

type DoraCountsGroupParams struct {
	LabelKey    string
	Environment string
	SinceDays   int32
	UntilDays   int32
}

type DoraCountsGroupRow struct {
	Grp            string
	DeploysSuccess int64
	DeploysTotal   int64
	DeploysFailed  int64
}

// Deploy COUNTS per label-value group over the [since_days, until_days) day
// window, from the analytics_deploy_daily rollup (additive, O(days)). Pairs with
// DoraLeadGroup (live lead p50) + DoraMTTR (live). day-window mirrors the live
// interval window: current = (since=window, until=0); prior = (2×window, window).
func (q *Queries) DoraCountsGroup(ctx context.Context, arg DoraCountsGroupParams) ([]DoraCountsGroupRow, error) {
	rows, err := q.db.Query(ctx, doraCountsGroup,
		arg.LabelKey,
		arg.Environment,
		arg.SinceDays,
		arg.UntilDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoraCountsGroupRow{}
	for rows.Next() {
		var i DoraCountsGroupRow
		if err := rows.Scan(
			&i.Grp,
			&i.DeploysSuccess,
			&i.DeploysTotal,
			&i.DeploysFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doraCountsOrg = `-- name: DoraCountsOrg :one
SELECT COALESCE(SUM(d.deploys_success), 0)::bigint AS deploys_success,
       COALESCE(SUM(d.deploys_total), 0)::bigint AS deploys_total,
       COALESCE(SUM(d.deploys_failed), 0)::bigint AS deploys_failed
FROM analytics_deploy_daily d
JOIN environments e ON e.id = d.environment_id
WHERE d.day >  current_date - $1::int
  AND d.day <= current_date - $2::int
  AND EXISTS (
      SELECT 1 FROM project_labels pl
      WHERE pl.project_id = e.project_id AND pl.key = $3
  )
  AND ($4::text = '' OR e.name = $4)
`

type DoraCountsOrgParams struct {
	SinceDays   int32
	UntilDays   int32
	LabelKey    string
	Environment string
}

type DoraCountsOrgRow struct {
	DeploysSuccess int64
	DeploysTotal   int64
	DeploysFailed  int64
}

// Org-wide deploy COUNTS over the [since_days, until_days) day window, from the
// analytics_deploy_daily rollup. EXISTS (not a join) so an environment is
// counted once even if its project carries the key under several values.
// Current window = (since=window, until=0); prior = (2×window, window).
func (q *Queries) DoraCountsOrg(ctx context.Context, arg DoraCountsOrgParams) (DoraCountsOrgRow, error) {
	row := q.db.QueryRow(ctx, doraCountsOrg,
		arg.SinceDays,
		arg.UntilDays,
		arg.LabelKey,
		arg.Environment,
	)
	var i DoraCountsOrgRow
	err := row.Scan(&i.DeploysSuccess, &i.DeploysTotal, &i.DeploysFailed)
	return i, err
}

const doraDailyCounts = `-- name: DoraDailyCounts :many
WITH days AS (
    -- Exactly the days the agg counts: (current_date - since_days, current_date].
    SELECT generate_series(
        current_date - $1::int + 1,
        current_date,
        interval '1 day'
    )::date AS day
),
agg AS (
    SELECT d.day AS day,
           SUM(d.deploys_success)::bigint AS deploys_success,
           SUM(d.deploys_total)::bigint AS deploys_total,
           SUM(d.deploys_failed)::bigint AS deploys_failed
    FROM analytics_deploy_daily d
    JOIN environments e ON e.id = d.environment_id
    WHERE d.day > current_date - $1::int
      AND EXISTS (
          SELECT 1 FROM project_labels pl
          WHERE pl.project_id = e.project_id AND pl.key = $2
      )
      AND ($3::text = '' OR e.name = $3)
    GROUP BY d.day
)
SELECT s.day AS day,
       COALESCE(a.deploys_success, 0)::bigint AS deploys_success,
       COALESCE(a.deploys_total, 0)::bigint AS deploys_total,
       COALESCE(a.deploys_failed, 0)::bigint AS deploys_failed
FROM days s
LEFT JOIN agg a ON a.day = s.day
ORDER BY s.day
`

type DoraDailyCountsParams struct {
	SinceDays   int32
	LabelKey    string
	Environment string
}

type DoraDailyCountsRow struct {
	Day            pgtype.Date
	DeploysSuccess int64
	DeploysTotal   int64
	DeploysFailed  int64
}

// Dense per-day org deploy COUNTS over the trailing window, from the rollup —
// feeds the hero sparklines. generate_series yields one row per calendar day
// (zero-filled) so a sparse window still plots an honest trend. Pairs with
// DoraDailyLead (live lead p50 per day), merged by day in the store.
func (q *Queries) DoraDailyCounts(ctx context.Context, arg DoraDailyCountsParams) ([]DoraDailyCountsRow, error) {
	rows, err := q.db.Query(ctx, doraDailyCounts, arg.SinceDays, arg.LabelKey, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoraDailyCountsRow{}
	for rows.Next() {
		var i DoraDailyCountsRow
		if err := rows.Scan(
			&i.Day,
			&i.DeploysSuccess,
			&i.DeploysTotal,
			&i.DeploysFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doraDailyLead = `-- name: DoraDailyLead :many
SELECT date_trunc('day', dr.finished_at)::date AS day,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
                    ORDER BY EXTRACT(EPOCH FROM (dr.finished_at - r.started_at))::double precision
                ) FILTER (WHERE dr.status = 'success' AND r.started_at IS NOT NULL),
                0)::double precision AS lead_time_p50_s
FROM deployment_revisions dr
JOIN environments e ON e.id = dr.environment_id
LEFT JOIN runs r ON r.id = dr.run_id
WHERE dr.status IN ('success', 'failed')
  AND dr.finished_at IS NOT NULL
  AND dr.finished_at >= current_date - make_interval(days => $1::int - 1)
  AND EXISTS (
      SELECT 1 FROM project_labels pl
      WHERE pl.project_id = e.project_id AND pl.key = $2
  )
  AND ($3::text = '' OR e.name = $3)
GROUP BY day
`

type DoraDailyLeadParams struct {
	SinceDays   int32
	LabelKey    string
	Environment string
}

type DoraDailyLeadRow struct {
	Day          pgtype.Date
	LeadTimeP50S float64
}

// Per-day org lead-time p50, LIVE (percentile can't be summed). Sparse — only
// days with successful deploys; the store left-joins these onto the dense
// DoraDailyCounts day list, defaulting missing days to 0.
func (q *Queries) DoraDailyLead(ctx context.Context, arg DoraDailyLeadParams) ([]DoraDailyLeadRow, error) {
	rows, err := q.db.Query(ctx, doraDailyLead, arg.SinceDays, arg.LabelKey, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoraDailyLeadRow{}
	for rows.Next() {
		var i DoraDailyLeadRow
		if err := rows.Scan(&i.Day, &i.LeadTimeP50S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doraLeadGroup = `-- name: DoraLeadGroup :many
WITH base AS (
    SELECT pl.value AS grp,
           dr.status,
           EXTRACT(EPOCH FROM (dr.finished_at - r.started_at))::double precision AS lead_s
    FROM project_labels pl
    JOIN environments e ON e.project_id = pl.project_id
    JOIN deployment_revisions dr ON dr.environment_id = e.id
    LEFT JOIN runs r ON r.id = dr.run_id
    WHERE pl.key = $1
      AND ($2::text = '' OR e.name = $2)
      AND dr.status IN ('success', 'failed')
      AND dr.finished_at IS NOT NULL
      AND dr.finished_at >= current_date - make_interval(days => $3::int - 1)
      AND dr.finished_at <  current_date - make_interval(days => $4::int - 1)
)
SELECT grp,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_s)
                FILTER (WHERE status = 'success' AND lead_s IS NOT NULL),
                0)::double precision AS lead_time_p50_s
FROM base
GROUP BY grp
ORDER BY grp
`

type DoraLeadGroupParams struct {
	LabelKey    string
	Environment string
	SinceDays   int32
	UntilDays   int32
}

type DoraLeadGroupRow struct {
	Grp          string
	LeadTimeP50S float64
}

// Lead-time p50 per group, LIVE from deploys + producing run (a median can't be
// summed across rollup buckets). Lead = producing run START → deploy finish
// (excludes queue wait). Same window as DoraCountsGroup, interval-based so the
// 00057 index applies.
func (q *Queries) DoraLeadGroup(ctx context.Context, arg DoraLeadGroupParams) ([]DoraLeadGroupRow, error) {
	rows, err := q.db.Query(ctx, doraLeadGroup,
		arg.LabelKey,
		arg.Environment,
		arg.SinceDays,
		arg.UntilDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoraLeadGroupRow{}
	for rows.Next() {
		var i DoraLeadGroupRow
		if err := rows.Scan(&i.Grp, &i.LeadTimeP50S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doraLeadOrg = `-- name: DoraLeadOrg :one
WITH base AS (
    SELECT dr.status,
           EXTRACT(EPOCH FROM (dr.finished_at - r.started_at))::double precision AS lead_s
    FROM deployment_revisions dr
    JOIN environments e ON e.id = dr.environment_id
    LEFT JOIN runs r ON r.id = dr.run_id
    WHERE dr.status IN ('success', 'failed')
      AND dr.finished_at IS NOT NULL
      AND dr.finished_at >= current_date - make_interval(days => $1::int - 1)
      AND dr.finished_at <  current_date - make_interval(days => $2::int - 1)
      AND EXISTS (
          SELECT 1 FROM project_labels pl
          WHERE pl.project_id = e.project_id AND pl.key = $3
      )
      AND ($4::text = '' OR e.name = $4)
)
SELECT COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lead_s)
                FILTER (WHERE status = 'success' AND lead_s IS NOT NULL),
                0)::double precision AS lead_time_p50_s
FROM base
`

type DoraLeadOrgParams struct {
	SinceDays   int32
	UntilDays   int32
	LabelKey    string
	Environment string
}

// Org-wide lead-time p50, LIVE (percentile can't be summed). Same window as
// DoraCountsOrg, interval-based for the 00057 index.
func (q *Queries) DoraLeadOrg(ctx context.Context, arg DoraLeadOrgParams) (float64, error) {
	row := q.db.QueryRow(ctx, doraLeadOrg,
		arg.SinceDays,
		arg.UntilDays,
		arg.LabelKey,
		arg.Environment,
	)
	var lead_time_p50_s float64
	err := row.Scan(&lead_time_p50_s)
	return lead_time_p50_s, err
}

const doraMTTR = `-- name: DoraMTTR :many
WITH failures AS (
    SELECT pl.value AS grp, dr.environment_id, dr.finished_at
    FROM project_labels pl
    JOIN environments e ON e.project_id = pl.project_id
    JOIN deployment_revisions dr ON dr.environment_id = e.id
    WHERE pl.key = $1
      AND ($2::text = '' OR e.name = $2)
      AND dr.status = 'failed'
      AND dr.finished_at IS NOT NULL
      AND dr.finished_at >= current_date - make_interval(days => $3::int - 1)
      AND dr.finished_at <  current_date - make_interval(days => $4::int - 1)
)
SELECT grp,
       COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
                    ORDER BY EXTRACT(EPOCH FROM (s.finished_at - f.finished_at))::double precision
                ) FILTER (WHERE s.finished_at IS NOT NULL),
                0)::double precision AS mttr_p50_s
FROM failures f
LEFT JOIN LATERAL (
    SELECT drs.finished_at
    FROM deployment_revisions drs
    WHERE drs.environment_id = f.environment_id
      AND drs.status = 'success'
      AND drs.finished_at IS NOT NULL
      AND drs.finished_at > f.finished_at
    ORDER BY drs.finished_at ASC
    LIMIT 1
) s ON TRUE
GROUP BY f.grp
`

type DoraMTTRParams struct {
	LabelKey    string
	Environment string
	SinceDays   int32
	UntilDays   int32
}

type DoraMTTRRow struct {
	Grp      string
	MttrP50S float64
}

// Median time-to-restore per group: for each FAILED deploy in the window, the
// gap to the next SUCCESS in the same environment. The restore lookup is a
// lateral index probe per failure instead of a self-scan over all historical
// deploy events for the label key.
func (q *Queries) DoraMTTR(ctx context.Context, arg DoraMTTRParams) ([]DoraMTTRRow, error) {
	rows, err := q.db.Query(ctx, doraMTTR,
		arg.LabelKey,
		arg.Environment,
		arg.SinceDays,
		arg.UntilDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoraMTTRRow{}
	for rows.Next() {
		var i DoraMTTRRow
		if err := rows.Scan(&i.Grp, &i.MttrP50S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doraWindowMTTR = `-- name: DoraWindowMTTR :one
WITH failures AS (
    SELECT dr.environment_id, dr.finished_at
    FROM deployment_revisions dr
    JOIN environments e ON e.id = dr.environment_id
    WHERE dr.status = 'failed'
      AND dr.finished_at IS NOT NULL
      AND dr.finished_at >= current_date - make_interval(days => $1::int - 1)
      AND dr.finished_at <  current_date - make_interval(days => $2::int - 1)
      AND EXISTS (
          SELECT 1 FROM project_labels pl
          WHERE pl.project_id = e.project_id AND pl.key = $3
      )
      AND ($4::text = '' OR e.name = $4)
)
SELECT COALESCE(PERCENTILE_CONT(0.5) WITHIN GROUP (
                    ORDER BY EXTRACT(EPOCH FROM (s.finished_at - f.finished_at))::double precision
                ) FILTER (WHERE s.finished_at IS NOT NULL),
                0)::double precision AS mttr_p50_s
FROM failures f
LEFT JOIN LATERAL (
    SELECT drs.finished_at
    FROM deployment_revisions drs
    WHERE drs.environment_id = f.environment_id
      AND drs.status = 'success'
      AND drs.finished_at IS NOT NULL
      AND drs.finished_at > f.finished_at
    ORDER BY drs.finished_at ASC
    LIMIT 1
) s ON TRUE
`

type DoraWindowMTTRParams struct {
	SinceDays   int32
	UntilDays   int32
	LabelKey    string
	Environment string
}

// Org-wide median time-to-restore over [since, until): for each FAILED deploy
// whose project carries the key, the gap to the next SUCCESS in the same
// environment (lateral index probe per failure).
func (q *Queries) DoraWindowMTTR(ctx context.Context, arg DoraWindowMTTRParams) (float64, error) {
	row := q.db.QueryRow(ctx, doraWindowMTTR,
		arg.SinceDays,
		arg.UntilDays,
		arg.LabelKey,
		arg.Environment,
	)
	var mttr_p50_s float64
	err := row.Scan(&mttr_p50_s)
	return mttr_p50_s, err
}

const listAnalyticsEnvironments = `-- name: ListAnalyticsEnvironments :many
SELECT DISTINCT e.name
FROM environments e
WHERE EXISTS (
        SELECT 1 FROM project_labels pl
        WHERE pl.project_id = e.project_id AND pl.key = $1
    )
  AND EXISTS (
        SELECT 1 FROM deployment_revisions dr
        WHERE dr.environment_id = e.id
          AND dr.status IN ('success', 'failed')
          AND dr.finished_at IS NOT NULL
    )
ORDER BY e.name
`

// Distinct environment names that have terminal deploys and belong to a project
// carrying the group-by key — the dashboard's "environment" filter options.
func (q *Queries) ListAnalyticsEnvironments(ctx context.Context, labelKey string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAnalyticsEnvironments, labelKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelKeys = `-- name: ListLabelKeys :many

SELECT DISTINCT key FROM project_labels ORDER BY key
`

// Cross-project analytics rollups, grouped by a project label key (the #107
// epic). All metrics derive from deployment_revisions + the producing run.
// Distinct label keys across all projects — the dashboard's "group by" picker.
func (q *Queries) ListLabelKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLabelKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
