// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, service_account_id, name, prefix,
       expires_at, last_used_at, revoked_at, created_at
FROM api_tokens
WHERE hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

type GetAPITokenByHashRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ServiceAccountID pgtype.UUID
	Name             string
	Prefix           string
	ExpiresAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

// Hot path: the bearer middleware probes this on every request.
// Returns NOT FOUND when revoked or expired so the middleware
// doesn't have to special-case those.
func (q *Queries) GetAPITokenByHash(ctx context.Context, hash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, hash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceAccountID,
		&i.Name,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenForSAOwner = `-- name: GetAPITokenForSAOwner :one
SELECT id, name, prefix, expires_at, last_used_at, revoked_at
FROM api_tokens
WHERE id = $1 AND service_account_id = $2
`

type GetAPITokenForSAOwnerParams struct {
	ID               pgtype.UUID
	ServiceAccountID pgtype.UUID
}

type GetAPITokenForSAOwnerRow struct {
	ID         pgtype.UUID
	Name       string
	Prefix     string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// Same, scoped to a service account (admin path).
func (q *Queries) GetAPITokenForSAOwner(ctx context.Context, arg GetAPITokenForSAOwnerParams) (GetAPITokenForSAOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenForSAOwner, arg.ID, arg.ServiceAccountID)
	var i GetAPITokenForSAOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenForUserOwner = `-- name: GetAPITokenForUserOwner :one
SELECT id, name, prefix, expires_at, last_used_at, revoked_at
FROM api_tokens
WHERE id = $1 AND user_id = $2
`

type GetAPITokenForUserOwnerParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetAPITokenForUserOwnerRow struct {
	ID         pgtype.UUID
	Name       string
	Prefix     string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

// Used by handlers that need to verify "this token belongs to this
// user before letting them revoke it" — not just any token.
func (q *Queries) GetAPITokenForUserOwner(ctx context.Context, arg GetAPITokenForUserOwnerParams) (GetAPITokenForUserOwnerRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenForUserOwner, arg.ID, arg.UserID)
	var i GetAPITokenForUserOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :one
INSERT INTO api_tokens (
    user_id, service_account_id, name, hash, prefix, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, service_account_id, name, prefix,
          expires_at, last_used_at, revoked_at, created_at
`

type InsertAPITokenParams struct {
	UserID           pgtype.UUID
	ServiceAccountID pgtype.UUID
	Name             string
	Hash             string
	Prefix           string
	ExpiresAt        pgtype.Timestamptz
}

type InsertAPITokenRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	ServiceAccountID pgtype.UUID
	Name             string
	Prefix           string
	ExpiresAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

// Stores a freshly-minted token. Caller passes the SHA-256 hex
// digest in `hash`; the plaintext is shown to the user once at
// creation time and never persisted. Either user_id OR
// service_account_id is set (XOR enforced by the table check).
func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) (InsertAPITokenRow, error) {
	row := q.db.QueryRow(ctx, insertAPIToken,
		arg.UserID,
		arg.ServiceAccountID,
		arg.Name,
		arg.Hash,
		arg.Prefix,
		arg.ExpiresAt,
	)
	var i InsertAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceAccountID,
		&i.Name,
		&i.Prefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensByServiceAccount = `-- name: ListAPITokensByServiceAccount :many
SELECT id, name, prefix, expires_at, last_used_at, revoked_at, created_at
FROM api_tokens
WHERE service_account_id = $1
ORDER BY created_at DESC
`

type ListAPITokensByServiceAccountRow struct {
	ID         pgtype.UUID
	Name       string
	Prefix     string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListAPITokensByServiceAccount(ctx context.Context, serviceAccountID pgtype.UUID) ([]ListAPITokensByServiceAccountRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensByServiceAccount, serviceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensByServiceAccountRow{}
	for rows.Next() {
		var i ListAPITokensByServiceAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, name, prefix, expires_at, last_used_at, revoked_at, created_at
FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPITokensByUserRow struct {
	ID         pgtype.UUID
	Name       string
	Prefix     string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Tokens this user owns, newest first. Used by /settings/api-tokens.
func (q *Queries) ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPITokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensByUserRow{}
	for rows.Next() {
		var i ListAPITokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

// Idempotent: revoke-on-already-revoked is a no-op. Caller filters
// by user_id or service_account_id to gate ownership.
func (q *Queries) RevokeAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = NOW()
WHERE id = $1
`

// Best-effort `last_used_at` bump. Called from the middleware
// when a Bearer token authenticates successfully — a stale value
// doesn't break anything, just makes the audit trail less useful.
func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPITokenLastUsed, id)
	return err
}
