// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimArtifactsForSweep = `-- name: ClaimArtifactsForSweep :many
UPDATE artifacts
SET status = 'deleting', deleted_at = NOW()
WHERE id IN (
    SELECT id FROM artifacts
    WHERE pinned_at IS NULL
      AND (
          (status = 'ready'
              AND expires_at IS NOT NULL
              AND expires_at < NOW())
          OR
          (status = 'deleting'
              AND deleted_at < NOW() - make_interval(mins => $2::int))
      )
    ORDER BY COALESCE(expires_at, deleted_at)
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, storage_key, size_bytes
`

type ClaimArtifactsForSweepParams struct {
	Limit   int32
	Column2 int32
}

type ClaimArtifactsForSweepRow struct {
	ID         pgtype.UUID
	StorageKey string
	SizeBytes  int64
}

// Atomically marks a bounded batch of artefacts as 'deleting' and
// returns their storage keys so the sweeper can call Store.Delete and
// then remove the DB row.
//
// Two populations get claimed:
//  1. Freshly-expired rows: status='ready' AND expires_at < now() AND
//     not pinned. Standard TTL sweep.
//  2. Rows left in 'deleting' for longer than the grace window — the
//     previous sweeper crashed between "marked deleting" and "storage
//     delete + row removed". We pick those up and retry idempotently.
//
// FOR UPDATE SKIP LOCKED makes this safe to run from multiple
// schedulers/sweepers at once; each gets a disjoint batch.
func (q *Queries) ClaimArtifactsForSweep(ctx context.Context, arg ClaimArtifactsForSweepParams) ([]ClaimArtifactsForSweepRow, error) {
	rows, err := q.db.Query(ctx, claimArtifactsForSweep, arg.Limit, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimArtifactsForSweepRow{}
	for rows.Next() {
		var i ClaimArtifactsForSweepRow
		if err := rows.Scan(&i.ID, &i.StorageKey, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireArtifactsBeyondKeepLast = `-- name: ExpireArtifactsBeyondKeepLast :execrows
WITH ranked AS (
  SELECT DISTINCT a.run_id, a.pipeline_id, r.created_at,
    row_number() OVER (
      PARTITION BY a.pipeline_id
      ORDER BY r.created_at DESC
    ) AS rn
  FROM artifacts a
  JOIN runs r ON r.id = a.run_id
  WHERE a.deleted_at IS NULL AND a.pinned_at IS NULL
)
UPDATE artifacts
SET expires_at = NOW()
WHERE run_id IN (SELECT run_id FROM ranked WHERE rn > $1::int)
  AND deleted_at IS NULL
  AND pinned_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

// Keep-last policy: per pipeline, rank the runs that produced
// non-deleted artefacts by recency (run.created_at DESC); any run
// beyond position N has ALL its non-pinned artefacts stamped with
// expires_at = NOW(). The next TTL sweep picks them up. Pinned rows
// are exempt; pinned runs don't consume a "slot" — they live forever
// orthogonally to the N budget.
func (q *Queries) ExpireArtifactsBeyondKeepLast(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, expireArtifactsBeyondKeepLast, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireOldestGloballyByExcess = `-- name: ExpireOldestGloballyByExcess :execrows
WITH running AS (
  SELECT a.id,
    COALESCE(SUM(a.size_bytes) OVER (
      ORDER BY a.created_at ASC
      ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
    ), 0)::bigint AS cum_prev
  FROM artifacts a
  WHERE a.deleted_at IS NULL AND a.pinned_at IS NULL
    AND a.status IN ('pending', 'ready')
)
UPDATE artifacts
SET expires_at = NOW()
WHERE id IN (SELECT id FROM running WHERE cum_prev < $1::bigint)
`

func (q *Queries) ExpireOldestGloballyByExcess(ctx context.Context, dollar_1 int64) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldestGloballyByExcess, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireOldestInProjectByExcess = `-- name: ExpireOldestInProjectByExcess :execrows
WITH running AS (
  SELECT a.id,
    COALESCE(SUM(a.size_bytes) OVER (
      ORDER BY a.created_at ASC
      ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
    ), 0)::bigint AS cum_prev
  FROM artifacts a
  WHERE a.project_id = $2::uuid
    AND a.deleted_at IS NULL AND a.pinned_at IS NULL
    AND a.status IN ('pending', 'ready')
)
UPDATE artifacts
SET expires_at = NOW()
WHERE id IN (SELECT id FROM running WHERE cum_prev < $1::bigint)
`

type ExpireOldestInProjectByExcessParams struct {
	Excess int64
	Pid    pgtype.UUID
}

// Stamp expires_at = NOW() on the oldest non-pinned rows in a project,
// stopping as soon as the demoted bytes cover `excess`. Uses a window
// function so the cut-off is computed against the cumulative-up-to-
// but-not-including-this-row (so we always demote enough, never
// less).
func (q *Queries) ExpireOldestInProjectByExcess(ctx context.Context, arg ExpireOldestInProjectByExcessParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireOldestInProjectByExcess, arg.Excess, arg.Pid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArtifactByStorageKey = `-- name: GetArtifactByStorageKey :one
SELECT id, run_id, job_run_id, pipeline_id, project_id,
       path, storage_key, status, size_bytes, content_sha256,
       expires_at, pinned_at, deleted_at, created_at
FROM artifacts
WHERE storage_key = $1
`

type GetArtifactByStorageKeyRow struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	PipelineID    pgtype.UUID
	ProjectID     pgtype.UUID
	Path          string
	StorageKey    string
	Status        string
	SizeBytes     int64
	ContentSha256 string
	ExpiresAt     pgtype.Timestamptz
	PinnedAt      pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// Single-row lookup for the JobResult confirmation path. Returns
// ErrNoRows if the agent invented a key or the row was swept.
func (q *Queries) GetArtifactByStorageKey(ctx context.Context, storageKey string) (GetArtifactByStorageKeyRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByStorageKey, storageKey)
	var i GetArtifactByStorageKeyRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobRunID,
		&i.PipelineID,
		&i.ProjectID,
		&i.Path,
		&i.StorageKey,
		&i.Status,
		&i.SizeBytes,
		&i.ContentSha256,
		&i.ExpiresAt,
		&i.PinnedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJobRunParents = `-- name: GetJobRunParents :one
SELECT r.pipeline_id AS pipeline_id,
       p.project_id  AS project_id,
       jr.agent_id   AS agent_id
FROM job_runs jr
JOIN runs r       ON r.id = jr.run_id
JOIN pipelines p  ON p.id = r.pipeline_id
WHERE jr.id = $1 AND jr.run_id = $2
`

type GetJobRunParentsParams struct {
	ID    pgtype.UUID
	RunID pgtype.UUID
}

type GetJobRunParentsRow struct {
	PipelineID pgtype.UUID
	ProjectID  pgtype.UUID
	AgentID    pgtype.UUID
}

// Resolves pipeline_id + project_id + agent_id for a (job_run_id,
// run_id) pair. Used by the RequestArtifactUpload handler to authorise
// + derive the FKs. Returns ErrNoRows if job_run_id doesn't belong to
// the claimed run_id. agent_id is NULL when the job hasn't been
// dispatched yet (shouldn't happen on this code path but the column
// nullability forces us to handle it).
func (q *Queries) GetJobRunParents(ctx context.Context, arg GetJobRunParentsParams) (GetJobRunParentsRow, error) {
	row := q.db.QueryRow(ctx, getJobRunParents, arg.ID, arg.RunID)
	var i GetJobRunParentsRow
	err := row.Scan(&i.PipelineID, &i.ProjectID, &i.AgentID)
	return i, err
}

const getRunUpstreamContext = `-- name: GetRunUpstreamContext :one
SELECT
  NULLIF(cause_detail->>'upstream_run_id',  '')::uuid AS upstream_run_id,
  (COALESCE(cause_detail->>'upstream_pipeline', ''))::text AS upstream_pipeline
FROM runs WHERE id = $1
`

type GetRunUpstreamContextRow struct {
	UpstreamRunID    pgtype.UUID
	UpstreamPipeline string
}

// For a downstream run, extracts upstream_run_id + upstream pipeline
// name from cause_detail JSON. Empty string / null UUID when this run
// was NOT triggered by an upstream material (cause is 'webhook' /
// 'manual'). Caller checks upstream_run_id.Valid.
func (q *Queries) GetRunUpstreamContext(ctx context.Context, id pgtype.UUID) (GetRunUpstreamContextRow, error) {
	row := q.db.QueryRow(ctx, getRunUpstreamContext, id)
	var i GetRunUpstreamContextRow
	err := row.Scan(&i.UpstreamRunID, &i.UpstreamPipeline)
	return i, err
}

const globalArtifactUsage = `-- name: GlobalArtifactUsage :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint AS bytes
FROM artifacts
WHERE deleted_at IS NULL
  AND pinned_at IS NULL
  AND status IN ('pending', 'ready')
`

// Total live artefact bytes. Returns 0 when the artifacts table is
// empty. Used for the global hard cap.
func (q *Queries) GlobalArtifactUsage(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, globalArtifactUsage)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const insertPendingArtifact = `-- name: InsertPendingArtifact :one
INSERT INTO artifacts (
    run_id, job_run_id, pipeline_id, project_id,
    path, storage_key, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, run_id, job_run_id, pipeline_id, project_id,
          path, storage_key, status, expires_at, created_at
`

type InsertPendingArtifactParams struct {
	RunID      pgtype.UUID
	JobRunID   pgtype.UUID
	PipelineID pgtype.UUID
	ProjectID  pgtype.UUID
	Path       string
	StorageKey string
	ExpiresAt  pgtype.Timestamptz
}

type InsertPendingArtifactRow struct {
	ID         pgtype.UUID
	RunID      pgtype.UUID
	JobRunID   pgtype.UUID
	PipelineID pgtype.UUID
	ProjectID  pgtype.UUID
	Path       string
	StorageKey string
	Status     string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Inserts a row in `pending` status ahead of the agent's upload. The
// storage_key is generated by the caller (UUID-based) so the row's id and
// the backend's object key are decoupled — makes it safe to retry without
// ending up with orphan objects keyed off a stale PK.
func (q *Queries) InsertPendingArtifact(ctx context.Context, arg InsertPendingArtifactParams) (InsertPendingArtifactRow, error) {
	row := q.db.QueryRow(ctx, insertPendingArtifact,
		arg.RunID,
		arg.JobRunID,
		arg.PipelineID,
		arg.ProjectID,
		arg.Path,
		arg.StorageKey,
		arg.ExpiresAt,
	)
	var i InsertPendingArtifactRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobRunID,
		&i.PipelineID,
		&i.ProjectID,
		&i.Path,
		&i.StorageKey,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByJobRun = `-- name: ListArtifactsByJobRun :many
SELECT id, run_id, job_run_id, pipeline_id, project_id,
       path, storage_key, status, size_bytes, content_sha256,
       expires_at, pinned_at, deleted_at, created_at
FROM artifacts
WHERE job_run_id = $1
ORDER BY created_at
`

type ListArtifactsByJobRunRow struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	PipelineID    pgtype.UUID
	ProjectID     pgtype.UUID
	Path          string
	StorageKey    string
	Status        string
	SizeBytes     int64
	ContentSha256 string
	ExpiresAt     pgtype.Timestamptz
	PinnedAt      pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// Used by server-side JobResult reconciliation to match ArtifactRef
// entries back to their pending rows. Also used later (E2c) to expose
// downloads to downstream jobs in the same run.
func (q *Queries) ListArtifactsByJobRun(ctx context.Context, jobRunID pgtype.UUID) ([]ListArtifactsByJobRunRow, error) {
	rows, err := q.db.Query(ctx, listArtifactsByJobRun, jobRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsByJobRunRow{}
	for rows.Next() {
		var i ListArtifactsByJobRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobRunID,
			&i.PipelineID,
			&i.ProjectID,
			&i.Path,
			&i.StorageKey,
			&i.Status,
			&i.SizeBytes,
			&i.ContentSha256,
			&i.ExpiresAt,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByRun = `-- name: ListArtifactsByRun :many
SELECT id, run_id, job_run_id, pipeline_id, project_id,
       path, storage_key, status, size_bytes, content_sha256,
       expires_at, pinned_at, deleted_at, created_at
FROM artifacts
WHERE run_id = $1 AND status = 'ready'
  AND deleted_at IS NULL
ORDER BY created_at
`

type ListArtifactsByRunRow struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	PipelineID    pgtype.UUID
	ProjectID     pgtype.UUID
	Path          string
	StorageKey    string
	Status        string
	SizeBytes     int64
	ContentSha256 string
	ExpiresAt     pgtype.Timestamptz
	PinnedAt      pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

// Used by E2c for intra-run downloads (`needs_artifacts:` resolution).
// Only returns ready artefacts — pending/deleting must not leak as
// dependable to downstream jobs.
func (q *Queries) ListArtifactsByRun(ctx context.Context, runID pgtype.UUID) ([]ListArtifactsByRunRow, error) {
	rows, err := q.db.Query(ctx, listArtifactsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsByRunRow{}
	for rows.Next() {
		var i ListArtifactsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobRunID,
			&i.PipelineID,
			&i.ProjectID,
			&i.Path,
			&i.StorageKey,
			&i.Status,
			&i.SizeBytes,
			&i.ContentSha256,
			&i.ExpiresAt,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsWithJobByRun = `-- name: ListArtifactsWithJobByRun :many
SELECT a.id, a.run_id, a.job_run_id, a.pipeline_id, a.project_id,
       a.path, a.storage_key, a.status, a.size_bytes, a.content_sha256,
       a.expires_at, a.pinned_at, a.deleted_at, a.created_at,
       jr.name AS job_name
FROM artifacts a
JOIN job_runs jr ON jr.id = a.job_run_id
WHERE a.run_id = $1 AND a.deleted_at IS NULL
ORDER BY jr.name, a.path
`

type ListArtifactsWithJobByRunRow struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	PipelineID    pgtype.UUID
	ProjectID     pgtype.UUID
	Path          string
	StorageKey    string
	Status        string
	SizeBytes     int64
	ContentSha256 string
	ExpiresAt     pgtype.Timestamptz
	PinnedAt      pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	JobName       string
}

// Same as ListArtifactsByRun but joined with job_runs.name so the UI
// can group artefacts by the job that produced them without an extra
// per-artifact lookup. Returns ALL statuses — callers filter as needed.
func (q *Queries) ListArtifactsWithJobByRun(ctx context.Context, runID pgtype.UUID) ([]ListArtifactsWithJobByRunRow, error) {
	rows, err := q.db.Query(ctx, listArtifactsWithJobByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsWithJobByRunRow{}
	for rows.Next() {
		var i ListArtifactsWithJobByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobRunID,
			&i.PipelineID,
			&i.ProjectID,
			&i.Path,
			&i.StorageKey,
			&i.Status,
			&i.SizeBytes,
			&i.ContentSha256,
			&i.ExpiresAt,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.JobName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsOverArtifactQuota = `-- name: ListProjectsOverArtifactQuota :many
SELECT a.project_id, COALESCE(SUM(a.size_bytes), 0)::bigint AS bytes
FROM artifacts a
WHERE a.deleted_at IS NULL
  AND a.pinned_at IS NULL
  AND a.status IN ('pending', 'ready')
GROUP BY a.project_id
HAVING COALESCE(SUM(a.size_bytes), 0) > $1::bigint
`

type ListProjectsOverArtifactQuotaRow struct {
	ProjectID pgtype.UUID
	Bytes     int64
}

// Projects whose total live artefact bytes (pending + ready, non-
// deleted, non-pinned) exceed the configured soft cap. Returned once
// per tick so the sweeper can ExpireOldestInProjectByExcess against
// each one individually.
func (q *Queries) ListProjectsOverArtifactQuota(ctx context.Context, dollar_1 int64) ([]ListProjectsOverArtifactQuotaRow, error) {
	rows, err := q.db.Query(ctx, listProjectsOverArtifactQuota, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsOverArtifactQuotaRow{}
	for rows.Next() {
		var i ListProjectsOverArtifactQuotaRow
		if err := rows.Scan(&i.ProjectID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyArtifactsByRunAndJobName = `-- name: ListReadyArtifactsByRunAndJobName :many
SELECT a.id, a.run_id, a.job_run_id, a.pipeline_id, a.project_id,
       a.path, a.storage_key, a.status, a.size_bytes, a.content_sha256,
       a.expires_at, a.pinned_at, a.deleted_at, a.created_at,
       jr.name AS job_name
FROM artifacts a
JOIN job_runs jr ON jr.id = a.job_run_id
WHERE a.run_id = $1
  AND jr.name  = $2
  AND a.status = 'ready'
  AND a.deleted_at IS NULL
  AND (cardinality($3::text[]) = 0 OR a.path = ANY($3::text[]))
ORDER BY a.path
`

type ListReadyArtifactsByRunAndJobNameParams struct {
	RunID   pgtype.UUID
	Name    string
	Column3 []string
}

type ListReadyArtifactsByRunAndJobNameRow struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	PipelineID    pgtype.UUID
	ProjectID     pgtype.UUID
	Path          string
	StorageKey    string
	Status        string
	SizeBytes     int64
	ContentSha256 string
	ExpiresAt     pgtype.Timestamptz
	PinnedAt      pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	JobName       string
}

// Returns ready artefacts produced by a specific job name within a run,
// optionally filtered by a path whitelist. Used by the scheduler when
// resolving `needs_artifacts` on a downstream job. An empty paths
// array returns all of that job's artefacts.
func (q *Queries) ListReadyArtifactsByRunAndJobName(ctx context.Context, arg ListReadyArtifactsByRunAndJobNameParams) ([]ListReadyArtifactsByRunAndJobNameRow, error) {
	rows, err := q.db.Query(ctx, listReadyArtifactsByRunAndJobName, arg.RunID, arg.Name, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyArtifactsByRunAndJobNameRow{}
	for rows.Next() {
		var i ListReadyArtifactsByRunAndJobNameRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobRunID,
			&i.PipelineID,
			&i.ProjectID,
			&i.Path,
			&i.StorageKey,
			&i.Status,
			&i.SizeBytes,
			&i.ContentSha256,
			&i.ExpiresAt,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.JobName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactReady = `-- name: MarkArtifactReady :execrows
UPDATE artifacts
SET status = 'ready',
    size_bytes = $2,
    content_sha256 = $3
WHERE storage_key = $1 AND status = 'pending'
`

type MarkArtifactReadyParams struct {
	StorageKey    string
	SizeBytes     int64
	ContentSha256 string
}

// Called after the server HEADs the storage and confirms the object is
// there. Bumps status + records size/sha. Safe to call once; subsequent
// calls update nothing (status already 'ready'), returning 0 rows.
func (q *Queries) MarkArtifactReady(ctx context.Context, arg MarkArtifactReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markArtifactReady, arg.StorageKey, arg.SizeBytes, arg.ContentSha256)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeArtifactRow = `-- name: RemoveArtifactRow :execrows
DELETE FROM artifacts WHERE id = $1
`

// Called by the sweeper AFTER Store.Delete succeeded (or the object
// was already gone). Removes the DB row.
func (q *Queries) RemoveArtifactRow(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeArtifactRow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
