// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAuthProvider = `-- name: DeleteAuthProvider :exec
DELETE FROM auth_providers WHERE id = $1
`

func (q *Queries) DeleteAuthProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthProvider, id)
	return err
}

const getAuthProviderByID = `-- name: GetAuthProviderByID :one
SELECT id, name, kind, display_name, client_id, client_secret,
       issuer, github_api_base, enabled, created_at, updated_at
FROM auth_providers
WHERE id = $1
`

func (q *Queries) GetAuthProviderByID(ctx context.Context, id pgtype.UUID) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, getAuthProviderByID, id)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DisplayName,
		&i.ClientID,
		&i.ClientSecret,
		&i.Issuer,
		&i.GithubApiBase,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthProviders = `-- name: ListAuthProviders :many
SELECT id, name, kind, display_name, client_id, client_secret,
       issuer, github_api_base, enabled, created_at, updated_at
FROM auth_providers
ORDER BY name ASC
`

// Returns every row regardless of `enabled`. The UI filters on
// the boolean so admins can see disabled providers they can re-
// enable later.
func (q *Queries) ListAuthProviders(ctx context.Context) ([]AuthProvider, error) {
	rows, err := q.db.Query(ctx, listAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthProvider{}
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.DisplayName,
			&i.ClientID,
			&i.ClientSecret,
			&i.Issuer,
			&i.GithubApiBase,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAuthProviders = `-- name: ListEnabledAuthProviders :many
SELECT id, name, kind, display_name, client_id, client_secret,
       issuer, github_api_base, enabled, created_at, updated_at
FROM auth_providers
WHERE enabled = TRUE
ORDER BY name ASC
`

// Bootstrap path: just the ones that should be registered on
// server start (or after a reload).
func (q *Queries) ListEnabledAuthProviders(ctx context.Context) ([]AuthProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthProvider{}
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.DisplayName,
			&i.ClientID,
			&i.ClientSecret,
			&i.Issuer,
			&i.GithubApiBase,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAuthProviderEnabled = `-- name: SetAuthProviderEnabled :exec
UPDATE auth_providers
SET enabled = $2, updated_at = NOW()
WHERE id = $1
`

type SetAuthProviderEnabledParams struct {
	ID      pgtype.UUID
	Enabled bool
}

func (q *Queries) SetAuthProviderEnabled(ctx context.Context, arg SetAuthProviderEnabledParams) error {
	_, err := q.db.Exec(ctx, setAuthProviderEnabled, arg.ID, arg.Enabled)
	return err
}

const upsertAuthProvider = `-- name: UpsertAuthProvider :one
INSERT INTO auth_providers (
    name, kind, display_name, client_id, client_secret,
    issuer, github_api_base, enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    kind            = EXCLUDED.kind,
    display_name    = EXCLUDED.display_name,
    client_id       = EXCLUDED.client_id,
    client_secret   = EXCLUDED.client_secret,
    issuer          = EXCLUDED.issuer,
    github_api_base = EXCLUDED.github_api_base,
    enabled         = EXCLUDED.enabled,
    updated_at      = NOW()
RETURNING id, name, kind, display_name, client_id, client_secret,
          issuer, github_api_base, enabled, created_at, updated_at
`

type UpsertAuthProviderParams struct {
	Name          string
	Kind          string
	DisplayName   string
	ClientID      string
	ClientSecret  []byte
	Issuer        string
	GithubApiBase string
	Enabled       bool
}

// ON CONFLICT (name) DO UPDATE bumps kind + display + id/secret
// + issuer + api base + enabled. We never update created_at.
func (q *Queries) UpsertAuthProvider(ctx context.Context, arg UpsertAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, upsertAuthProvider,
		arg.Name,
		arg.Kind,
		arg.DisplayName,
		arg.ClientID,
		arg.ClientSecret,
		arg.Issuer,
		arg.GithubApiBase,
		arg.Enabled,
	)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.DisplayName,
		&i.ClientID,
		&i.ClientSecret,
		&i.Issuer,
		&i.GithubApiBase,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
