// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthState = `-- name: ConsumeAuthState :one
DELETE FROM auth_states
WHERE state_hash = $1 AND expires_at > NOW()
RETURNING provider, redirect_to, nonce
`

type ConsumeAuthStateRow struct {
	Provider   string
	RedirectTo string
	Nonce      string
}

// Single-use: delete as we read. Returning nothing = no such state
// (or it expired and the sweeper got to it first).
func (q *Queries) ConsumeAuthState(ctx context.Context, stateHash []byte) (ConsumeAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeAuthState, stateHash)
	var i ConsumeAuthStateRow
	err := row.Scan(&i.Provider, &i.RedirectTo, &i.Nonce)
	return i, err
}

const deleteExpiredAuthStates = `-- name: DeleteExpiredAuthStates :exec
DELETE FROM auth_states WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthStates)
	return err
}

const deleteExpiredUserSessions = `-- name: DeleteExpiredUserSessions :exec
DELETE FROM user_sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredUserSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredUserSessions)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions WHERE id = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteUserSession, id)
	return err
}

const deleteUserSessionsForUser = `-- name: DeleteUserSessionsForUser :exec
DELETE FROM user_sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessionsForUser, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, avatar_url, provider, external_id, role,
       disabled_at, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ExternalID,
		&i.Role,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT u.id, u.email, u.name, u.avatar_url, u.provider, u.external_id,
       u.role, u.disabled_at, u.last_login_at, u.created_at, u.updated_at,
       s.expires_at, s.last_seen_at
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.expires_at > NOW()
`

type GetUserSessionRow struct {
	ID          pgtype.UUID
	Email       string
	Name        string
	AvatarUrl   string
	Provider    string
	ExternalID  string
	Role        string
	DisabledAt  pgtype.Timestamptz
	LastLoginAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

// Returns the session + its user row. Expired rows are filtered in
// the query so a single round-trip tells the handler "yes/no".
func (q *Queries) GetUserSession(ctx context.Context, id []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, id)
	var i GetUserSessionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ExternalID,
		&i.Role,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertAuthState = `-- name: InsertAuthState :exec
INSERT INTO auth_states (state_hash, provider, redirect_to, nonce, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuthStateParams struct {
	StateHash  []byte
	Provider   string
	RedirectTo string
	Nonce      string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) InsertAuthState(ctx context.Context, arg InsertAuthStateParams) error {
	_, err := q.db.Exec(ctx, insertAuthState,
		arg.StateHash,
		arg.Provider,
		arg.RedirectTo,
		arg.Nonce,
		arg.ExpiresAt,
	)
	return err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO user_sessions (id, user_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
`

type InsertUserSessionParams struct {
	ID        []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UserAgent string
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, avatar_url, provider, external_id, role,
       disabled_at, last_login_at, created_at, updated_at
FROM users
ORDER BY email ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Provider,
			&i.ExternalID,
			&i.Role,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions
SET last_seen_at = NOW()
WHERE id = $1
`

// Cheap idempotent update; called at most once per request via a
// debounce in the middleware so we don't rewrite the row on every
// 2s dashboard poll.
func (q *Queries) TouchUserSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, touchUserSession, id)
	return err
}

const upsertUserByProvider = `-- name: UpsertUserByProvider :one
INSERT INTO users (email, name, avatar_url, provider, external_id, role, last_login_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (provider, external_id) DO UPDATE SET
    email        = EXCLUDED.email,
    name         = EXCLUDED.name,
    avatar_url   = EXCLUDED.avatar_url,
    last_login_at = NOW(),
    updated_at   = NOW()
RETURNING id, email, name, avatar_url, provider, external_id, role,
          disabled_at, last_login_at, created_at, updated_at
`

type UpsertUserByProviderParams struct {
	Email      string
	Name       string
	AvatarUrl  string
	Provider   string
	ExternalID string
	Role       string
}

// Either inserts a fresh row (new login) or bumps the profile
// fields we pull from the IdP every time. Role is intentionally
// NOT overwritten on conflict — it's admin-assigned and must not
// revert to 'user' just because the IdP doesn't carry it.
func (q *Queries) UpsertUserByProvider(ctx context.Context, arg UpsertUserByProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByProvider,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Provider,
		arg.ExternalID,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Provider,
		&i.ExternalID,
		&i.Role,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
