// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: compliance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFrameworkUsage = `-- name: CountFrameworkUsage :one
SELECT
  (SELECT COUNT(*) FROM project_frameworks pf WHERE pf.framework_id = $1) AS project_count,
  (SELECT COUNT(*) FROM policy_frameworks  pl WHERE pl.framework_id = $1) AS policy_count
`

type CountFrameworkUsageRow struct {
	ProjectCount int64
	PolicyCount  int64
}

// Delete-guard: how many projects carry the framework and how many policies
// target it. A framework still in use must not be silently dropped.
func (q *Queries) CountFrameworkUsage(ctx context.Context, frameworkID pgtype.UUID) (CountFrameworkUsageRow, error) {
	row := q.db.QueryRow(ctx, countFrameworkUsage, frameworkID)
	var i CountFrameworkUsageRow
	err := row.Scan(&i.ProjectCount, &i.PolicyCount)
	return i, err
}

const deleteComplianceFramework = `-- name: DeleteComplianceFramework :exec
DELETE FROM compliance_frameworks WHERE id = $1
`

func (q *Queries) DeleteComplianceFramework(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComplianceFramework, id)
	return err
}

const deleteCompliancePolicy = `-- name: DeleteCompliancePolicy :exec
DELETE FROM compliance_policies WHERE id = $1
`

func (q *Queries) DeleteCompliancePolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompliancePolicy, id)
	return err
}

const deletePolicyFrameworks = `-- name: DeletePolicyFrameworks :exec
DELETE FROM policy_frameworks WHERE policy_id = $1
`

func (q *Queries) DeletePolicyFrameworks(ctx context.Context, policyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicyFrameworks, policyID)
	return err
}

const deleteProjectFrameworks = `-- name: DeleteProjectFrameworks :exec
DELETE FROM project_frameworks WHERE project_id = $1
`

func (q *Queries) DeleteProjectFrameworks(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFrameworks, projectID)
	return err
}

const getComplianceFramework = `-- name: GetComplianceFramework :one
SELECT id, name, description, created_by, created_at, updated_at
FROM compliance_frameworks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetComplianceFramework(ctx context.Context, id pgtype.UUID) (ComplianceFramework, error) {
	row := q.db.QueryRow(ctx, getComplianceFramework, id)
	var i ComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompliancePolicy = `-- name: GetCompliancePolicy :one
SELECT id, name, description, enabled, mode, priority, applies_to_all,
       position_before, position_after, config_yaml, config,
       created_by, created_at, updated_at
FROM compliance_policies
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCompliancePolicy(ctx context.Context, id pgtype.UUID) (CompliancePolicy, error) {
	row := q.db.QueryRow(ctx, getCompliancePolicy, id)
	var i CompliancePolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Mode,
		&i.Priority,
		&i.AppliesToAll,
		&i.PositionBefore,
		&i.PositionAfter,
		&i.ConfigYaml,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertComplianceFramework = `-- name: InsertComplianceFramework :one
INSERT INTO compliance_frameworks (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at, updated_at
`

type InsertComplianceFrameworkParams struct {
	Name        string
	Description string
	CreatedBy   string
}

func (q *Queries) InsertComplianceFramework(ctx context.Context, arg InsertComplianceFrameworkParams) (ComplianceFramework, error) {
	row := q.db.QueryRow(ctx, insertComplianceFramework, arg.Name, arg.Description, arg.CreatedBy)
	var i ComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCompliancePolicy = `-- name: InsertCompliancePolicy :one
INSERT INTO compliance_policies
  (name, description, enabled, mode, priority, applies_to_all,
   position_before, position_after, config_yaml, config, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, description, enabled, mode, priority, applies_to_all,
          position_before, position_after, created_by, created_at, updated_at
`

type InsertCompliancePolicyParams struct {
	Name           string
	Description    string
	Enabled        bool
	Mode           string
	Priority       int32
	AppliesToAll   bool
	PositionBefore string
	PositionAfter  string
	ConfigYaml     string
	Config         []byte
	CreatedBy      string
}

type InsertCompliancePolicyRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Enabled        bool
	Mode           string
	Priority       int32
	AppliesToAll   bool
	PositionBefore string
	PositionAfter  string
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertCompliancePolicy(ctx context.Context, arg InsertCompliancePolicyParams) (InsertCompliancePolicyRow, error) {
	row := q.db.QueryRow(ctx, insertCompliancePolicy,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Mode,
		arg.Priority,
		arg.AppliesToAll,
		arg.PositionBefore,
		arg.PositionAfter,
		arg.ConfigYaml,
		arg.Config,
		arg.CreatedBy,
	)
	var i InsertCompliancePolicyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Mode,
		&i.Priority,
		&i.AppliesToAll,
		&i.PositionBefore,
		&i.PositionAfter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPolicyFramework = `-- name: InsertPolicyFramework :exec
INSERT INTO policy_frameworks (policy_id, framework_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertPolicyFrameworkParams struct {
	PolicyID    pgtype.UUID
	FrameworkID pgtype.UUID
}

func (q *Queries) InsertPolicyFramework(ctx context.Context, arg InsertPolicyFrameworkParams) error {
	_, err := q.db.Exec(ctx, insertPolicyFramework, arg.PolicyID, arg.FrameworkID)
	return err
}

const insertProjectFramework = `-- name: InsertProjectFramework :exec
INSERT INTO project_frameworks (project_id, framework_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertProjectFrameworkParams struct {
	ProjectID   pgtype.UUID
	FrameworkID pgtype.UUID
}

func (q *Queries) InsertProjectFramework(ctx context.Context, arg InsertProjectFrameworkParams) error {
	_, err := q.db.Exec(ctx, insertProjectFramework, arg.ProjectID, arg.FrameworkID)
	return err
}

const listAllProjectIDs = `-- name: ListAllProjectIDs :many
SELECT id FROM projects
`

func (q *Queries) ListAllProjectIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllProjectIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplianceFrameworks = `-- name: ListComplianceFrameworks :many

SELECT id, name, description, created_by, created_at, updated_at
FROM compliance_frameworks
ORDER BY name
`

// Compliance frameworks: admin-defined labels assigned to projects.
func (q *Queries) ListComplianceFrameworks(ctx context.Context) ([]ComplianceFramework, error) {
	rows, err := q.db.Query(ctx, listComplianceFrameworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceFramework{}
	for rows.Next() {
		var i ComplianceFramework
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompliancePolicies = `-- name: ListCompliancePolicies :many

SELECT id, name, description, enabled, mode, priority, applies_to_all,
       position_before, position_after, created_by, created_at, updated_at
FROM compliance_policies
ORDER BY priority, name
`

type ListCompliancePoliciesRow struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Enabled        bool
	Mode           string
	Priority       int32
	AppliesToAll   bool
	PositionBefore string
	PositionAfter  string
	CreatedBy      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Compliance policies.
// Admin list: metadata only (the compiled config + source YAML are fetched
// per-policy on Get).
func (q *Queries) ListCompliancePolicies(ctx context.Context) ([]ListCompliancePoliciesRow, error) {
	rows, err := q.db.Query(ctx, listCompliancePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompliancePoliciesRow{}
	for rows.Next() {
		var i ListCompliancePoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.Mode,
			&i.Priority,
			&i.AppliesToAll,
			&i.PositionBefore,
			&i.PositionAfter,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworkIDsByPolicy = `-- name: ListFrameworkIDsByPolicy :many
SELECT framework_id FROM policy_frameworks WHERE policy_id = $1
`

func (q *Queries) ListFrameworkIDsByPolicy(ctx context.Context, policyID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFrameworkIDsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var framework_id pgtype.UUID
		if err := rows.Scan(&framework_id); err != nil {
			return nil, err
		}
		items = append(items, framework_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworksByProject = `-- name: ListFrameworksByProject :many

SELECT f.id, f.name, f.description, f.created_by, f.created_at, f.updated_at
FROM compliance_frameworks f
JOIN project_frameworks pf ON pf.framework_id = f.id
WHERE pf.project_id = $1
ORDER BY f.name
`

// Project ↔ framework assignment.
func (q *Queries) ListFrameworksByProject(ctx context.Context, projectID pgtype.UUID) ([]ComplianceFramework, error) {
	rows, err := q.db.Query(ctx, listFrameworksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceFramework{}
	for rows.Next() {
		var i ComplianceFramework
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineKindsByProject = `-- name: ListPipelineKindsByProject :many
SELECT id, name, system_managed FROM pipelines WHERE project_id = $1 ORDER BY name
`

type ListPipelineKindsByProjectRow struct {
	ID            pgtype.UUID
	Name          string
	SystemManaged bool
}

// Governance reconciliation: each pipeline's id/name plus whether it is the
// server-owned synthetic pipeline (system_managed). Repo pipelines are those
// with system_managed = false. Ordered by name so the apply path's
// PipelinesRemoved list stays deterministic.
func (q *Queries) ListPipelineKindsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListPipelineKindsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listPipelineKindsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPipelineKindsByProjectRow{}
	for rows.Next() {
		var i ListPipelineKindsByProjectRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SystemManaged); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineRawByProject = `-- name: ListPipelineRawByProject :many
SELECT id, definition_raw FROM pipelines WHERE project_id = $1
`

type ListPipelineRawByProjectRow struct {
	ID            pgtype.UUID
	DefinitionRaw []byte
}

// Recompute support: the stored raw (pre-policy) definitions for a project,
// re-merged with current policies to refresh the effective definition.
func (q *Queries) ListPipelineRawByProject(ctx context.Context, projectID pgtype.UUID) ([]ListPipelineRawByProjectRow, error) {
	rows, err := q.db.Query(ctx, listPipelineRawByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPipelineRawByProjectRow{}
	for rows.Next() {
		var i ListPipelineRawByProjectRow
		if err := rows.Scan(&i.ID, &i.DefinitionRaw); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyConfigsExcept = `-- name: ListPolicyConfigsExcept :many
SELECT id, name, config FROM compliance_policies WHERE id <> $1
`

type ListPolicyConfigsExceptRow struct {
	ID     pgtype.UUID
	Name   string
	Config []byte
}

// Used at create/update to detect job/stage name collisions across policies
// (two policies must not both own `_compliance_scan` — they would produce
// duplicate job_runs). Pass uuid.Nil on create to compare against all.
func (q *Queries) ListPolicyConfigsExcept(ctx context.Context, id pgtype.UUID) ([]ListPolicyConfigsExceptRow, error) {
	rows, err := q.db.Query(ctx, listPolicyConfigsExcept, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPolicyConfigsExceptRow{}
	for rows.Next() {
		var i ListPolicyConfigsExceptRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIDsByFrameworks = `-- name: ListProjectIDsByFrameworks :many
SELECT DISTINCT project_id
FROM project_frameworks
WHERE framework_id = ANY($1::uuid[])
`

// Recompute fan-out: every project carrying any of the given frameworks.
func (q *Queries) ListProjectIDsByFrameworks(ctx context.Context, dollar_1 []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProjectIDsByFrameworks, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var project_id pgtype.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePoliciesForProject = `-- name: ResolvePoliciesForProject :many
SELECT DISTINCT p.id, p.name, p.mode, p.priority,
       p.position_before, p.position_after, p.config
FROM compliance_policies p
WHERE p.enabled = TRUE
  AND (
    p.applies_to_all = TRUE
    OR EXISTS (
      SELECT 1
      FROM policy_frameworks pf
      JOIN project_frameworks prf ON prf.framework_id = pf.framework_id
      WHERE pf.policy_id = p.id AND prf.project_id = $1
    )
  )
ORDER BY p.priority, p.name
`

type ResolvePoliciesForProjectRow struct {
	ID             pgtype.UUID
	Name           string
	Mode           string
	Priority       int32
	PositionBefore string
	PositionAfter  string
	Config         []byte
}

// The apply-time hot path: every enabled policy that applies to a project —
// global (applies_to_all) or targeting a framework the project carries —
// with its compiled config + merge metadata, ordered deterministically.
func (q *Queries) ResolvePoliciesForProject(ctx context.Context, projectID pgtype.UUID) ([]ResolvePoliciesForProjectRow, error) {
	rows, err := q.db.Query(ctx, resolvePoliciesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolvePoliciesForProjectRow{}
	for rows.Next() {
		var i ResolvePoliciesForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.Priority,
			&i.PositionBefore,
			&i.PositionAfter,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComplianceFramework = `-- name: UpdateComplianceFramework :execrows
UPDATE compliance_frameworks
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateComplianceFrameworkParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateComplianceFramework(ctx context.Context, arg UpdateComplianceFrameworkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateComplianceFramework, arg.ID, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCompliancePolicy = `-- name: UpdateCompliancePolicy :execrows
UPDATE compliance_policies
SET name = $2, description = $3, enabled = $4, mode = $5, priority = $6,
    applies_to_all = $7, position_before = $8, position_after = $9,
    config_yaml = $10, config = $11, updated_at = NOW()
WHERE id = $1
`

type UpdateCompliancePolicyParams struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	Enabled        bool
	Mode           string
	Priority       int32
	AppliesToAll   bool
	PositionBefore string
	PositionAfter  string
	ConfigYaml     string
	Config         []byte
}

func (q *Queries) UpdateCompliancePolicy(ctx context.Context, arg UpdateCompliancePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompliancePolicy,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Mode,
		arg.Priority,
		arg.AppliesToAll,
		arg.PositionBefore,
		arg.PositionAfter,
		arg.ConfigYaml,
		arg.Config,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePipelineEffectiveDefinition = `-- name: UpdatePipelineEffectiveDefinition :execrows
UPDATE pipelines
SET definition = $2,
    definition_version = CASE
        WHEN definition = $2 THEN definition_version
        ELSE definition_version + 1
    END,
    updated_at = CASE WHEN definition = $2 THEN updated_at ELSE NOW() END
WHERE id = $1
`

type UpdatePipelineEffectiveDefinitionParams struct {
	ID         pgtype.UUID
	Definition []byte
}

func (q *Queries) UpdatePipelineEffectiveDefinition(ctx context.Context, arg UpdatePipelineEffectiveDefinitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePipelineEffectiveDefinition, arg.ID, arg.Definition)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
