// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertSecurityFindings implements pgx.CopyFromSource.
type iteratorForInsertSecurityFindings struct {
	rows                 []InsertSecurityFindingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSecurityFindings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSecurityFindings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].JobRunID,
		r.rows[0].RunID,
		r.rows[0].PipelineID,
		r.rows[0].ProjectID,
		r.rows[0].JobName,
		r.rows[0].MatrixKey,
		r.rows[0].ArtifactID,
		r.rows[0].ArtifactPath,
		r.rows[0].Tool,
		r.rows[0].RuleID,
		r.rows[0].Severity,
		r.rows[0].Level,
		r.rows[0].Message,
		r.rows[0].LocationPath,
		r.rows[0].LocationLine,
		r.rows[0].LocationUrl,
		r.rows[0].Fingerprint,
	}, nil
}

func (r iteratorForInsertSecurityFindings) Err() error {
	return nil
}

func (q *Queries) InsertSecurityFindings(ctx context.Context, arg []InsertSecurityFindingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"security_findings"}, []string{"job_run_id", "run_id", "pipeline_id", "project_id", "job_name", "matrix_key", "artifact_id", "artifact_path", "tool", "rule_id", "severity", "level", "message", "location_path", "location_line", "location_url", "fingerprint"}, &iteratorForInsertSecurityFindings{rows: arg})
}
