// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cron.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCronMaterials = `-- name: ListCronMaterials :many
SELECT m.id, m.pipeline_id, pl.project_id, m.config,
       cs.last_fired_at
FROM materials m
JOIN pipelines pl ON pl.id = m.pipeline_id
LEFT JOIN cron_state cs ON cs.material_id = m.id
WHERE m.type = 'cron'
ORDER BY m.id
`

type ListCronMaterialsRow struct {
	ID          pgtype.UUID
	PipelineID  pgtype.UUID
	ProjectID   pgtype.UUID
	Config      []byte
	LastFiredAt pgtype.Timestamptz
}

// Loads every cron material in the system alongside its pipeline
// / project id and its last-fired timestamp (NULL when never
// fired). The ticker walks this list on every tick; N is bounded
// by `pipelines × cron_materials_per_pipeline`, typically a few
// dozen at most, so scanning in-process is fine.
func (q *Queries) ListCronMaterials(ctx context.Context) ([]ListCronMaterialsRow, error) {
	rows, err := q.db.Query(ctx, listCronMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCronMaterialsRow{}
	for rows.Next() {
		var i ListCronMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.ProjectID,
			&i.Config,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCronFired = `-- name: UpsertCronFired :exec
INSERT INTO cron_state (material_id, last_fired_at)
VALUES ($1, $2)
ON CONFLICT (material_id) DO UPDATE SET
    last_fired_at = EXCLUDED.last_fired_at,
    updated_at    = NOW()
`

type UpsertCronFiredParams struct {
	MaterialID  pgtype.UUID
	LastFiredAt pgtype.Timestamptz
}

// Records a fire time for a cron material. The ticker calls this
// right after dispatching a run so a crashed server doesn't re-
// fire the same tick when it comes back.
func (q *Queries) UpsertCronFired(ctx context.Context, arg UpsertCronFiredParams) error {
	_, err := q.db.Exec(ctx, upsertCronFired, arg.MaterialID, arg.LastFiredAt)
	return err
}
