// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deploy_watches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const armRolloutGate = `-- name: ArmRolloutGate :execrows
UPDATE deploy_watches
SET gate_id                = gen_random_uuid(),
    gate_armed_at          = NOW(),
    gate_paused_step       = $1,
    gate_rollout_cluster   = $2,
    gate_rollout_namespace = $3,
    gate_rollout_name      = $4
WHERE deployment_revision_id = $5
  AND claim_id = $6
  -- Idempotent re-arm guard. The COMPLETE-pin invariant is enforced at the store edge
  -- (ArmRolloutGate rejects an empty cluster/namespace/name before this runs).
  AND gate_id IS NULL
`

type ArmRolloutGateParams struct {
	GatePausedStep       *int32
	GateRolloutCluster   *string
	GateRolloutNamespace *string
	GateRolloutName      *string
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Arm the approval gate for the current indefinite pause. Stamps a FRESH gate_id (the
// anti-stale token), the armed-at time, the paused step, and the RESOLVED Rollout
// identity PINNED for this gate — Promote/Abort act on these, never a re-discovery, so
// `.status.resources[]` drift can't redirect the effect. All three identity columns are
// stamped together (a complete pinned tuple; the watcher only arms with all three).
// Fenced on claim_id; `gate_id IS NULL` makes a double-tick a no-op (never re-arms a
// fresh token under an in-flight vote).
func (q *Queries) ArmRolloutGate(ctx context.Context, arg ArmRolloutGateParams) (int64, error) {
	result, err := q.db.Exec(ctx, armRolloutGate,
		arg.GatePausedStep,
		arg.GateRolloutCluster,
		arg.GateRolloutNamespace,
		arg.GateRolloutName,
		arg.DeploymentRevisionID,
		arg.ClaimID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDeployWatches = `-- name: ClaimDeployWatches :many
UPDATE deploy_watches w
SET claim_id = gen_random_uuid(), claimed_by = $1, claimed_at = NOW()
WHERE w.deployment_revision_id IN (
    SELECT dw.deployment_revision_id
    FROM deploy_watches dw
    JOIN deployment_revisions dr ON dr.id = dw.deployment_revision_id
    WHERE dr.status = 'in_progress'
      AND (dw.claimed_at IS NULL
           OR dw.claimed_at < NOW() - make_interval(secs => $2::int))
    ORDER BY dw.claimed_at NULLS FIRST, dw.created_at
    FOR UPDATE OF dw SKIP LOCKED
    LIMIT $3
)
RETURNING deployment_revision_id, project_id, sync_mode, cluster, application, namespace, expected_revision, watch_started_at, sync_requested_at, deadline_at, degraded_since, claim_id, claimed_by, claimed_at, created_at, rollout_aware, rollout_cluster, rollout_namespace, rollout_name, rollout_phase, rollout_message, rollout_pause_reason, rollout_current_step, rollout_step_count, rollout_aborted, rollout_error, rollout_observed_at, gate_approvers, gate_approver_groups, gate_required, gate_description, gate_id, gate_armed_at, gate_paused_step, gate_rollout_cluster, gate_rollout_namespace, gate_rollout_name, gate_decision, gate_decided_by, gate_decided_at, gate_actioned_at, rollout_abort_actioned_at
`

type ClaimDeployWatchesParams struct {
	ClaimedBy    *string
	LeaseSeconds int32
	MaxBatch     int32
}

// Atomically claim a batch of claimable watches — never claimed, or lease-expired
// (the prior watcher crashed) — assigning each a fresh fencing token. The join to
// deployment_revisions filters to still-in_progress deploys: a backstop, since the
// terminalizers (FinalizeDeploymentRevision / FinalizeDeployWatch) already delete the
// watch — so a terminal-revision watch never reaches a watcher even if one lingered.
// FOR UPDATE OF ... SKIP
// LOCKED lets replicas claim disjoint batches without contending. Each row gets its
// OWN claim_id (gen_random_uuid is volatile, evaluated per row).
func (q *Queries) ClaimDeployWatches(ctx context.Context, arg ClaimDeployWatchesParams) ([]DeployWatch, error) {
	rows, err := q.db.Query(ctx, claimDeployWatches, arg.ClaimedBy, arg.LeaseSeconds, arg.MaxBatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployWatch{}
	for rows.Next() {
		var i DeployWatch
		if err := rows.Scan(
			&i.DeploymentRevisionID,
			&i.ProjectID,
			&i.SyncMode,
			&i.Cluster,
			&i.Application,
			&i.Namespace,
			&i.ExpectedRevision,
			&i.WatchStartedAt,
			&i.SyncRequestedAt,
			&i.DeadlineAt,
			&i.DegradedSince,
			&i.ClaimID,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.RolloutAware,
			&i.RolloutCluster,
			&i.RolloutNamespace,
			&i.RolloutName,
			&i.RolloutPhase,
			&i.RolloutMessage,
			&i.RolloutPauseReason,
			&i.RolloutCurrentStep,
			&i.RolloutStepCount,
			&i.RolloutAborted,
			&i.RolloutError,
			&i.RolloutObservedAt,
			&i.GateApprovers,
			&i.GateApproverGroups,
			&i.GateRequired,
			&i.GateDescription,
			&i.GateID,
			&i.GateArmedAt,
			&i.GatePausedStep,
			&i.GateRolloutCluster,
			&i.GateRolloutNamespace,
			&i.GateRolloutName,
			&i.GateDecision,
			&i.GateDecidedBy,
			&i.GateDecidedAt,
			&i.GateActionedAt,
			&i.RolloutAbortActionedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearDeployWatchDegraded = `-- name: ClearDeployWatchDegraded :execrows
UPDATE deploy_watches
SET degraded_since = NULL
WHERE deployment_revision_id = $1 AND claim_id = $2
`

type ClearDeployWatchDegradedParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Health recovered before the debounce elapsed: reset the anchor. Fenced on claim_id.
func (q *Queries) ClearDeployWatchDegraded(ctx context.Context, arg ClearDeployWatchDegradedParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearDeployWatchDegraded, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearRolloutGateColumns = `-- name: ClearRolloutGateColumns :execrows
UPDATE deploy_watches
SET deadline_at = CASE
        WHEN gate_armed_at IS NOT NULL AND gate_decision IS NULL
        THEN deadline_at + (NOW() - gate_armed_at)
        ELSE deadline_at
    END,
    gate_id                = NULL,
    gate_armed_at          = NULL,
    gate_paused_step       = NULL,
    gate_rollout_cluster   = NULL,
    gate_rollout_namespace = NULL,
    gate_rollout_name      = NULL,
    gate_decision          = NULL,
    gate_decided_by        = NULL,
    gate_decided_at        = NULL,
    gate_actioned_at       = NULL
WHERE deployment_revision_id = $1
  AND claim_id = $2
  -- Only a REAL armed round is clearable — a spurious ClearGate on an unarmed watch
  -- must not "succeed" (and then delete this deploy's votes). gate_id is stamped by
  -- ArmRolloutGate and nulled here, so it marks exactly an armed round.
  AND gate_id IS NOT NULL
`

type ClearRolloutGateColumnsParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Disarm the current step's gate: null the per-arm / decision / action columns. The
// CONFIG columns (gate_approvers/required/description) persist for the whole deploy, so
// the next pause re-arms with the same policy. If cleared while STILL UNDECIDED (an
// external promote before any vote), resume the deadline with the one-time shift
// deadline_at += NOW() - gate_armed_at. The CASE reads the OLD row values (an UPDATE's
// SET RHS all see the pre-update row), so it computes the shift before nulling. Guarded
// so it's applied at most once — a DECIDED gate already had its deadline resumed by
// DecideRolloutGate. Fenced on claim_id.
func (q *Queries) ClearRolloutGateColumns(ctx context.Context, arg ClearRolloutGateColumnsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRolloutGateColumns, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveWatchesForCluster = `-- name: CountActiveWatchesForCluster :one
SELECT COUNT(*) FROM deploy_watches WHERE cluster = $1 OR rollout_cluster = $1
`

// Backs the cluster delete-guard: an in-flight watch referencing the cluster (as its
// Application cluster OR its Rollout cluster) RESTRICTs it (both FKs); this gives the
// friendly message before the DELETE fails.
func (q *Queries) CountActiveWatchesForCluster(ctx context.Context, cluster string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWatchesForCluster, cluster)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployWatch = `-- name: CreateDeployWatch :one
INSERT INTO deploy_watches (
    deployment_revision_id, project_id, sync_mode, cluster, application,
    namespace, expected_revision, deadline_at,
    rollout_aware, rollout_cluster, rollout_namespace, rollout_name,
    gate_approvers, gate_approver_groups, gate_required, gate_description
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
       $13, $14,
       $15, $16
WHERE EXISTS (
    SELECT 1 FROM deployment_revisions WHERE id = $1 AND status = 'in_progress'
)
RETURNING deployment_revision_id, project_id, sync_mode, cluster, application, namespace, expected_revision, watch_started_at, sync_requested_at, deadline_at, degraded_since, claim_id, claimed_by, claimed_at, created_at, rollout_aware, rollout_cluster, rollout_namespace, rollout_name, rollout_phase, rollout_message, rollout_pause_reason, rollout_current_step, rollout_step_count, rollout_aborted, rollout_error, rollout_observed_at, gate_approvers, gate_approver_groups, gate_required, gate_description, gate_id, gate_armed_at, gate_paused_step, gate_rollout_cluster, gate_rollout_namespace, gate_rollout_name, gate_decision, gate_decided_by, gate_decided_at, gate_actioned_at, rollout_abort_actioned_at
`

type CreateDeployWatchParams struct {
	DeploymentRevisionID pgtype.UUID
	ProjectID            pgtype.UUID
	SyncMode             string
	Cluster              string
	Application          string
	Namespace            string
	ExpectedRevision     string
	DeadlineAt           pgtype.Timestamptz
	RolloutAware         bool
	RolloutCluster       *string
	RolloutNamespace     *string
	RolloutName          *string
	GateApprovers        []string
	GateApproverGroups   []string
	GateRequired         *int32
	GateDescription      *string
}

// Create the control-loop record for a freshly-created in_progress deployment
// revision. Unclaimed (claim_* NULL) and sync_requested_at NULL: the row exists
// BEFORE Sync fires so a crash between create and Sync is recoverable. The
// WHERE EXISTS guard refuses to watch an already-terminal revision (a late or
// duplicate create) — 0 rows → the store maps it to ErrRevisionNotInProgress.
// The gate_* CONFIG columns are the target's governing_gate denormalized here at
// creation (an immutable per-deploy snapshot; a mid-flight target edit must not change
// an in-flight deploy's gate). gate_required NULL => this deploy is not gated. The
// per-arm / decision / action gate columns stay NULL until the watcher arms a step.
func (q *Queries) CreateDeployWatch(ctx context.Context, arg CreateDeployWatchParams) (DeployWatch, error) {
	row := q.db.QueryRow(ctx, createDeployWatch,
		arg.DeploymentRevisionID,
		arg.ProjectID,
		arg.SyncMode,
		arg.Cluster,
		arg.Application,
		arg.Namespace,
		arg.ExpectedRevision,
		arg.DeadlineAt,
		arg.RolloutAware,
		arg.RolloutCluster,
		arg.RolloutNamespace,
		arg.RolloutName,
		arg.GateApprovers,
		arg.GateApproverGroups,
		arg.GateRequired,
		arg.GateDescription,
	)
	var i DeployWatch
	err := row.Scan(
		&i.DeploymentRevisionID,
		&i.ProjectID,
		&i.SyncMode,
		&i.Cluster,
		&i.Application,
		&i.Namespace,
		&i.ExpectedRevision,
		&i.WatchStartedAt,
		&i.SyncRequestedAt,
		&i.DeadlineAt,
		&i.DegradedSince,
		&i.ClaimID,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.RolloutAware,
		&i.RolloutCluster,
		&i.RolloutNamespace,
		&i.RolloutName,
		&i.RolloutPhase,
		&i.RolloutMessage,
		&i.RolloutPauseReason,
		&i.RolloutCurrentStep,
		&i.RolloutStepCount,
		&i.RolloutAborted,
		&i.RolloutError,
		&i.RolloutObservedAt,
		&i.GateApprovers,
		&i.GateApproverGroups,
		&i.GateRequired,
		&i.GateDescription,
		&i.GateID,
		&i.GateArmedAt,
		&i.GatePausedStep,
		&i.GateRolloutCluster,
		&i.GateRolloutNamespace,
		&i.GateRolloutName,
		&i.GateDecision,
		&i.GateDecidedBy,
		&i.GateDecidedAt,
		&i.GateActionedAt,
		&i.RolloutAbortActionedAt,
	)
	return i, err
}

const deleteDeployGateVotes = `-- name: DeleteDeployGateVotes :exec
DELETE FROM job_run_approvals
WHERE job_run_id = (
    SELECT job_run_id FROM deployment_revisions WHERE id = $1
)
`

// Delete the current arm's approval votes so the next step's gate starts fresh. Votes
// reuse job_run_approvals keyed on the deploy's job_run_id; each canary step is its own
// round, so a step's votes must not carry into the next. The durable per-decision record
// is the audit event emitted by DecideRolloutGate, not these transient rows.
func (q *Queries) DeleteDeployGateVotes(ctx context.Context, deploymentRevisionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeployGateVotes, deploymentRevisionID)
	return err
}

const deleteDeployWatchClaimed = `-- name: DeleteDeployWatchClaimed :execrows
DELETE FROM deploy_watches
WHERE deployment_revision_id = $1 AND claim_id = $2
`

type DeleteDeployWatchClaimedParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Fenced delete used by the atomic terminal tx: 0 rows means the lease was lost, so
// the caller MUST NOT terminalize the deploy (fencing guarantee).
func (q *Queries) DeleteDeployWatchClaimed(ctx context.Context, arg DeleteDeployWatchClaimedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeployWatchClaimed, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeployWatch = `-- name: GetDeployWatch :one
SELECT deployment_revision_id, project_id, sync_mode, cluster, application, namespace, expected_revision, watch_started_at, sync_requested_at, deadline_at, degraded_since, claim_id, claimed_by, claimed_at, created_at, rollout_aware, rollout_cluster, rollout_namespace, rollout_name, rollout_phase, rollout_message, rollout_pause_reason, rollout_current_step, rollout_step_count, rollout_aborted, rollout_error, rollout_observed_at, gate_approvers, gate_approver_groups, gate_required, gate_description, gate_id, gate_armed_at, gate_paused_step, gate_rollout_cluster, gate_rollout_namespace, gate_rollout_name, gate_decision, gate_decided_by, gate_decided_at, gate_actioned_at, rollout_abort_actioned_at FROM deploy_watches WHERE deployment_revision_id = $1
`

func (q *Queries) GetDeployWatch(ctx context.Context, deploymentRevisionID pgtype.UUID) (DeployWatch, error) {
	row := q.db.QueryRow(ctx, getDeployWatch, deploymentRevisionID)
	var i DeployWatch
	err := row.Scan(
		&i.DeploymentRevisionID,
		&i.ProjectID,
		&i.SyncMode,
		&i.Cluster,
		&i.Application,
		&i.Namespace,
		&i.ExpectedRevision,
		&i.WatchStartedAt,
		&i.SyncRequestedAt,
		&i.DeadlineAt,
		&i.DegradedSince,
		&i.ClaimID,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.RolloutAware,
		&i.RolloutCluster,
		&i.RolloutNamespace,
		&i.RolloutName,
		&i.RolloutPhase,
		&i.RolloutMessage,
		&i.RolloutPauseReason,
		&i.RolloutCurrentStep,
		&i.RolloutStepCount,
		&i.RolloutAborted,
		&i.RolloutError,
		&i.RolloutObservedAt,
		&i.GateApprovers,
		&i.GateApproverGroups,
		&i.GateRequired,
		&i.GateDescription,
		&i.GateID,
		&i.GateArmedAt,
		&i.GatePausedStep,
		&i.GateRolloutCluster,
		&i.GateRolloutNamespace,
		&i.GateRolloutName,
		&i.GateDecision,
		&i.GateDecidedBy,
		&i.GateDecidedAt,
		&i.GateActionedAt,
		&i.RolloutAbortActionedAt,
	)
	return i, err
}

const listDeployWatchesForProject = `-- name: ListDeployWatchesForProject :many
SELECT dw.deployment_revision_id, e.name AS environment, dr.version,
       dw.expected_revision, dw.sync_mode,
       dw.cluster, dw.application, dw.watch_started_at, dw.sync_requested_at,
       dw.deadline_at, dw.degraded_since,
       dw.rollout_aware, dw.rollout_phase, dw.rollout_message, dw.rollout_pause_reason,
       dw.rollout_current_step, dw.rollout_step_count, dw.rollout_aborted,
       dw.rollout_error, dw.rollout_observed_at
FROM deploy_watches dw
JOIN deployment_revisions dr ON dr.id = dw.deployment_revision_id
JOIN environments e ON e.id = dr.environment_id
WHERE dw.project_id = $1
ORDER BY e.name
`

type ListDeployWatchesForProjectRow struct {
	DeploymentRevisionID pgtype.UUID
	Environment          string
	Version              string
	ExpectedRevision     string
	SyncMode             string
	Cluster              string
	Application          string
	WatchStartedAt       pgtype.Timestamptz
	SyncRequestedAt      pgtype.Timestamptz
	DeadlineAt           pgtype.Timestamptz
	DegradedSince        pgtype.Timestamptz
	RolloutAware         bool
	RolloutPhase         *string
	RolloutMessage       *string
	RolloutPauseReason   *string
	RolloutCurrentStep   *int32
	RolloutStepCount     *int32
	RolloutAborted       *bool
	RolloutError         *string
	RolloutObservedAt    pgtype.Timestamptz
}

// In-flight native deploys for a project (one row per still-in_progress revision),
// joined to the environment name + display version for the UI live-status endpoint.
// Config fields (cluster/application/sync_mode) are returned here but sanitised by
// role at the HTTP layer — viewers never see them.
func (q *Queries) ListDeployWatchesForProject(ctx context.Context, projectID pgtype.UUID) ([]ListDeployWatchesForProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeployWatchesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployWatchesForProjectRow{}
	for rows.Next() {
		var i ListDeployWatchesForProjectRow
		if err := rows.Scan(
			&i.DeploymentRevisionID,
			&i.Environment,
			&i.Version,
			&i.ExpectedRevision,
			&i.SyncMode,
			&i.Cluster,
			&i.Application,
			&i.WatchStartedAt,
			&i.SyncRequestedAt,
			&i.DeadlineAt,
			&i.DegradedSince,
			&i.RolloutAware,
			&i.RolloutPhase,
			&i.RolloutMessage,
			&i.RolloutPauseReason,
			&i.RolloutCurrentStep,
			&i.RolloutStepCount,
			&i.RolloutAborted,
			&i.RolloutError,
			&i.RolloutObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeployWatchSyncRequested = `-- name: MarkDeployWatchSyncRequested :execrows
UPDATE deploy_watches
SET sync_requested_at = NOW()
WHERE deployment_revision_id = $1 AND claim_id = $2
`

type MarkDeployWatchSyncRequestedParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Stamp the correlation anchor right after Sync fires. Fenced on claim_id.
func (q *Queries) MarkDeployWatchSyncRequested(ctx context.Context, arg MarkDeployWatchSyncRequestedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeployWatchSyncRequested, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markGateActioned = `-- name: MarkGateActioned :execrows
UPDATE deploy_watches
SET gate_actioned_at = NOW()
WHERE deployment_revision_id = $1
  AND claim_id = $2
  AND gate_actioned_at IS NULL
`

type MarkGateActionedParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Record that the gated Promote/Abort was ISSUED for this decision (anti-retry only —
// no deadline change; the terminal DECISION already resumed the deadline). Fenced on
// claim_id; `gate_actioned_at IS NULL` makes a re-tick a no-op.
func (q *Queries) MarkGateActioned(ctx context.Context, arg MarkGateActionedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markGateActioned, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewDeployWatch = `-- name: RenewDeployWatch :execrows
UPDATE deploy_watches
SET claimed_at = NOW()
WHERE deployment_revision_id = $1 AND claim_id = $2
`

type RenewDeployWatchParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Heartbeat: extend the lease. Fenced on claim_id — 0 rows means the lease was
// stolen (another replica reclaimed) and this watcher must drop the work.
func (q *Queries) RenewDeployWatch(ctx context.Context, arg RenewDeployWatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewDeployWatch, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDeployWatchDegradedSince = `-- name: SetDeployWatchDegradedSince :execrows
UPDATE deploy_watches
SET degraded_since = COALESCE(degraded_since, NOW())
WHERE deployment_revision_id = $1 AND claim_id = $2
`

type SetDeployWatchDegradedSinceParams struct {
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Open the debounce window on the first Degraded tick (COALESCE keeps the earliest).
// Fenced on claim_id.
func (q *Queries) SetDeployWatchDegradedSince(ctx context.Context, arg SetDeployWatchDegradedSinceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDeployWatchDegradedSince, arg.DeploymentRevisionID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampDeployWatchSyncRequested = `-- name: StampDeployWatchSyncRequested :execrows
UPDATE deploy_watches
SET sync_requested_at = NOW()
WHERE deployment_revision_id = $1 AND sync_requested_at IS NULL
`

// UNFENCED stamp of the correlation anchor at dispatch, before any watcher has
// claimed the watch (so the fenced MarkDeployWatchSyncRequested can't be used yet).
// Monotonic: `WHERE sync_requested_at IS NULL` — a later dispatch/retry never reopens
// the anchor. 0 rows → already stamped or gone; the caller logs and continues.
func (q *Queries) StampDeployWatchSyncRequested(ctx context.Context, deploymentRevisionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, stampDeployWatchSyncRequested, deploymentRevisionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampRolloutObservation = `-- name: StampRolloutObservation :execrows
UPDATE deploy_watches
SET rollout_phase        = $1,
    rollout_message      = $2,
    rollout_pause_reason = $3,
    rollout_current_step = $4,
    rollout_step_count   = $5,
    rollout_aborted      = $6,
    rollout_error        = $7,
    rollout_observed_at  = NOW()
WHERE deployment_revision_id = $8
  AND claim_id = $9
`

type StampRolloutObservationParams struct {
	RolloutPhase         *string
	RolloutMessage       *string
	RolloutPauseReason   *string
	RolloutCurrentStep   *int32
	RolloutStepCount     *int32
	RolloutAborted       *bool
	RolloutError         *string
	DeploymentRevisionID pgtype.UUID
	ClaimID              pgtype.UUID
}

// Persist the observed Rollout snapshot onto the watch each tick, so the UI (which
// reads the DB) can render canary progress. Fenced on claim_id — 0 rows means the
// lease was lost. rollout_current_step is NULL when the controller hasn't reported it
// (RolloutState.CurrentStepKnown=false). Clears rollout_error on a successful observe.
func (q *Queries) StampRolloutObservation(ctx context.Context, arg StampRolloutObservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, stampRolloutObservation,
		arg.RolloutPhase,
		arg.RolloutMessage,
		arg.RolloutPauseReason,
		arg.RolloutCurrentStep,
		arg.RolloutStepCount,
		arg.RolloutAborted,
		arg.RolloutError,
		arg.DeploymentRevisionID,
		arg.ClaimID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
