// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deployments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeploymentRevision = `-- name: CreateDeploymentRevision :one
INSERT INTO deployment_revisions
    (environment_id, run_id, job_run_id, attempt, version, is_rollback, deployed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateDeploymentRevisionParams struct {
	EnvironmentID pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	Attempt       int32
	Version       string
	IsRollback    bool
	DeployedBy    string
}

// Recorded at dispatch with the resolved version, status in_progress,
// tagged with the dispatch attempt so retries don't collide.
func (q *Queries) CreateDeploymentRevision(ctx context.Context, arg CreateDeploymentRevisionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDeploymentRevision,
		arg.EnvironmentID,
		arg.RunID,
		arg.JobRunID,
		arg.Attempt,
		arg.Version,
		arg.IsRollback,
		arg.DeployedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const currentDeploymentByEnvironment = `-- name: CurrentDeploymentByEnvironment :one
SELECT id, environment_id, run_id, job_run_id, attempt, version, status,
       is_rollback, deployed_by, created_at, finished_at
FROM deployment_revisions
WHERE environment_id = $1 AND status = 'success'
ORDER BY finished_at DESC
LIMIT 1
`

// "What's deployed now": newest successful revision. Served straight
// off idx_deployment_revisions_current.
func (q *Queries) CurrentDeploymentByEnvironment(ctx context.Context, environmentID pgtype.UUID) (DeploymentRevision, error) {
	row := q.db.QueryRow(ctx, currentDeploymentByEnvironment, environmentID)
	var i DeploymentRevision
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.RunID,
		&i.JobRunID,
		&i.Attempt,
		&i.Version,
		&i.Status,
		&i.IsRollback,
		&i.DeployedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteDeploymentRevision = `-- name: DeleteDeploymentRevision :exec
DELETE FROM deployment_revisions
WHERE id = $1 AND status = 'in_progress'
`

// Removes a revision created at dispatch when the dispatch then failed
// to reach an agent (the frame never went out, so no deploy happened).
// Scoped to in_progress so it can never erase a finalized audit row.
func (q *Queries) DeleteDeploymentRevision(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeploymentRevision, id)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :execrows
DELETE FROM environments WHERE project_id = $1 AND id = $2
`

type DeleteEnvironmentParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

// Hard-delete an environment scoped to its project. ON DELETE CASCADE on
// deploy_targets, deployment_revisions and analytics_deploy_daily fans the
// delete out — the environment's whole deploy history + any registered target
// (incl. a gated one) go with it, so the API gates this to admin. Returns rows
// affected (0 = absent or not in this project → 404). Environments are lazy, so
// a later deploy to the same name re-creates it empty.
func (q *Queries) DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironment, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const environmentBelongsToProject = `-- name: EnvironmentBelongsToProject :one
SELECT EXISTS (
    SELECT 1 FROM environments WHERE id = $2 AND project_id = $1
)
`

type EnvironmentBelongsToProjectParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

// Scope guard: confirm an environment id is owned by a project before
// serving its deployments through that project's URL.
func (q *Queries) EnvironmentBelongsToProject(ctx context.Context, arg EnvironmentBelongsToProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, environmentBelongsToProject, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const finalizeDeploymentRevision = `-- name: FinalizeDeploymentRevision :one
WITH finalized AS (
    UPDATE deployment_revisions
    SET status = $3, finished_at = NOW()
    WHERE job_run_id = $1 AND attempt = $2 AND status = 'in_progress'
    RETURNING id
), cleaned AS (
    DELETE FROM deploy_watches
    WHERE deployment_revision_id IN (SELECT id FROM finalized)
)
SELECT count(*) FROM finalized
`

type FinalizeDeploymentRevisionParams struct {
	JobRunID pgtype.UUID
	Attempt  int32
	Status   string
}

// Called on the job's terminal result (or by the reaper for a dead
// attempt): flips the in_progress revision of THIS (job_run, attempt)
// to success/failed and stamps finished_at. Keyed on attempt so a
// success on attempt 1 never finalises a stale attempt-0 row. Guarded
// on status='in_progress' so a re-delivered result is a no-op. Returns
// the count finalized (0 = the job had no deploy: block, or already final).
//
// The `cleaned` data-modifying CTE atomically removes any deploy_watch for the
// finalized revision: a native-provider deploy may be terminalized by THIS
// job/reaper path (not only by the watcher's own FinalizeDeployWatch), and a watch
// left behind would linger forever in the live-watch queue (never claimable — the
// claim scan filters status='in_progress') and falsely block deleting its cluster.
func (q *Queries) FinalizeDeploymentRevision(ctx context.Context, arg FinalizeDeploymentRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, finalizeDeploymentRevision, arg.JobRunID, arg.Attempt, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalizeDeploymentRevisionByID = `-- name: FinalizeDeploymentRevisionByID :one
UPDATE deployment_revisions
SET status = $2, finished_at = NOW()
WHERE id = $1 AND status = 'in_progress'
RETURNING job_run_id, attempt
`

type FinalizeDeploymentRevisionByIDParams struct {
	ID     pgtype.UUID
	Status string
}

type FinalizeDeploymentRevisionByIDRow struct {
	JobRunID pgtype.UUID
	Attempt  int32
}

// Terminalize a specific revision by id (the deploy watcher's convergence verdict)
// and return its job link so the SAME tx can complete the server-managed deploy
// job_run (ADR-0001, Model A). Guarded on status='in_progress' so a re-delivered
// finalize is a no-op (ErrNoRows). The watcher's FinalizeDeployWatch deletes the
// deploy_watch (fenced) in the same tx before calling this.
func (q *Queries) FinalizeDeploymentRevisionByID(ctx context.Context, arg FinalizeDeploymentRevisionByIDParams) (FinalizeDeploymentRevisionByIDRow, error) {
	row := q.db.QueryRow(ctx, finalizeDeploymentRevisionByID, arg.ID, arg.Status)
	var i FinalizeDeploymentRevisionByIDRow
	err := row.Scan(&i.JobRunID, &i.Attempt)
	return i, err
}

const getDeploymentRevision = `-- name: GetDeploymentRevision :one
SELECT id, environment_id, run_id, job_run_id, attempt, version, status,
       is_rollback, deployed_by, created_at, finished_at
FROM deployment_revisions
WHERE id = $1
`

func (q *Queries) GetDeploymentRevision(ctx context.Context, id pgtype.UUID) (DeploymentRevision, error) {
	row := q.db.QueryRow(ctx, getDeploymentRevision, id)
	var i DeploymentRevision
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.RunID,
		&i.JobRunID,
		&i.Attempt,
		&i.Version,
		&i.Status,
		&i.IsRollback,
		&i.DeployedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeploymentHistory = `-- name: ListDeploymentHistory :many
SELECT id, environment_id, run_id, job_run_id, attempt, version, status,
       is_rollback, deployed_by, created_at, finished_at
FROM deployment_revisions
WHERE environment_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDeploymentHistoryParams struct {
	EnvironmentID pgtype.UUID
	Limit         int32
}

// Timeline for one environment, all statuses, newest first.
func (q *Queries) ListDeploymentHistory(ctx context.Context, arg ListDeploymentHistoryParams) ([]DeploymentRevision, error) {
	rows, err := q.db.Query(ctx, listDeploymentHistory, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentRevision{}
	for rows.Next() {
		var i DeploymentRevision
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.RunID,
			&i.JobRunID,
			&i.Attempt,
			&i.Version,
			&i.Status,
			&i.IsRollback,
			&i.DeployedBy,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, description, created_at, updated_at
FROM environments
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsWithCurrentByProject = `-- name: ListEnvironmentsWithCurrentByProject :many
SELECT e.id, e.name, e.description, e.created_at, e.updated_at,
       c.id                           AS current_id,
       c.run_id                       AS current_run_id,
       COALESCE(c.attempt, 0)         AS current_attempt,
       COALESCE(c.version, '')        AS current_version,
       COALESCE(c.is_rollback, FALSE) AS current_is_rollback,
       COALESCE(c.deployed_by, '')    AS current_deployed_by,
       c.created_at                   AS current_created_at,
       c.finished_at                  AS current_finished_at
FROM environments e
LEFT JOIN LATERAL (
    SELECT id, run_id, attempt, version, is_rollback, deployed_by, created_at, finished_at
    FROM deployment_revisions
    WHERE environment_id = e.id AND status = 'success'
    ORDER BY finished_at DESC
    LIMIT 1
) c ON TRUE
WHERE e.project_id = $1
ORDER BY e.name
`

type ListEnvironmentsWithCurrentByProjectRow struct {
	ID                pgtype.UUID
	Name              string
	Description       string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	CurrentID         pgtype.UUID
	CurrentRunID      pgtype.UUID
	CurrentAttempt    int32
	CurrentVersion    string
	CurrentIsRollback bool
	CurrentDeployedBy string
	CurrentCreatedAt  pgtype.Timestamptz
	CurrentFinishedAt pgtype.Timestamptz
}

// One row per environment with its CURRENT deployment (newest
// successful revision) attached via LEFT JOIN LATERAL — environments
// with nothing deployed yet still appear, with NULL current_* columns.
// The LATERAL probe lands straight on idx_deployment_revisions_current
// (one index hit per environment), so this is the single query behind
// the Environments tab — no N+1.
// current_id is the has-a-deployment discriminator (NULL = nothing
// deployed yet). version/is_rollback/deployed_by are COALESCEd because
// the LEFT JOIN yields NULL for an undeployed env and their base
// columns are NOT NULL (sqlc would type them non-nullable and the
// scan would fail on NULL); the caller gates on current_id.Valid.
func (q *Queries) ListEnvironmentsWithCurrentByProject(ctx context.Context, projectID pgtype.UUID) ([]ListEnvironmentsWithCurrentByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsWithCurrentByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsWithCurrentByProjectRow{}
	for rows.Next() {
		var i ListEnvironmentsWithCurrentByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentID,
			&i.CurrentRunID,
			&i.CurrentAttempt,
			&i.CurrentVersion,
			&i.CurrentIsRollback,
			&i.CurrentDeployedBy,
			&i.CurrentCreatedAt,
			&i.CurrentFinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentDescription = `-- name: UpdateEnvironmentDescription :exec
UPDATE environments
SET description = $3, updated_at = NOW()
WHERE project_id = $1 AND id = $2
`

type UpdateEnvironmentDescriptionParams struct {
	ProjectID   pgtype.UUID
	ID          pgtype.UUID
	Description string
}

func (q *Queries) UpdateEnvironmentDescription(ctx context.Context, arg UpdateEnvironmentDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentDescription, arg.ProjectID, arg.ID, arg.Description)
	return err
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
INSERT INTO environments (project_id, name)
VALUES ($1, $2)
ON CONFLICT (project_id, name) DO UPDATE SET updated_at = NOW()
RETURNING id
`

type UpsertEnvironmentParams struct {
	ProjectID pgtype.UUID
	Name      string
}

// Lazy-create: the first dispatch of a job with deploy:{environment:X}
// inserts the row; later dispatches just bump updated_at. Returns the
// id so the dispatch path can attach a revision regardless of which
// side of the conflict it hit.
func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertEnvironment, arg.ProjectID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
