// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deploy_targets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDeployTargetsForCluster = `-- name: CountDeployTargetsForCluster :one
SELECT COUNT(*) FROM deploy_targets WHERE cluster = $1
`

// Backs the cluster delete-guard: a cluster referenced by any target can't be
// deleted (also enforced by the FK's ON DELETE RESTRICT, this gives the message).
func (q *Queries) CountDeployTargetsForCluster(ctx context.Context, cluster string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeployTargetsForCluster, cluster)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDeployTargetByEnvironment = `-- name: DeleteDeployTargetByEnvironment :execrows
DELETE FROM deploy_targets
WHERE environment_id = (
    SELECT id FROM environments WHERE project_id = $1 AND name = $2
)
`

type DeleteDeployTargetByEnvironmentParams struct {
	ProjectID pgtype.UUID
	Name      string
}

func (q *Queries) DeleteDeployTargetByEnvironment(ctx context.Context, arg DeleteDeployTargetByEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeployTargetByEnvironment, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeployTargetsForProject = `-- name: ListDeployTargetsForProject :many
SELECT dt.id, e.name AS environment, dt.provider, dt.cluster, dt.application,
       dt.namespace, dt.sync_mode
FROM deploy_targets dt
JOIN environments e ON e.id = dt.environment_id
WHERE e.project_id = $1
ORDER BY e.name
`

type ListDeployTargetsForProjectRow struct {
	ID          pgtype.UUID
	Environment string
	Provider    string
	Cluster     string
	Application string
	Namespace   string
	SyncMode    string
}

func (q *Queries) ListDeployTargetsForProject(ctx context.Context, projectID pgtype.UUID) ([]ListDeployTargetsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeployTargetsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeployTargetsForProjectRow{}
	for rows.Next() {
		var i ListDeployTargetsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Environment,
			&i.Provider,
			&i.Cluster,
			&i.Application,
			&i.Namespace,
			&i.SyncMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDeployTarget = `-- name: ResolveDeployTarget :one
SELECT dt.provider, dt.cluster, dt.application, dt.namespace, dt.sync_mode,
       e.project_id, e.name AS environment
FROM deploy_targets dt
JOIN environments e ON e.id = dt.environment_id
WHERE e.project_id = $1 AND e.name = $2
`

type ResolveDeployTargetParams struct {
	ProjectID pgtype.UUID
	Name      string
}

type ResolveDeployTargetRow struct {
	Provider    string
	Cluster     string
	Application string
	Namespace   string
	SyncMode    string
	ProjectID   pgtype.UUID
	Environment string
}

// Resolve `deploy: { to: <env> }` for a project: join the environment to its
// target and return everything the provider needs.
func (q *Queries) ResolveDeployTarget(ctx context.Context, arg ResolveDeployTargetParams) (ResolveDeployTargetRow, error) {
	row := q.db.QueryRow(ctx, resolveDeployTarget, arg.ProjectID, arg.Name)
	var i ResolveDeployTargetRow
	err := row.Scan(
		&i.Provider,
		&i.Cluster,
		&i.Application,
		&i.Namespace,
		&i.SyncMode,
		&i.ProjectID,
		&i.Environment,
	)
	return i, err
}

const upsertDeployTarget = `-- name: UpsertDeployTarget :one
INSERT INTO deploy_targets (environment_id, provider, cluster, application, namespace, sync_mode, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (environment_id) DO UPDATE SET
    provider = EXCLUDED.provider,
    cluster = EXCLUDED.cluster,
    application = EXCLUDED.application,
    namespace = EXCLUDED.namespace,
    sync_mode = EXCLUDED.sync_mode,
    updated_at = NOW()
RETURNING id
`

type UpsertDeployTargetParams struct {
	EnvironmentID pgtype.UUID
	Provider      string
	Cluster       string
	Application   string
	Namespace     string
	SyncMode      string
	CreatedBy     string
}

// Register/update the deploy target for an environment (1:1). The admin API
// EnsureEnvironment's the environment first, then upserts here.
func (q *Queries) UpsertDeployTarget(ctx context.Context, arg UpsertDeployTargetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDeployTarget,
		arg.EnvironmentID,
		arg.Provider,
		arg.Cluster,
		arg.Application,
		arg.Namespace,
		arg.SyncMode,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
