// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_freezes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnvironmentFreeze = `-- name: DeleteEnvironmentFreeze :one
DELETE FROM environment_freezes
WHERE project_id = $1 AND name = $2
RETURNING frozen_at, frozen_by, reason
`

type DeleteEnvironmentFreezeParams struct {
	ProjectID pgtype.UUID
	Name      string
}

type DeleteEnvironmentFreezeRow struct {
	FrozenAt pgtype.Timestamptz
	FrozenBy string
	Reason   string
}

// Unfreeze. The `project_id` predicate IS the scope check — no separate
// EnvironmentBelongsToProject precheck is needed (and none would help: the
// freeze can exist without an environments row). Returns no row when it
// wasn't frozen, so unfreeze is idempotent and only a real thaw is audited.
func (q *Queries) DeleteEnvironmentFreeze(ctx context.Context, arg DeleteEnvironmentFreezeParams) (DeleteEnvironmentFreezeRow, error) {
	row := q.db.QueryRow(ctx, deleteEnvironmentFreeze, arg.ProjectID, arg.Name)
	var i DeleteEnvironmentFreezeRow
	err := row.Scan(&i.FrozenAt, &i.FrozenBy, &i.Reason)
	return i, err
}

const environmentIsFrozen = `-- name: EnvironmentIsFrozen :one
SELECT EXISTS (
    SELECT 1 FROM environment_freezes WHERE project_id = $1 AND name = $2
)
`

type EnvironmentIsFrozenParams struct {
	ProjectID pgtype.UUID
	Name      string
}

// The authoritative admission re-check, run INSIDE the admitting tx while
// holding ProjectEnvFreezeLockKey. Kept separate from GetEnvironmentFreeze so
// the hot path scans one bool instead of three columns it would discard.
func (q *Queries) EnvironmentIsFrozen(ctx context.Context, arg EnvironmentIsFrozenParams) (bool, error) {
	row := q.db.QueryRow(ctx, environmentIsFrozen, arg.ProjectID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const frozenEnvironments = `-- name: FrozenEnvironments :many
SELECT name
FROM environment_freezes
WHERE project_id = $1 AND name = ANY($2::text[])
ORDER BY name
`

type FrozenEnvironmentsParams struct {
	ProjectID pgtype.UUID
	Names     []string
}

// Batched freeze lookup for a set of env names: ONE query per scheduler tick
// for the active stage's deploy envs (and per approval for a gate's governed
// envs) instead of N per-job probes. Returns only the frozen ones, ORDER BY
// name so callers can pick a DETERMINISTIC "winning" env — the run-level
// queue_reason must not alternate between two frozen envs from tick to tick.
func (q *Queries) FrozenEnvironments(ctx context.Context, arg FrozenEnvironmentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, frozenEnvironments, arg.ProjectID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentFreeze = `-- name: GetEnvironmentFreeze :one
SELECT frozen_at, frozen_by, reason
FROM environment_freezes
WHERE project_id = $1 AND name = $2
`

type GetEnvironmentFreezeParams struct {
	ProjectID pgtype.UUID
	Name      string
}

type GetEnvironmentFreezeRow struct {
	FrozenAt pgtype.Timestamptz
	FrozenBy string
	Reason   string
}

// Single-env freeze state, PK probe. ErrNoRows = not frozen.
func (q *Queries) GetEnvironmentFreeze(ctx context.Context, arg GetEnvironmentFreezeParams) (GetEnvironmentFreezeRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentFreeze, arg.ProjectID, arg.Name)
	var i GetEnvironmentFreezeRow
	err := row.Scan(&i.FrozenAt, &i.FrozenBy, &i.Reason)
	return i, err
}

const insertEnvironmentFreeze = `-- name: InsertEnvironmentFreeze :one
INSERT INTO environment_freezes (project_id, name, frozen_by, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, name) DO NOTHING
RETURNING frozen_at
`

type InsertEnvironmentFreezeParams struct {
	ProjectID pgtype.UUID
	Name      string
	FrozenBy  string
	Reason    string
}

// Freeze (project, name). ON CONFLICT DO NOTHING makes the toggle idempotent
// AND preserves the ORIGINAL freeze: re-freezing an already-frozen env must
// not reset frozen_at/frozen_by/reason (that would erase who stopped
// production and why). Returns no row when it was already frozen, which is
// what drives the "only audit a real state change" branch in the store.
func (q *Queries) InsertEnvironmentFreeze(ctx context.Context, arg InsertEnvironmentFreezeParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertEnvironmentFreeze,
		arg.ProjectID,
		arg.Name,
		arg.FrozenBy,
		arg.Reason,
	)
	var frozen_at pgtype.Timestamptz
	err := row.Scan(&frozen_at)
	return frozen_at, err
}

const listRunsHeldByEnvironment = `-- name: ListRunsHeldByEnvironment :many
SELECT r.id
FROM runs r
JOIN pipelines pl ON pl.id = r.pipeline_id
WHERE pl.project_id = $1
  AND r.queue_reason = 'frozen-deploy:' || $2::text
  AND r.status IN ('queued', 'running')
`

type ListRunsHeldByEnvironmentParams struct {
	ProjectID pgtype.UUID
	Name      string
}

// The runs a freeze is currently holding, so unfreeze can NOTIFY each one
// awake instead of waiting up to a full scheduler tick.
//
// EXACT equality on the composed reason, never LIKE: ValidEnvironmentName
// allows `_`, which is a LIKE single-char wildcard, so
// `queue_reason LIKE 'frozen-deploy:staging_eu'` would also match
// `frozen-deploy:stagingXeu`. runs has no project_id (only pipeline_id), so
// the project scope comes through pipelines.
func (q *Queries) ListRunsHeldByEnvironment(ctx context.Context, arg ListRunsHeldByEnvironmentParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRunsHeldByEnvironment, arg.ProjectID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
