// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fanout.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findDownstreamUpstreamMaterials = `-- name: FindDownstreamUpstreamMaterials :many
SELECT m.id AS material_id, m.pipeline_id AS downstream_pipeline_id, m.config
FROM materials m
JOIN pipelines down ON down.id = m.pipeline_id
JOIN pipelines up ON up.id = $1::uuid
                 AND up.project_id = down.project_id
WHERE m.type = 'upstream'
  AND m.config->>'pipeline' = up.name
  AND m.config->>'stage' = $2::text
  AND COALESCE(m.config->>'status', 'success') = 'success'
ORDER BY down.name
`

type FindDownstreamUpstreamMaterialsParams struct {
	UpstreamPipelineID pgtype.UUID
	StageName          string
}

type FindDownstreamUpstreamMaterialsRow struct {
	MaterialID           pgtype.UUID
	DownstreamPipelineID pgtype.UUID
	Config               []byte
}

// For a completed stage on an upstream pipeline, find every "upstream"
// material in OTHER pipelines of the same project that points at it. The
// status filter respects `materials.config.status` (default 'success') so a
// user can gate downstream on specific outcomes.
func (q *Queries) FindDownstreamUpstreamMaterials(ctx context.Context, arg FindDownstreamUpstreamMaterialsParams) ([]FindDownstreamUpstreamMaterialsRow, error) {
	rows, err := q.db.Query(ctx, findDownstreamUpstreamMaterials, arg.UpstreamPipelineID, arg.StageName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDownstreamUpstreamMaterialsRow{}
	for rows.Next() {
		var i FindDownstreamUpstreamMaterialsRow
		if err := rows.Scan(&i.MaterialID, &i.DownstreamPipelineID, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRunByUpstream = `-- name: FindRunByUpstream :one
SELECT id, counter
FROM runs
WHERE pipeline_id = $1::uuid
  AND cause = 'upstream'
  AND (cause_detail->>'upstream_run_id')::uuid = $2::uuid
LIMIT 1
`

type FindRunByUpstreamParams struct {
	PipelineID    pgtype.UUID
	UpstreamRunID pgtype.UUID
}

type FindRunByUpstreamRow struct {
	ID      pgtype.UUID
	Counter int64
}

// Idempotency check for fanout: if we already created a downstream run for
// this (pipeline, upstream_run_id) pair, skip.
func (q *Queries) FindRunByUpstream(ctx context.Context, arg FindRunByUpstreamParams) (FindRunByUpstreamRow, error) {
	row := q.db.QueryRow(ctx, findRunByUpstream, arg.PipelineID, arg.UpstreamRunID)
	var i FindRunByUpstreamRow
	err := row.Scan(&i.ID, &i.Counter)
	return i, err
}

const getStageSummary = `-- name: GetStageSummary :one
SELECT s.id AS stage_run_id, s.name AS stage_name,
       r.id AS run_id, r.pipeline_id, r.counter, r.revisions,
       p.name AS pipeline_name
FROM stage_runs s
JOIN runs r ON r.id = s.run_id
JOIN pipelines p ON p.id = r.pipeline_id
WHERE s.id = $1
LIMIT 1
`

type GetStageSummaryRow struct {
	StageRunID   pgtype.UUID
	StageName    string
	RunID        pgtype.UUID
	PipelineID   pgtype.UUID
	Counter      int64
	Revisions    []byte
	PipelineName string
}

// Everything the fanout trigger needs to identify this stage's position
// (pipeline + run + counter + revisions) without multiple round-trips.
func (q *Queries) GetStageSummary(ctx context.Context, id pgtype.UUID) (GetStageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStageSummary, id)
	var i GetStageSummaryRow
	err := row.Scan(
		&i.StageRunID,
		&i.StageName,
		&i.RunID,
		&i.PipelineID,
		&i.Counter,
		&i.Revisions,
		&i.PipelineName,
	)
	return i, err
}
