// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github_check_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGithubCheckRun = `-- name: GetGithubCheckRun :one
SELECT run_id, installation_id, check_run_id, owner, repo, head_sha,
       status_context, reporting_mode, completed, created_at, updated_at
FROM github_check_runs
WHERE run_id = $1
`

type GetGithubCheckRunRow struct {
	RunID          pgtype.UUID
	InstallationID int64
	CheckRunID     *int64
	Owner          string
	Repo           string
	HeadSha        string
	StatusContext  string
	ReportingMode  string
	Completed      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Reporter needs owner/repo/check_run_id to patch a check when the
// run finishes. Returns ErrNoRows when the run didn't produce a
// check (most common path: no App installed, or feature disabled).
func (q *Queries) GetGithubCheckRun(ctx context.Context, runID pgtype.UUID) (GetGithubCheckRunRow, error) {
	row := q.db.QueryRow(ctx, getGithubCheckRun, runID)
	var i GetGithubCheckRunRow
	err := row.Scan(
		&i.RunID,
		&i.InstallationID,
		&i.CheckRunID,
		&i.Owner,
		&i.Repo,
		&i.HeadSha,
		&i.StatusContext,
		&i.ReportingMode,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markGithubCheckRunCompleted = `-- name: MarkGithubCheckRunCompleted :exec
UPDATE github_check_runs
SET completed = TRUE, updated_at = NOW()
WHERE run_id = $1
`

// Flips the link's lifecycle flag after the check is PATCHed to a terminal
// state on GitHub. A later rerun reads this to decide reuse vs. recreate:
// GitHub won't cleanly reopen a completed check (completed_at is set-once), so
// a completed link forces a fresh check run on the next reopen.
func (q *Queries) MarkGithubCheckRunCompleted(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markGithubCheckRunCompleted, runID)
	return err
}

const upsertGithubCheckRun = `-- name: UpsertGithubCheckRun :exec
INSERT INTO github_check_runs (
    run_id, installation_id, check_run_id, owner, repo, head_sha, status_context, reporting_mode, completed
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, FALSE)
ON CONFLICT (run_id) DO UPDATE SET
    installation_id = EXCLUDED.installation_id,
    check_run_id    = EXCLUDED.check_run_id,
    owner           = EXCLUDED.owner,
    repo            = EXCLUDED.repo,
    head_sha        = EXCLUDED.head_sha,
    status_context  = EXCLUDED.status_context,
    reporting_mode  = EXCLUDED.reporting_mode,
    completed       = FALSE,
    updated_at      = NOW()
`

type UpsertGithubCheckRunParams struct {
	RunID          pgtype.UUID
	InstallationID int64
	CheckRunID     *int64
	Owner          string
	Repo           string
	HeadSha        string
	StatusContext  string
	ReportingMode  string
}

// Called right after CreateCheckRun on GitHub responds; caller may
// already have an entry from a previous retry so we upsert rather
// than insert. updated_at bumps so we can spot stale rows later.
// completed is forced FALSE: a (re)created check run is open again, so a
// rerun that recreates the check resets the lifecycle flag.
// check_run_id is NULL in commit_status mode (no GitHub Check Run exists);
// reporting_mode is the per-run effective mode, persisted so complete/reopen
// read it back instead of re-deriving from the project's current setting.
func (q *Queries) UpsertGithubCheckRun(ctx context.Context, arg UpsertGithubCheckRunParams) error {
	_, err := q.db.Exec(ctx, upsertGithubCheckRun,
		arg.RunID,
		arg.InstallationID,
		arg.CheckRunID,
		arg.Owner,
		arg.Repo,
		arg.HeadSha,
		arg.StatusContext,
		arg.ReportingMode,
	)
	return err
}
