// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: github_check_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGithubCheckRun = `-- name: GetGithubCheckRun :one
SELECT run_id, installation_id, check_run_id, owner, repo, head_sha,
       created_at, updated_at
FROM github_check_runs
WHERE run_id = $1
`

// Reporter needs owner/repo/check_run_id to patch a check when the
// run finishes. Returns ErrNoRows when the run didn't produce a
// check (most common path: no App installed, or feature disabled).
func (q *Queries) GetGithubCheckRun(ctx context.Context, runID pgtype.UUID) (GithubCheckRun, error) {
	row := q.db.QueryRow(ctx, getGithubCheckRun, runID)
	var i GithubCheckRun
	err := row.Scan(
		&i.RunID,
		&i.InstallationID,
		&i.CheckRunID,
		&i.Owner,
		&i.Repo,
		&i.HeadSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGithubCheckRun = `-- name: UpsertGithubCheckRun :exec
INSERT INTO github_check_runs (
    run_id, installation_id, check_run_id, owner, repo, head_sha
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (run_id) DO UPDATE SET
    installation_id = EXCLUDED.installation_id,
    check_run_id    = EXCLUDED.check_run_id,
    owner           = EXCLUDED.owner,
    repo            = EXCLUDED.repo,
    head_sha        = EXCLUDED.head_sha,
    updated_at      = NOW()
`

type UpsertGithubCheckRunParams struct {
	RunID          pgtype.UUID
	InstallationID int64
	CheckRunID     int64
	Owner          string
	Repo           string
	HeadSha        string
}

// Called right after CreateCheckRun on GitHub responds; caller may
// already have an entry from a previous retry so we upsert rather
// than insert. updated_at bumps so we can spot stale rows later.
func (q *Queries) UpsertGithubCheckRun(ctx context.Context, arg UpsertGithubCheckRunParams) error {
	_, err := q.db.Exec(ctx, upsertGithubCheckRun,
		arg.RunID,
		arg.InstallationID,
		arg.CheckRunID,
		arg.Owner,
		arg.Repo,
		arg.HeadSha,
	)
	return err
}
