// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
	AddedBy pgtype.UUID
}

// Idempotent on (group_id, user_id) — re-adding is a no-op, not
// an error, so the UI's "add if not present" flow doesn't need
// a pre-check query.
func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.AddedBy)
	return err
}

const countJobRunApprovals = `-- name: CountJobRunApprovals :one
SELECT COUNT(*)::INT
FROM job_run_approvals
WHERE job_run_id = $1 AND decision = 'approved'
`

// Quorum check: how many approved votes (excluding rejects)
// has this gate accumulated?
func (q *Queries) CountJobRunApprovals(ctx context.Context, jobRunID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countJobRunApprovals, jobRunID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, created_by, created_at, updated_at
FROM groups
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, created_by, created_at, updated_at
FROM groups
WHERE name = $1
LIMIT 1
`

// Used on approve: gate carries group NAMES (not ids) so renames
// propagate cleanly. Lookup translates name → id → members.
func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at, updated_at
`

type InsertGroupParams struct {
	Name        string
	Description string
	CreatedBy   pgtype.UUID
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, insertGroup, arg.Name, arg.Description, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobRunApproval = `-- name: InsertJobRunApproval :one
INSERT INTO job_run_approvals
    (job_run_id, user_id, user_label, decision, comment)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (job_run_id, user_id) DO NOTHING
RETURNING job_run_id, user_id, decision, decided_at
`

type InsertJobRunApprovalParams struct {
	JobRunID  pgtype.UUID
	UserID    pgtype.UUID
	UserLabel string
	Decision  string
	Comment   string
}

type InsertJobRunApprovalRow struct {
	JobRunID  pgtype.UUID
	UserID    pgtype.UUID
	Decision  string
	DecidedAt pgtype.Timestamptz
}

// Records one vote on a gate. Unique (job_run_id, user_id) —
// double-voting is a conflict, not a silent dup. Returns
// (id, created) so the caller sees whether the vote actually
// landed or was a re-post from the same user.
func (q *Queries) InsertJobRunApproval(ctx context.Context, arg InsertJobRunApprovalParams) (InsertJobRunApprovalRow, error) {
	row := q.db.QueryRow(ctx, insertJobRunApproval,
		arg.JobRunID,
		arg.UserID,
		arg.UserLabel,
		arg.Decision,
		arg.Comment,
	)
	var i InsertJobRunApprovalRow
	err := row.Scan(
		&i.JobRunID,
		&i.UserID,
		&i.Decision,
		&i.DecidedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.email, u.name, u.role, gm.added_at
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY COALESCE(NULLIF(u.name, ''), u.email)
`

type ListGroupMembersRow struct {
	ID      pgtype.UUID
	Email   string
	Name    string
	Role    string
	AddedAt pgtype.Timestamptz
}

// Join against users so the UI renders name/email without a
// second round-trip. Orders by the user's display name so the
// admin UI reads alphabetically.
func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.description, g.created_by, g.created_at, g.updated_at,
       (SELECT COUNT(*) FROM group_members m WHERE m.group_id = g.id)::INT AS member_count
FROM groups g
ORDER BY g.name
`

type ListGroupsRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	MemberCount int32
}

// UI: admin-only list of groups + a cheap member count so the
// settings page can render "SRE (4 members)" without a second
// query per group.
func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRunApprovals = `-- name: ListJobRunApprovals :many
SELECT user_id, user_label, decision, comment, decided_at
FROM job_run_approvals
WHERE job_run_id = $1
ORDER BY decided_at ASC
`

type ListJobRunApprovalsRow struct {
	UserID    pgtype.UUID
	UserLabel string
	Decision  string
	Comment   string
	DecidedAt pgtype.Timestamptz
}

// Detail trail for the UI: every vote in chronological order.
func (q *Queries) ListJobRunApprovals(ctx context.Context, jobRunID pgtype.UUID) ([]ListJobRunApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listJobRunApprovals, jobRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunApprovalsRow{}
	for rows.Next() {
		var i ListJobRunApprovalsRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserLabel,
			&i.Decision,
			&i.Comment,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupNames = `-- name: ListUserGroupNames :many
SELECT g.name
FROM group_members gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1
`

// Permission check hot path: "is this user in any group that's
// in the gate's approver_groups?" — we fetch the user's group
// names once per approve call and intersect in Go. Names (not
// ids) match what the gate stores.
func (q *Queries) ListUserGroupNames(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserGroupNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const updateGroup = `-- name: UpdateGroup :exec
UPDATE groups
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateGroupParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) error {
	_, err := q.db.Exec(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	return err
}
