// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           pgtype.UUID
	Name         string
	TokenHash    string
	Version      *string
	Os           *string
	Arch         *string
	Tags         []string
	Capacity     int32
	Status       string
	LastSeenAt   pgtype.Timestamptz
	RegisteredAt pgtype.Timestamptz
}

type Artifact struct {
	ID            pgtype.UUID
	RunID         pgtype.UUID
	JobRunID      pgtype.UUID
	PipelineID    pgtype.UUID
	ProjectID     pgtype.UUID
	Path          string
	StorageKey    string
	SizeBytes     int64
	ContentSha256 string
	Status        string
	PinnedAt      pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type AuthProvider struct {
	ID            pgtype.UUID
	Name          string
	Kind          string
	DisplayName   string
	ClientID      string
	ClientSecret  []byte
	Issuer        string
	GithubApiBase string
	Enabled       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AuthState struct {
	StateHash  []byte
	Provider   string
	RedirectTo string
	Nonce      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Cach struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	Key            string
	StorageKey     string
	SizeBytes      int64
	ContentSha256  *string
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	LastAccessedAt pgtype.Timestamptz
}

type CronState struct {
	MaterialID  pgtype.UUID
	LastFiredAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GithubCheckRun struct {
	RunID          pgtype.UUID
	InstallationID int64
	CheckRunID     int64
	Owner          string
	Repo           string
	HeadSha        string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type JobRun struct {
	ID                  pgtype.UUID
	RunID               pgtype.UUID
	StageRunID          pgtype.UUID
	Name                string
	MatrixKey           *string
	Image               *string
	AgentID             pgtype.UUID
	Status              string
	ExitCode            *int32
	Error               *string
	Needs               []string
	StartedAt           pgtype.Timestamptz
	FinishedAt          pgtype.Timestamptz
	Attempt             int32
	ApprovalGate        bool
	Approvers           []string
	ApprovalDescription *string
	AwaitingSince       pgtype.Timestamptz
	DecidedBy           *string
	DecidedAt           pgtype.Timestamptz
	Decision            *string
}

type LogLine struct {
	ID       int64
	JobRunID pgtype.UUID
	Seq      int64
	Stream   string
	At       pgtype.Timestamptz
	Text     string
}

type Material struct {
	ID          pgtype.UUID
	PipelineID  pgtype.UUID
	Type        string
	Config      []byte
	Fingerprint string
	AutoUpdate  bool
	CreatedAt   pgtype.Timestamptz
}

type Modification struct {
	ID          int64
	MaterialID  pgtype.UUID
	Revision    string
	Branch      *string
	Author      *string
	Message     *string
	Payload     []byte
	CommittedAt pgtype.Timestamptz
	DetectedAt  pgtype.Timestamptz
}

type Pipeline struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	Name              string
	Definition        []byte
	DefinitionVersion int32
	ConfigRepo        *string
	ConfigPath        string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ConfigPath  string
}

type Run struct {
	ID          pgtype.UUID
	PipelineID  pgtype.UUID
	Counter     int64
	Cause       string
	CauseDetail []byte
	Status      string
	Revisions   []byte
	TriggeredBy *string
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type ScmSource struct {
	ID                 pgtype.UUID
	ProjectID          pgtype.UUID
	Provider           string
	Url                string
	DefaultBranch      string
	AuthRef            *string
	LastSyncedAt       pgtype.Timestamptz
	LastSyncedRevision *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	WebhookSecret      []byte
}

type Secret struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
	ValueEnc  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type StageRun struct {
	ID         pgtype.UUID
	RunID      pgtype.UUID
	Name       string
	Ordinal    int32
	Status     string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	AvatarUrl    string
	Provider     string
	ExternalID   string
	Role         string
	DisabledAt   pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	PasswordHash []byte
}

type UserPreference struct {
	UserID      pgtype.UUID
	Preferences []byte
	UpdatedAt   pgtype.Timestamptz
}

type UserSession struct {
	ID         []byte
	UserID     pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	UserAgent  string
	CreatedAt  pgtype.Timestamptz
}

type VcsIntegration struct {
	ID            pgtype.UUID
	Kind          string
	Name          string
	DisplayName   string
	AppID         *int64
	PrivateKey    []byte
	WebhookSecret []byte
	ApiBase       string
	Enabled       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID         int64
	Provider   string
	Event      string
	MaterialID pgtype.UUID
	Status     string
	HttpStatus int32
	Headers    []byte
	Payload    []byte
	Error      *string
	ReceivedAt pgtype.Timestamptz
}
