// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: platform_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePlatformSetting = `-- name: DeletePlatformSetting :exec
DELETE FROM platform_settings WHERE key = $1
`

// Removes a setting; the boot path then falls back to env config.
func (q *Queries) DeletePlatformSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deletePlatformSetting, key)
	return err
}

const getPlatformSetting = `-- name: GetPlatformSetting :one
SELECT key, value, credentials_enc, updated_at, updated_by
FROM platform_settings
WHERE key = $1
LIMIT 1
`

// Single-row lookup by string key. Returns the full envelope so
// the caller can decrypt the secret half locally with the cipher
// (no plaintext crosses the store boundary unless the caller
// explicitly decrypts).
func (q *Queries) GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getPlatformSetting, key)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CredentialsEnc,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertPlatformSetting = `-- name: UpsertPlatformSetting :one
INSERT INTO platform_settings (key, value, credentials_enc, updated_at, updated_by)
VALUES ($1, $2, $3, NOW(), $4)
ON CONFLICT (key) DO UPDATE
    SET value           = EXCLUDED.value,
        credentials_enc = EXCLUDED.credentials_enc,
        updated_at      = NOW(),
        updated_by      = EXCLUDED.updated_by
RETURNING key, value, credentials_enc, updated_at, updated_by
`

type UpsertPlatformSettingParams struct {
	Key            string
	Value          []byte
	CredentialsEnc []byte
	UpdatedBy      pgtype.UUID
}

// Idempotent write. Replaces value + credentials_enc on key
// collision. updated_at refreshes on every write so audit / UI
// "last changed" stays honest.
func (q *Queries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, upsertPlatformSetting,
		arg.Key,
		arg.Value,
		arg.CredentialsEnc,
		arg.UpdatedBy,
	)
	var i PlatformSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CredentialsEnc,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
