// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: project_crons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectCron = `-- name: DeleteProjectCron :exec
DELETE FROM project_crons WHERE id = $1
`

func (q *Queries) DeleteProjectCron(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectCron, id)
	return err
}

const getProjectCron = `-- name: GetProjectCron :one
SELECT id, project_id, name, expression, pipeline_ids, enabled,
       last_fired_at, created_by, created_at, updated_at
FROM project_crons
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProjectCron(ctx context.Context, id pgtype.UUID) (ProjectCron, error) {
	row := q.db.QueryRow(ctx, getProjectCron, id)
	var i ProjectCron
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Expression,
		&i.PipelineIds,
		&i.Enabled,
		&i.LastFiredAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectCron = `-- name: InsertProjectCron :one
INSERT INTO project_crons
    (project_id, name, expression, pipeline_ids, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, expression, pipeline_ids, enabled,
          last_fired_at, created_by, created_at, updated_at
`

type InsertProjectCronParams struct {
	ProjectID   pgtype.UUID
	Name        string
	Expression  string
	PipelineIds []pgtype.UUID
	Enabled     bool
	CreatedBy   pgtype.UUID
}

func (q *Queries) InsertProjectCron(ctx context.Context, arg InsertProjectCronParams) (ProjectCron, error) {
	row := q.db.QueryRow(ctx, insertProjectCron,
		arg.ProjectID,
		arg.Name,
		arg.Expression,
		arg.PipelineIds,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i ProjectCron
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Expression,
		&i.PipelineIds,
		&i.Enabled,
		&i.LastFiredAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledProjectCrons = `-- name: ListEnabledProjectCrons :many
SELECT id, project_id, name, expression, pipeline_ids,
       last_fired_at
FROM project_crons
WHERE enabled = TRUE
ORDER BY id
`

type ListEnabledProjectCronsRow struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	Name        string
	Expression  string
	PipelineIds []pgtype.UUID
	LastFiredAt pgtype.Timestamptz
}

// Ticker path: every enabled schedule in the system + its
// last-fired bookkeeping. N is small (projects × a handful of
// schedules each), so full-scan-in-memory is fine.
func (q *Queries) ListEnabledProjectCrons(ctx context.Context) ([]ListEnabledProjectCronsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledProjectCrons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledProjectCronsRow{}
	for rows.Next() {
		var i ListEnabledProjectCronsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Expression,
			&i.PipelineIds,
			&i.LastFiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCronsByProject = `-- name: ListProjectCronsByProject :many
SELECT id, project_id, name, expression, pipeline_ids, enabled,
       last_fired_at, created_by, created_at, updated_at
FROM project_crons
WHERE project_id = $1
ORDER BY created_at DESC, id ASC
`

// UI: list schedules bound to one project, newest first so
// recently-added shows at the top.
func (q *Queries) ListProjectCronsByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectCron, error) {
	rows, err := q.db.Query(ctx, listProjectCronsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectCron{}
	for rows.Next() {
		var i ProjectCron
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Expression,
			&i.PipelineIds,
			&i.Enabled,
			&i.LastFiredAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProjectCronFired = `-- name: MarkProjectCronFired :exec
UPDATE project_crons
SET last_fired_at = $2, updated_at = NOW()
WHERE id = $1
`

type MarkProjectCronFiredParams struct {
	ID          pgtype.UUID
	LastFiredAt pgtype.Timestamptz
}

// Called by the ticker after a successful evaluation+fire cycle.
// Same-second fires are gated via the cron expression parser
// reading last_fired_at — the store update closes that loop.
func (q *Queries) MarkProjectCronFired(ctx context.Context, arg MarkProjectCronFiredParams) error {
	_, err := q.db.Exec(ctx, markProjectCronFired, arg.ID, arg.LastFiredAt)
	return err
}

const updateProjectCron = `-- name: UpdateProjectCron :exec
UPDATE project_crons
SET name = $2,
    expression = $3,
    pipeline_ids = $4,
    enabled = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateProjectCronParams struct {
	ID          pgtype.UUID
	Name        string
	Expression  string
	PipelineIds []pgtype.UUID
	Enabled     bool
}

// Full-record update: UI saves the entire edited row so absent
// fields mean "cleared". Intentionally does NOT touch
// last_fired_at — that's bookkeeping the ticker owns.
func (q *Queries) UpdateProjectCron(ctx context.Context, arg UpdateProjectCronParams) error {
	_, err := q.db.Exec(ctx, updateProjectCron,
		arg.ID,
		arg.Name,
		arg.Expression,
		arg.PipelineIds,
		arg.Enabled,
	)
	return err
}
