// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectBySlug = `-- name: DeleteProjectBySlug :execrows
DELETE FROM projects WHERE slug = $1
`

// Returns the number of project rows deleted (0 or 1). ON DELETE
// CASCADE on every foreign key that points at projects carries
// the children (pipelines → materials → runs → artifacts, secrets,
// scm_sources, etc.), so this single statement is enough.
func (q *Queries) DeleteProjectBySlug(ctx context.Context, slug string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectBySlug, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findProjectBySlug = `-- name: FindProjectBySlug :one
SELECT id, slug, name, description, config_path, created_at, updated_at
FROM projects
WHERE slug = $1
LIMIT 1
`

type FindProjectBySlugRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) FindProjectBySlug(ctx context.Context, slug string) (FindProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, findProjectBySlug, slug)
	var i FindProjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ConfigPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectDeletionCounts = `-- name: GetProjectDeletionCounts :one
SELECT
    (SELECT COUNT(*) FROM pipelines WHERE project_id = p.id)::bigint        AS pipeline_count,
    (SELECT COUNT(*) FROM runs r
        JOIN pipelines pl ON pl.id = r.pipeline_id
        WHERE pl.project_id = p.id)::bigint                                  AS run_count,
    (SELECT COUNT(*) FROM secrets WHERE project_id = p.id)::bigint           AS secret_count,
    (SELECT COUNT(*) FROM scm_sources WHERE project_id = p.id)::bigint       AS scm_source_count
FROM projects p
WHERE p.slug = $1
`

type GetProjectDeletionCountsRow struct {
	PipelineCount  int64
	RunCount       int64
	SecretCount    int64
	ScmSourceCount int64
}

// Aggregated before the cascading delete so the caller can surface
// "deleted N pipelines, M runs, K secrets" without probing each
// table after the fact (by then the rows are gone). Kept as a
// single round-trip so the delete flow stays two calls, not six.
func (q *Queries) GetProjectDeletionCounts(ctx context.Context, slug string) (GetProjectDeletionCountsRow, error) {
	row := q.db.QueryRow(ctx, getProjectDeletionCounts, slug)
	var i GetProjectDeletionCountsRow
	err := row.Scan(
		&i.PipelineCount,
		&i.RunCount,
		&i.SecretCount,
		&i.ScmSourceCount,
	)
	return i, err
}

const getProjectNotifications = `-- name: GetProjectNotifications :one
SELECT notifications
FROM projects
WHERE id = $1
`

// Returns the project-level notifications JSONB array. The run-
// create path consults this when the pipeline's own `notifications:`
// block is absent (pipeline nil means "inherit"; pipeline empty
// list means "explicit opt-out" and we skip this entirely).
func (q *Queries) GetProjectNotifications(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProjectNotifications, id)
	var notifications []byte
	err := row.Scan(&notifications)
	return notifications, err
}

const setProjectNotifications = `-- name: SetProjectNotifications :exec
UPDATE projects
SET notifications = $2, updated_at = NOW()
WHERE id = $1
`

type SetProjectNotificationsParams struct {
	ID            pgtype.UUID
	Notifications []byte
}

// Replaces the project-level notifications list. Admin/maintainer
// UI writes here; the column has a NOT NULL default of '[]' so a
// fresh project never needs an initial INSERT against this field.
func (q *Queries) SetProjectNotifications(ctx context.Context, arg SetProjectNotificationsParams) error {
	_, err := q.db.Exec(ctx, setProjectNotifications, arg.ID, arg.Notifications)
	return err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (slug, name, description, config_path)
VALUES ($1, $2, $3, COALESCE(NULLIF($4::text, ''), '.gocdnext'))
ON CONFLICT (slug) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    config_path = COALESCE(NULLIF(EXCLUDED.config_path, ''), projects.config_path),
    updated_at  = NOW()
RETURNING id, slug, name, description, config_path, created_at, updated_at, (xmax = 0) AS created
`

type UpsertProjectParams struct {
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
}

type UpsertProjectRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Created     bool
}

// config_path defaults to '.gocdnext' at the SQL level. Apply
// callers that don't set it (legacy path, drift re-apply) get
// that default naturally via COALESCE on the column-side default.
// Callers that DO set it override via ON CONFLICT.
func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (UpsertProjectRow, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ConfigPath,
	)
	var i UpsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ConfigPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
