// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findProjectBySlug = `-- name: FindProjectBySlug :one
SELECT id, slug, name, description, config_path, created_at, updated_at
FROM projects
WHERE slug = $1
LIMIT 1
`

type FindProjectBySlugRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) FindProjectBySlug(ctx context.Context, slug string) (FindProjectBySlugRow, error) {
	row := q.db.QueryRow(ctx, findProjectBySlug, slug)
	var i FindProjectBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ConfigPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (slug, name, description, config_path)
VALUES ($1, $2, $3, COALESCE(NULLIF($4::text, ''), '.gocdnext'))
ON CONFLICT (slug) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    config_path = COALESCE(NULLIF(EXCLUDED.config_path, ''), projects.config_path),
    updated_at  = NOW()
RETURNING id, slug, name, description, config_path, created_at, updated_at, (xmax = 0) AS created
`

type UpsertProjectParams struct {
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
}

type UpsertProjectRow struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Description *string
	ConfigPath  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Created     bool
}

// config_path defaults to '.gocdnext' at the SQL level. Apply
// callers that don't set it (legacy path, drift re-apply) get
// that default naturally via COALESCE on the column-side default.
// Callers that DO set it override via ON CONFLICT.
func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (UpsertProjectRow, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ConfigPath,
	)
	var i UpsertProjectRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ConfigPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
