// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Moves a queued, unassigned job to running and records the agent. The status
	// predicate prevents a race where two scheduler ticks pick the same job.
	AssignJob(ctx context.Context, arg AssignJobParams) (AssignJobRow, error)
	// Flips a run to 'canceled' only if it was still active. Idempotent:
	// a second call on a terminal run returns no rows so the handler
	// can answer 409. Returns the row id so the caller can tell the
	// update happened.
	CancelActiveRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Pending approval gates in a failed run also get canceled so a
	// rejected deploy doesn't leave a "ready to approve" ghost sitting
	// in the UI with no path forward. Reject is the intended decision
	// path; cancel here only fires on upstream stage failure. Jobs
	// inside the synthetic _notifications stage are preserved so
	// `on: failure` notifications still fire.
	CancelQueuedJobsInRun(ctx context.Context, runID pgtype.UUID) error
	// When a user stage fails we stop dispatching the rest of the run's user
	// stages. Running work stays untouched; the agent will still report its
	// outcome. The synthetic _notifications stage is preserved on purpose —
	// a pipeline that declared `on: failure` notifications still needs them
	// to fire. The scheduler filters the notification jobs by `on:` when
	// dispatching so only the matching ones actually run.
	CancelQueuedStagesInRun(ctx context.Context, runID pgtype.UUID) error
	// Atomically marks a bounded batch of artefacts as 'deleting' and
	// returns their storage keys so the sweeper can call Store.Delete and
	// then remove the DB row.
	//
	// Two populations get claimed:
	//   1) Freshly-expired rows: status='ready' AND expires_at < now() AND
	//      not pinned. Standard TTL sweep.
	//   2) Rows left in 'deleting' for longer than the grace window — the
	//      previous sweeper crashed between "marked deleting" and "storage
	//      delete + row removed". We pick those up and retry idempotently.
	//
	// FOR UPDATE SKIP LOCKED makes this safe to run from multiple
	// schedulers/sweepers at once; each gets a disjoint batch.
	ClaimArtifactsForSweep(ctx context.Context, arg ClaimArtifactsForSweepParams) ([]ClaimArtifactsForSweepRow, error)
	// Flips a queued or running job to its terminal state. Idempotent: matches
	// only non-terminal rows. Accepting 'queued' lets the scheduler fail a job
	// at dispatch time (e.g. unresolved secret) without first flipping it to
	// running via AssignJob. Returns stage/run ids so the caller can cascade.
	CompleteJobRun(ctx context.Context, arg CompleteJobRunParams) (CompleteJobRunRow, error)
	CompleteRun(ctx context.Context, arg CompleteRunParams) error
	CompleteStageRun(ctx context.Context, arg CompleteStageRunParams) error
	// Single-use: delete as we read. Returning nothing = no such state
	// (or it expired and the sweeper got to it first).
	ConsumeAuthState(ctx context.Context, stateHash []byte) (ConsumeAuthStateRow, error)
	// Drives the "show local login form" decision on the login page:
	// no rows = zero local admins, the form stays hidden so the page
	// doesn't advertise a dead code path.
	CountLocalUsers(ctx context.Context) (int64, error)
	CountRunsByPipeline(ctx context.Context, pipelineID pgtype.UUID) (int64, error)
	// Paired with ListRunsGlobal so /runs can render "N of M" with the
	// same filter args. Returned as bigint to fit any table; UI only
	// needs int32 but this avoids cast noise.
	CountRunsGlobal(ctx context.Context, arg CountRunsGlobalParams) (int64, error)
	// Pair for ListWebhookDeliveries so the UI can render "N of M".
	CountWebhookDeliveries(ctx context.Context, arg CountWebhookDeliveriesParams) (int64, error)
	// Median run duration in seconds across the last 7 days. NULL when
	// no finished runs.
	DashboardP50DurationSec7d(ctx context.Context) (float64, error)
	// Active backlog: every queued run across the system, plus queued
	// + running job_runs (the scheduler's work left to do).
	DashboardQueueDepth(ctx context.Context) (DashboardQueueDepthRow, error)
	// Count of runs created today (server-local day boundary via
	// now()::date).
	DashboardRunsToday(ctx context.Context) (int64, error)
	// Terminal runs in the last 7 days, broken down by outcome. The
	// caller computes rate = success / (success + failure). Returns
	// 0 when no terminal runs in the window.
	DashboardSuccessRate7d(ctx context.Context) (DashboardSuccessRate7dRow, error)
	DeleteAuthProvider(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredAuthStates(ctx context.Context) error
	DeleteExpiredUserSessions(ctx context.Context) error
	DeleteGlobalSecretByName(ctx context.Context, name string) (int64, error)
	// Called after a successful reclaim so the retry starts with a clean log
	// window. Loses the old attempt's output — acceptable MVP trade for not
	// growing the schema to carry per-attempt log namespacing.
	DeleteLogLinesByJob(ctx context.Context, jobRunID pgtype.UUID) error
	DeleteMaterial(ctx context.Context, id pgtype.UUID) error
	DeletePipeline(ctx context.Context, id pgtype.UUID) error
	// Returns the number of project rows deleted (0 or 1). ON DELETE
	// CASCADE on every foreign key that points at projects carries
	// the children (pipelines → materials → runs → artifacts, secrets,
	// scm_sources, etc.), so this single statement is enough.
	DeleteProjectBySlug(ctx context.Context, slug string) (int64, error)
	DeleteSecretByName(ctx context.Context, arg DeleteSecretByNameParams) (int64, error)
	DeleteUserSession(ctx context.Context, id []byte) error
	DeleteUserSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	DeleteVCSIntegration(ctx context.Context, id pgtype.UUID) error
	// Keep-last policy: per pipeline, rank the runs that produced
	// non-deleted artefacts by recency (run.created_at DESC); any run
	// beyond position N has ALL its non-pinned artefacts stamped with
	// expires_at = NOW(). The next TTL sweep picks them up. Pinned rows
	// are exempt; pinned runs don't consume a "slot" — they live forever
	// orthogonally to the N budget.
	ExpireArtifactsBeyondKeepLast(ctx context.Context, dollar_1 int32) (int64, error)
	ExpireOldestGloballyByExcess(ctx context.Context, dollar_1 int64) (int64, error)
	// Stamp expires_at = NOW() on the oldest non-pinned rows in a project,
	// stopping as soon as the demoted bytes cover `excess`. Uses a window
	// function so the cut-off is computed against the cumulative-up-to-
	// but-not-including-this-row (so we always demote enough, never
	// less).
	ExpireOldestInProjectByExcess(ctx context.Context, arg ExpireOldestInProjectByExcessParams) (int64, error)
	FindAgentByName(ctx context.Context, name string) (Agent, error)
	// Same shape as ListAgentsWithRunning but for one row — reused by
	// the /agents/{id} page. Returns ErrNoRows when the UUID is not
	// an existing agent.
	FindAgentWithRunning(ctx context.Context, id pgtype.UUID) (FindAgentWithRunningRow, error)
	// For a completed stage on an upstream pipeline, find every "upstream"
	// material in OTHER pipelines of the same project that points at it. The
	// status filter respects `materials.config.status` (default 'success') so a
	// user can gate downstream on specific outcomes.
	FindDownstreamUpstreamMaterials(ctx context.Context, arg FindDownstreamUpstreamMaterialsParams) ([]FindDownstreamUpstreamMaterialsRow, error)
	FindMaterialByFingerprint(ctx context.Context, fingerprint string) (Material, error)
	FindProjectBySlug(ctx context.Context, slug string) (FindProjectBySlugRow, error)
	// Idempotency check for fanout: if we already created a downstream run for
	// this (pipeline, upstream_run_id) pair, skip.
	FindRunByUpstream(ctx context.Context, arg FindRunByUpstreamParams) (FindRunByUpstreamRow, error)
	// Rotation + UI detail views go project-slug → scm_source without
	// the caller having to resolve the project id first.
	FindScmSourceBySlug(ctx context.Context, slug string) (FindScmSourceBySlugRow, error)
	// Read path used by webhook drift detection and future UI
	// listings. Does NOT return webhook_secret — that's handled by
	// GetScmSourceWebhookSecret to keep ciphertext out of the general
	// read path.
	FindScmSourceByURL(ctx context.Context, url string) (FindScmSourceByURLRow, error)
	// Single-row lookup for the JobResult confirmation path. Returns
	// ErrNoRows if the agent invented a key or the row was swept.
	GetArtifactByStorageKey(ctx context.Context, storageKey string) (GetArtifactByStorageKeyRow, error)
	GetAuthProviderByID(ctx context.Context, id pgtype.UUID) (AuthProvider, error)
	// Reporter needs owner/repo/check_run_id to patch a check when the
	// run finishes. Returns ErrNoRows when the run didn't produce a
	// check (most common path: no App installed, or feature disabled).
	GetGithubCheckRun(ctx context.Context, runID pgtype.UUID) (GithubCheckRun, error)
	// Resolver fallback: after GetSecretValuesByProject, names still
	// missing are looked up as globals. Kept as a separate call so
	// the resolver can short-circuit when every name was already
	// covered at project scope.
	GetGlobalSecretValues(ctx context.Context, dollar_1 []string) ([]GetGlobalSecretValuesRow, error)
	// Used by the reaper to disambiguate "at max attempts" from "already
	// handled" when ReclaimJobForRetry returned no rows.
	GetJobAttempt(ctx context.Context, id pgtype.UUID) (GetJobAttemptRow, error)
	// Resolves pipeline_id + project_id + agent_id for a (job_run_id,
	// run_id) pair. Used by the RequestArtifactUpload handler to authorise
	// + derive the FKs. Returns ErrNoRows if job_run_id doesn't belong to
	// the claimed run_id. agent_id is NULL when the job hasn't been
	// dispatched yet (shouldn't happen on this code path but the column
	// nullability forces us to handle it).
	GetJobRunParents(ctx context.Context, arg GetJobRunParentsParams) (GetJobRunParentsRow, error)
	// Most recent modification across any material attached to a
	// pipeline. Powers "trigger latest" for manual runs. Ordered by
	// detected_at so the newest webhook delivery wins even when the
	// committer timestamp is older (rebases, fast-forwards of older
	// commits).
	GetLatestModificationForPipeline(ctx context.Context, pipelineID pgtype.UUID) (GetLatestModificationForPipelineRow, error)
	// Fetches the row we need to bcrypt-compare on a login POST.
	// Filtering by provider keeps an OIDC user with the same email
	// from accidentally answering to a password form.
	GetLocalUserForLogin(ctx context.Context, email string) (User, error)
	GetModificationByKey(ctx context.Context, arg GetModificationByKeyParams) (Modification, error)
	GetPipelineDefinition(ctx context.Context, id pgtype.UUID) (GetPipelineDefinitionRow, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (GetProjectByIDRow, error)
	GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error)
	// Aggregated before the cascading delete so the caller can surface
	// "deleted N pipelines, M runs, K secrets" without probing each
	// table after the fact (by then the rows are gone). Kept as a
	// single round-trip so the delete flow stays two calls, not six.
	GetProjectDeletionCounts(ctx context.Context, slug string) (GetProjectDeletionCountsRow, error)
	// Thin row used by cancel/rerun handlers to check status + find the
	// pipeline + revisions without pulling the whole detail query.
	GetRunForAction(ctx context.Context, id pgtype.UUID) (GetRunForActionRow, error)
	GetRunForDispatch(ctx context.Context, id pgtype.UUID) (GetRunForDispatchRow, error)
	GetRunProgress(ctx context.Context, runID pgtype.UUID) (GetRunProgressRow, error)
	// For a downstream run, extracts upstream_run_id + upstream pipeline
	// name from cause_detail JSON. Empty string / null UUID when this run
	// was NOT triggered by an upstream material (cause is 'webhook' /
	// 'manual'). Caller checks upstream_run_id.Valid.
	GetRunUpstreamContext(ctx context.Context, id pgtype.UUID) (GetRunUpstreamContextRow, error)
	// Aggregate job outcomes across USER stages only (everything except
	// the synthetic _notifications). The cascade uses this to decide the
	// final run.status when finalizing — notification success/failure
	// must not flip a user run from success to failed or vice versa.
	GetRunUserStageOutcome(ctx context.Context, runID pgtype.UUID) (GetRunUserStageOutcomeRow, error)
	// pl.definition is returned so the read path can decode the
	// notifications array and stamp on/uses onto synth job rows
	// without a second round-trip. Adds one JSONB column to the
	// response but avoids a per-run "did this pipeline have
	// notifications?" lookup.
	GetRunWithPipeline(ctx context.Context, id pgtype.UUID) (GetRunWithPipelineRow, error)
	GetScmSourceByProject(ctx context.Context, projectID pgtype.UUID) (GetScmSourceByProjectRow, error)
	// Webhook-handler path: pulls the sealed secret + the scm_source
	// id for a given clone_url so HandleGitHub can verify HMAC with
	// the right per-repo key. Returns an empty BYTEA when the row
	// has no secret configured yet (the caller then answers 401 —
	// "no webhook secret registered for this repo").
	GetScmSourceWebhookSecretByURL(ctx context.Context, url string) (GetScmSourceWebhookSecretByURLRow, error)
	// Used by the scheduler when a job declares `secrets: [FOO, BAR]`. Returns
	// the encrypted blobs; the caller decrypts and injects as env vars.
	GetSecretValuesByProject(ctx context.Context, arg GetSecretValuesByProjectParams) ([]GetSecretValuesByProjectRow, error)
	// Counts jobs still working vs already-failed within a stage — the numbers
	// the caller uses to decide whether to promote the stage. `awaiting_approval`
	// is unfinished too: the gate hasn't decided yet, so the stage can't close.
	GetStageProgress(ctx context.Context, stageRunID pgtype.UUID) (GetStageProgressRow, error)
	// Everything the fanout trigger needs to identify this stage's position
	// (pipeline + run + counter + revisions) without multiple round-trips.
	GetStageSummary(ctx context.Context, id pgtype.UUID) (GetStageSummaryRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// Returns the stored preferences blob for a user. Callers treat
	// the "no row" case as "empty preferences" (pgx.ErrNoRows); this
	// query stays minimal so the shape follows the JSONB document
	// rather than forcing a struct on every new key.
	GetUserPreferences(ctx context.Context, userID pgtype.UUID) (GetUserPreferencesRow, error)
	// Returns the session + its user row. Expired rows are filtered in
	// the query so a single round-trip tells the handler "yes/no".
	GetUserSession(ctx context.Context, id []byte) (GetUserSessionRow, error)
	GetVCSIntegrationByID(ctx context.Context, id pgtype.UUID) (VcsIntegration, error)
	// Expands a row with its headers + payload JSON for the drawer
	// view. Kept in a separate query so the list shot stays tiny
	// (payloads can be 100+ KB).
	GetWebhookDelivery(ctx context.Context, id int64) (WebhookDelivery, error)
	// Total live artefact bytes. Returns 0 when the artifacts table is
	// empty. Used for the global hard cap.
	GlobalArtifactUsage(ctx context.Context) (int64, error)
	InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error)
	// Write-only hot path — every RBAC'd mutation fires one of these.
	// at is stamped by the DB so clock skew on multi-replica setups
	// doesn't re-order events inside a single tick.
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertAuthState(ctx context.Context, arg InsertAuthStateParams) error
	InsertJobRun(ctx context.Context, arg InsertJobRunParams) (InsertJobRunRow, error)
	// Agents send log lines with a per-(job_run_id) monotonic seq; the UNIQUE
	// constraint makes retries safe.
	InsertLogLine(ctx context.Context, arg InsertLogLineParams) error
	InsertMaterial(ctx context.Context, arg InsertMaterialParams) (Material, error)
	InsertModification(ctx context.Context, arg InsertModificationParams) (Modification, error)
	// Inserts a row in `pending` status ahead of the agent's upload. The
	// storage_key is generated by the caller (UUID-based) so the row's id and
	// the backend's object key are decoupled — makes it safe to retry without
	// ending up with orphan objects keyed off a stale PK.
	InsertPendingArtifact(ctx context.Context, arg InsertPendingArtifactParams) (InsertPendingArtifactRow, error)
	InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error)
	InsertStageRun(ctx context.Context, arg InsertStageRunParams) (InsertStageRunRow, error)
	InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error
	// Append-only audit row for every HTTP call that lands on
	// /api/webhooks/*. Rows outlive the request so the admin page can
	// show signature-rejected and drift-only deliveries too, not just
	// the ones that produced a modification.
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (InsertWebhookDeliveryRow, error)
	// Per-pipeline latest run with the triggering modification's
	// commit metadata (branch, message, author, short revision). The
	// runs.revisions JSONB is keyed by material_id; we unpack it and
	// match each (material_id, revision) to the modification row
	// that actually produced the run. LIMIT/DISTINCT ON at each level
	// keeps the output one row per pipeline even when a run snapshots
	// multiple materials — we pick the first match deterministically
	// (order by material_id) so the card shows a stable ref.
	LatestRunMetaByProjectSlug(ctx context.Context, slug string) ([]LatestRunMetaByProjectSlugRow, error)
	// Per-project commit metadata from the most recent run across all
	// of the project's pipelines. Same JSONB-expand pattern as the
	// per-slug variant, just without the slug filter so one query
	// serves the whole projects list. triggered_by is kept so the UI
	// can fall back to the manual-trigger user when author is null
	// (manual runs don't create webhook-driven modifications).
	LatestRunMetaPerProject(ctx context.Context) ([]LatestRunMetaPerProjectRow, error)
	// DISTINCT ON picks the most recent run per pipeline. Pipelines with
	// no runs yet are absent from the result; the handler merges with
	// ListPipelinesByProjectSlug to produce node entries.
	LatestRunPerPipelineByProjectSlug(ctx context.Context, slug string) ([]LatestRunPerPipelineByProjectSlugRow, error)
	// Dashboard + /agents list: every agent with its declared metadata
	// + a count of currently-running job_runs it's been assigned.
	// LEFT JOIN + FILTER gives 0 for idle agents without needing a
	// second roundtrip.
	ListAgentsWithRunning(ctx context.Context) ([]ListAgentsWithRunningRow, error)
	// Used by server-side JobResult reconciliation to match ArtifactRef
	// entries back to their pending rows. Also used later (E2c) to expose
	// downloads to downstream jobs in the same run.
	ListArtifactsByJobRun(ctx context.Context, jobRunID pgtype.UUID) ([]ListArtifactsByJobRunRow, error)
	// Used by E2c for intra-run downloads (`needs_artifacts:` resolution).
	// Only returns ready artefacts — pending/deleting must not leak as
	// dependable to downstream jobs.
	ListArtifactsByRun(ctx context.Context, runID pgtype.UUID) ([]ListArtifactsByRunRow, error)
	// Same as ListArtifactsByRun but joined with job_runs.name so the UI
	// can group artefacts by the job that produced them without an extra
	// per-artifact lookup. Returns ALL statuses — callers filter as needed.
	ListArtifactsWithJobByRun(ctx context.Context, runID pgtype.UUID) ([]ListArtifactsWithJobByRunRow, error)
	// Reverse-chrono listing with optional filters. Empty string on
	// action_filter / target_type_filter / actor_email_filter
	// disables that filter; nil actor_id_filter disables actor
	// filtering (applied separately because typing empty UUID as
	// "no filter" leaks).
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	// Returns every row regardless of `enabled`. The UI filters on
	// the boolean so admins can see disabled providers they can re-
	// enable later.
	ListAuthProviders(ctx context.Context) ([]AuthProvider, error)
	// Loads every cron material in the system alongside its pipeline
	// / project id and its last-fired timestamp (NULL when never
	// fired). The ticker walks this list on every tick; N is bounded
	// by `pipelines × cron_materials_per_pipeline`, typically a few
	// dozen at most, so scanning in-process is fine.
	ListCronMaterials(ctx context.Context) ([]ListCronMaterialsRow, error)
	// Returns queued jobs in the lowest-ordinal stage that still has queued or
	// running work. The scheduler does needs-satisfaction checking in Go so the
	// query stays readable; the stage gate is the only SQL-level constraint.
	ListDispatchableJobs(ctx context.Context, runID pgtype.UUID) ([]ListDispatchableJobsRow, error)
	// Bootstrap path: just the ones that should be registered on
	// server start (or after a reload).
	ListEnabledAuthProviders(ctx context.Context) ([]AuthProvider, error)
	// Bootstrap + reload path: rows the registry should actually
	// instantiate on startup.
	ListEnabledVCSIntegrations(ctx context.Context) ([]VcsIntegration, error)
	// Admin-only listing of every global (unscoped) secret. Same
	// "names + timestamps, never values" contract as project secrets.
	ListGlobalSecrets(ctx context.Context) ([]ListGlobalSecretsRow, error)
	ListJobRunsByRun(ctx context.Context, runID pgtype.UUID) ([]ListJobRunsByRunRow, error)
	ListJobRunsByRunFull(ctx context.Context, runID pgtype.UUID) ([]ListJobRunsByRunFullRow, error)
	// Batch-loads job_runs for every run whose id is in the input
	// array. The project detail page renders a GitLab-style pipeline
	// flow per pipeline, each stage box listing its jobs — fetching
	// these per pipeline would mean N queries. This single scan
	// covers the card set.
	ListJobRunsForRuns(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListJobRunsForRunsRow, error)
	// Recent jobs dispatched to this agent. Joined all the way up to
	// the project so the table can link to the owning run/project
	// without per-row lookups. LIMIT is caller-supplied to avoid
	// pagination complexity for now (UI caps at 100).
	ListJobsForAgent(ctx context.Context, arg ListJobsForAgentParams) ([]ListJobsForAgentRow, error)
	ListMaterialsByPipeline(ctx context.Context, pipelineID pgtype.UUID) ([]Material, error)
	// All materials across pipelines of a project. VSM uses the
	// `upstream` ones to build edges between pipeline nodes; git ones
	// are informational (shown as entry points on the graph).
	ListMaterialsByProjectSlug(ctx context.Context, slug string) ([]ListMaterialsByProjectSlugRow, error)
	ListPipelinesByProject(ctx context.Context, projectID pgtype.UUID) ([]ListPipelinesByProjectRow, error)
	// Returns definition alongside metadata so the card can pull
	// stage names from the YAML when the pipeline has never run
	// (no stage_runs yet → no history to render from).
	ListPipelinesByProjectSlug(ctx context.Context, slug string) ([]ListPipelinesByProjectSlugRow, error)
	// Projects whose total live artefact bytes (pending + ready, non-
	// deleted, non-pinned) exceed the configured soft cap. Returned once
	// per tick so the sweeper can ExpireOldestInProjectByExcess against
	// each one individually.
	ListProjectsOverArtifactQuota(ctx context.Context, dollar_1 int64) ([]ListProjectsOverArtifactQuotaRow, error)
	// Project list used by the dashboard home. Joins enough aggregate info so the
	// UI renders without round-tripping per row.
	//
	// Extra columns feed the card-style layout on /projects:
	//   * provider: from the bound scm_source when present; empty string
	//     when the project has no repo yet (shown as "—" in the UI).
	//   * run_count: total runs across all pipelines — the card shows
	//     "5 pipelines · 123 runs" as a density signal.
	//   * status_agg: coarse health derived from the most recent run per
	//     pipeline. Pre-computed in a CTE (latest_per_pipeline) so the
	//     outer aggregate stays aggregate-only; correlated subqueries
	//     inside CASE/WHEN during GROUP BY are fragile in Postgres and
	//     blew up the previous version of this query.
	ListProjectsWithCounts(ctx context.Context) ([]ListProjectsWithCountsRow, error)
	// Runs the scheduler's tick reconsiders: both freshly queued ones and
	// already-running runs that may have a queued job waiting (re-queued by the
	// reaper, blocked waiting for a next stage, etc.).
	ListQueuedRunIDs(ctx context.Context) ([]pgtype.UUID, error)
	// Returns ready artefacts produced by a specific job name within a run,
	// optionally filtered by a path whitelist. Used by the scheduler when
	// resolving `needs_artifacts` on a downstream job. An empty paths
	// array returns all of that job's artefacts.
	ListReadyArtifactsByRunAndJobName(ctx context.Context, arg ListReadyArtifactsByRunAndJobNameParams) ([]ListReadyArtifactsByRunAndJobNameRow, error)
	ListRunsByProjectSlug(ctx context.Context, arg ListRunsByProjectSlugParams) ([]ListRunsByProjectSlugRow, error)
	// Cross-project timeline: most recent runs first. Carries the
	// pipeline + project names so list views can link without per-row
	// lookups. All filter params accept the empty string as "no filter"
	// so the same query drives the dashboard widget (no filters) and
	// the /runs page (every filter the UI exposes).
	ListRunsGlobal(ctx context.Context, arg ListRunsGlobalParams) ([]ListRunsGlobalRow, error)
	// Lists names + timestamps only — values never leave the DB without going
	// through GetSecretValuesByProject below.
	ListSecretsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListSecretsByProjectRow, error)
	ListStageRunsByRun(ctx context.Context, runID pgtype.UUID) ([]ListStageRunsByRunRow, error)
	ListStageRunsByRunOrdered(ctx context.Context, runID pgtype.UUID) ([]ListStageRunsByRunOrderedRow, error)
	// Batch-loads stage_runs for every run whose id is in the input
	// array — the project detail page renders one pipeline card per
	// pipeline and each card needs the latest run's stage states.
	// Issuing one query per card would mean N+1 round trips; this
	// amortizes them into a single scan.
	ListStageRunsForRuns(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListStageRunsForRunsRow, error)
	// Running jobs whose agent is either offline or hasn't been seen within
	// @staleness. The reaper walks this list every tick and either re-queues or
	// fails them.
	ListStaleRunningJobs(ctx context.Context, staleness pgtype.Interval) ([]ListStaleRunningJobsRow, error)
	// Per-project top-N (most recently updated) pipelines with their
	// latest run status. Used to render the "mini stack" inside each
	// project card without issuing one query per card (N+1). Capped at
	// 20 entries per project via ROW_NUMBER partition — the side-by-
	// side pipeline layout in the card fits comfortably up to ~10
	// pipelines; projects beyond that surface a "+K more" hint. Bump
	// the cap further if real-world projects regularly cross it.
	//
	// Also returns:
	//   * latest_run_id: zero-UUID when the pipeline has never run.
	//     Callers collect these to batch-load stage_runs.
	//   * definition: the pipeline's YAML snapshot (JSONB). The card
	//     renders grey "pending" stage pills from definition.Stages
	//     when latest_run_id is zero, and reconciles definition vs.
	//     stage_runs for mid-run/cancelled states.
	ListTopPipelinesPerProject(ctx context.Context) ([]ListTopPipelinesPerProjectRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// Admin feed. Returns every row regardless of `enabled` so the
	// /settings/integrations page can surface disabled rows the user
	// can re-enable.
	ListVCSIntegrations(ctx context.Context) ([]VcsIntegration, error)
	// Admin console feed. Most recent first; indexed on received_at.
	// Filter by provider + status keep the page useful even under
	// heavy traffic. Empty string = no filter on that axis.
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	MarkAgentOffline(ctx context.Context, id pgtype.UUID) error
	// Called after the server HEADs the storage and confirms the object is
	// there. Bumps status + records size/sha. Safe to call once; subsequent
	// calls update nothing (status already 'ready'), returning 0 rows.
	MarkArtifactReady(ctx context.Context, arg MarkArtifactReadyParams) (int64, error)
	MarkRunRunningIfQueued(ctx context.Context, id pgtype.UUID) error
	MarkStageRunningIfQueued(ctx context.Context, id pgtype.UUID) error
	NextRunCounter(ctx context.Context, pipelineID pgtype.UUID) (int64, error)
	// Returns true when the pipeline has any run in 'running' status
	// other than the one we're about to dispatch. The scheduler checks
	// this for pipelines configured with concurrency: serial and
	// leaves the run queued when another one is already in flight.
	// Excluded self so a re-entrant tick (scheduler evaluates the
	// same run twice) doesn't see itself as a blocker.
	OtherRunningRunExistsForPipeline(ctx context.Context, arg OtherRunningRunExistsForPipelineParams) (bool, error)
	// Per-pipeline aggregate stats over the last $2 interval. Terminal
	// runs only — queued/running are excluded so the medians don't move
	// during active work. `process_time_p50_seconds` is the median of
	// the per-run sum of stage_run durations (actual busy time),
	// distinct from `lead_time_p50_seconds` (wall-clock run duration).
	PipelineMetricsByProjectSlug(ctx context.Context, arg PipelineMetricsByProjectSlugParams) ([]PipelineMetricsByProjectSlugRow, error)
	// Per-stage aggregates over the same window. Feeds the card's
	// per-stage duration badge (p50) and bottleneck call-out (success
	// rate under threshold). Only terminal stage_runs count — a
	// running/cancelled stage without finished_at would poison the
	// median.
	PipelineStageMetricsByProjectSlug(ctx context.Context, arg PipelineStageMetricsByProjectSlugParams) ([]PipelineStageMetricsByProjectSlugRow, error)
	// Per-project roll-up of terminal runs over the last $1 interval.
	// Same math as PipelineMetricsByProjectSlug but grouped by project
	// instead of pipeline — the projects list card shows one KPI strip
	// per project, so aggregating in SQL saves an N×round-trip dance
	// when compared with looping the per-slug query per project.
	ProjectMetricsAggregated(ctx context.Context, sinceWindow pgtype.Interval) ([]ProjectMetricsAggregatedRow, error)
	// Flips a running job back to queued, IF it is still running AND still under
	// the retry cap. Returns the new attempt number; ErrNoRows signals the caller
	// should take a different code path (failed-at-max or already-handled).
	ReclaimJobForRetry(ctx context.Context, arg ReclaimJobForRetryParams) (ReclaimJobForRetryRow, error)
	// Called by the sweeper AFTER Store.Delete succeeded (or the object
	// was already gone). Removes the DB row.
	RemoveArtifactRow(ctx context.Context, id pgtype.UUID) (int64, error)
	SetAuthProviderEnabled(ctx context.Context, arg SetAuthProviderEnabledParams) error
	SetVCSIntegrationEnabled(ctx context.Context, arg SetVCSIntegrationEnabledParams) error
	// Marks a still-queued job as 'skipped' with a terminal finish
	// time so GetStageProgress stops counting it as unfinished. The
	// scheduler calls this for synthetic notification jobs whose
	// `on:` trigger doesn't match the run's user-stage outcome —
	// skipped is the right semantic (the job was never attempted on
	// purpose) vs. canceled (user/system stopped it).
	SkipJobRun(ctx context.Context, id pgtype.UUID) (SkipJobRunRow, error)
	// Returns the tail (up to $2 lines) of a job's logs, oldest-first within the
	// returned window, so the UI can append-only render.
	TailLogLinesByJob(ctx context.Context, arg TailLogLinesByJobParams) ([]TailLogLinesByJobRow, error)
	// Cheap idempotent update; called at most once per request via a
	// debounce in the middleware so we don't rewrite the row on every
	// 2s dashboard poll.
	TouchUserSession(ctx context.Context, id []byte) error
	// Called from the gRPC heartbeat handler so the reaper can tell which agents
	// are still alive. Tiny write per heartbeat (default cadence 30s).
	UpdateAgentLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateAgentOnRegister(ctx context.Context, arg UpdateAgentOnRegisterParams) error
	// Dedicated password-only write. Used when an admin changes their
	// own password from /settings/account — we never want to let the
	// admin also flip their role through that surface.
	UpdateLocalUserPassword(ctx context.Context, arg UpdateLocalUserPasswordParams) error
	// Stamp the last successful config sync. Called after a drift re-apply so
	// operators can see whether the live config tracks HEAD.
	UpdateScmSourceSynced(ctx context.Context, arg UpdateScmSourceSyncedParams) error
	// Rotation path. Takes the newly sealed ciphertext and bumps
	// updated_at. Intended for POST /api/v1/projects/{slug}/scm-sources
	// /{id}/rotate-webhook-secret.
	UpdateScmSourceWebhookSecret(ctx context.Context, arg UpdateScmSourceWebhookSecretParams) error
	// Flip a user's role. The CHECK constraint on the column enforces
	// the enum; an admin calling this with a typo'd value gets a clean
	// error from Postgres instead of a silent wrong-role write.
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	// ON CONFLICT (name) DO UPDATE bumps kind + display + id/secret
	// + issuer + api base + enabled. We never update created_at.
	UpsertAuthProvider(ctx context.Context, arg UpsertAuthProviderParams) (AuthProvider, error)
	// Records a fire time for a cron material. The ticker calls this
	// right after dispatching a run so a crashed server doesn't re-
	// fire the same tick when it comes back.
	UpsertCronFired(ctx context.Context, arg UpsertCronFiredParams) error
	// Called right after CreateCheckRun on GitHub responds; caller may
	// already have an entry from a previous retry so we upsert rather
	// than insert. updated_at bumps so we can spot stale rows later.
	UpsertGithubCheckRun(ctx context.Context, arg UpsertGithubCheckRunParams) error
	// Global scope: project_id = NULL, shadowed by a same-name project
	// secret at resolution time. Targets the partial UNIQUE index
	// secrets_global_name_idx — Postgres can't infer partial indexes
	// from ON CONFLICT (name) alone, so we spell out the predicate.
	UpsertGlobalSecret(ctx context.Context, arg UpsertGlobalSecretParams) (UpsertGlobalSecretRow, error)
	// Create/update a local account. Called from the CLI and the
	// admin self-service change-password endpoint. external_id is
	// the email so the (provider, external_id) unique key covers us.
	UpsertLocalUser(ctx context.Context, arg UpsertLocalUserParams) (UpsertLocalUserRow, error)
	UpsertMaterial(ctx context.Context, arg UpsertMaterialParams) (UpsertMaterialRow, error)
	UpsertPipeline(ctx context.Context, arg UpsertPipelineParams) (UpsertPipelineRow, error)
	// config_path defaults to '.gocdnext' at the SQL level. Apply
	// callers that don't set it (legacy path, drift re-apply) get
	// that default naturally via COALESCE on the column-side default.
	// Callers that DO set it override via ON CONFLICT.
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (UpsertProjectRow, error)
	// Bind a project to its SCM source. updated_at only bumps when
	// something meaningful changes, so idempotent re-applies don't
	// spam the timeline. webhook_secret is BYTEA ciphertext (sealed
	// in the store layer via crypto.Cipher); sending NULL means
	// "keep the existing ciphertext" so rotation is explicit — a
	// Plain upsert without a secret doesn't wipe an existing one.
	UpsertScmSource(ctx context.Context, arg UpsertScmSourceParams) (UpsertScmSourceRow, error)
	// Upserts a (project_id, name) -> value_enc pair. updated_at always bumps on
	// update because the ciphertext changes (random nonce) even for identical
	// plaintext, making a "was this changed" diff unreliable; we bump
	// unconditionally on write.
	//
	// Targets the partial UNIQUE index secrets_project_name_idx (rows
	// where project_id IS NOT NULL). The global twin lives in
	// UpsertGlobalSecret below.
	UpsertSecret(ctx context.Context, arg UpsertSecretParams) (UpsertSecretRow, error)
	// Either inserts a fresh row (new login) or bumps the profile
	// fields we pull from the IdP every time. Role is intentionally
	// NOT overwritten on conflict — it's admin-assigned and must not
	// revert to 'user' just because the IdP doesn't carry it.
	UpsertUserByProvider(ctx context.Context, arg UpsertUserByProviderParams) (UpsertUserByProviderRow, error)
	// Writes the full preferences document for a user. Upsert so the
	// caller doesn't have to branch on "first save vs. update" — the
	// web action uses a PUT-style full-document replace, not a
	// field-level merge, so this is the only write the domain needs.
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UpsertUserPreferencesRow, error)
	// ON CONFLICT (name) DO UPDATE refreshes every field EXCEPT
	// private_key + webhook_secret when the caller passes NULL.
	// The handler interprets an empty string from the dialog as
	// "keep existing ciphertext", mirroring auth_providers.
	UpsertVCSIntegration(ctx context.Context, arg UpsertVCSIntegrationParams) (VcsIntegration, error)
	// Median wait time per upstream→downstream edge in the project's
	// VSM. Wait = downstream.started_at − upstream.finished_at, over
	// terminal-or-dispatched runs where cause='upstream' and the
	// cause_detail's upstream_run_id resolves to a real upstream run.
	// Grouping by (from_pipeline_id, to_pipeline_id) so multiple edges
	// from the same upstream to different downstreams each get their
	// own median — the VSM graph labels arrows with these numbers.
	VSMEdgeTimingByProjectSlug(ctx context.Context, arg VSMEdgeTimingByProjectSlugParams) ([]VSMEdgeTimingByProjectSlugRow, error)
}

var _ Querier = (*Queries)(nil)
