// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Idempotent on (group_id, user_id) — re-adding is a no-op, not
	// an error, so the UI's "add if not present" flow doesn't need
	// a pre-check query.
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	// Ownership probe for ServiceLifecycle ingest. Returns true when
	// the calling agent has (now OR ever) a job_run under this run —
	// the natural binding for "this agent is part of the run, so
	// whatever it says about service lifecycle is credible".
	//
	// Used as the gate on `starting`/`ready`/`failed`. For `stopped`,
	// the handler additionally accepts any agent because cleanup is
	// BROADCAST to k8s-capable agents that may never have owned a
	// job (the whole point of the broadcast model).
	AgentOwnedJobInRun(ctx context.Context, arg AgentOwnedJobInRunParams) (bool, error)
	// Moves a queued, unassigned job to running and records the agent. The status
	// predicate prevents a race where two scheduler ticks pick the same job.
	//
	// `attempt` flows back so the scheduler can RecordAssignment on the
	// target session — the result handler then validates the (agent,
	// attempt) snapshot to refuse stale results from revoked sessions
	// whose job got redispatched to the same agent_id on a higher
	// attempt. See sessions.Session.RecordAssignment.
	AssignJob(ctx context.Context, arg AssignJobParams) (AssignJobRow, error)
	// Flips a run to 'canceled' only if it was still active. Idempotent:
	// a second call on a terminal run returns no rows so the handler
	// can answer 409. Returns the row id so the caller can tell the
	// update happened.
	//
	// queue_reason is cleared in the same UPDATE so a canceled-while-
	// queued run doesn't carry a "waiting on #N" message into the
	// runs list. Doing it in this UPDATE (vs a follow-up
	// ClearRunQueueReason call) keeps the cancel atomic and saves a
	// round-trip.
	CancelActiveRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Flips a single job_run to 'canceled' ONLY when it's still queued.
	// `running` jobs go through the agent's gRPC CancelJob → JobResult
	// path so the audit trail records the actual stop time. Returns the
	// row id so the caller can tell whether the update happened (the
	// predicate could miss in a race with the scheduler dispatch path).
	//
	// We DON'T pre-fill exit_code or error here — those columns are
	// agent-driven on running cancels, and for a queued cancel the
	// absence of an exit_code is the honest signal ("never started").
	CancelQueuedJobRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Pending approval gates in a failed run also get canceled so a
	// rejected deploy doesn't leave a "ready to approve" ghost sitting
	// in the UI with no path forward. Reject is the intended decision
	// path; cancel here only fires on upstream stage failure. Jobs
	// inside the synthetic _notifications stage are preserved so
	// `on: failure` notifications still fire.
	CancelQueuedJobsInRun(ctx context.Context, runID pgtype.UUID) error
	// When a user stage fails we stop dispatching the rest of the run's user
	// stages. Running work stays untouched; the agent will still report its
	// outcome. The synthetic _notifications stage is preserved on purpose —
	// a pipeline that declared `on: failure` notifications still needs them
	// to fire. The scheduler filters the notification jobs by `on:` when
	// dispatching so only the matching ones actually run.
	CancelQueuedStagesInRun(ctx context.Context, runID pgtype.UUID) error
	// Atomically marks a bounded batch of artefacts as 'deleting' and
	// returns their storage keys so the sweeper can call Store.Delete and
	// then remove the DB row.
	//
	// Three populations get claimed:
	//   1) Freshly-expired rows: status='ready' AND expires_at < now() AND
	//      not pinned. Standard TTL sweep.
	//   2) Rows left in 'deleting' for longer than the grace window — the
	//      previous sweeper crashed between "marked deleting" and "storage
	//      delete + row removed". We pick those up and retry idempotently.
	//   3) Orphan pending rows older than the grace window — RequestArtifactUpload
	//      inserted a pending row, but the agent never confirmed (gRPC drop
	//      after server commit + before client got the ticket, SignedPutURL
	//      error mid-loop, agent process died between PUT and JobResult, or
	//      a duplicate path in the request that fell out of the dedupe).
	//      Without this branch, the partial-unique-index 00035 would refuse
	//      future inserts on the same (job_run_id, path) FOREVER. The grace
	//      window doubles as "wait long enough for a legitimate upload to
	//      finish" — the typical PUT completes well under a minute, so the
	//      sweeper's default (e.g. 30 min) leaves a comfortable margin.
	//
	// FOR UPDATE SKIP LOCKED makes this safe to run from multiple
	// schedulers/sweepers at once; each gets a disjoint batch.
	ClaimArtifactsForSweep(ctx context.Context, arg ClaimArtifactsForSweepParams) ([]ClaimArtifactsForSweepRow, error)
	// Clears queue_reason. Called by the scheduler when a run transitions
	// to running (predecessor finished, run is dispatchable). Also called
	// by terminal-transition paths so a canceled-while-queued run doesn't
	// carry a stale "waiting on #N" message in the runs list.
	ClearRunQueueReason(ctx context.Context, id pgtype.UUID) error
	// Flips a queued or running job to its terminal state, IF the caller's
	// expected agent_id snapshot still matches what's on the row.
	// Idempotent: matches only non-terminal rows.
	//
	// Accepting both 'queued' AND 'running' covers two distinct callers:
	//   - handleJobResult (agent gRPC): row was 'running' when AssignJob
	//     dispatched it. Passes the calling session's agent UUID as
	//     expected_agent_id. A stale result from a revoked agent session
	//     whose job was reclaimed (agent_id NULL'd) or redispatched
	//     (different agent) will NOT match — `IS NOT DISTINCT FROM` is
	//     load-bearing here, both on the NULL-NULL match for the
	//     scheduler path AND on the NULL-mismatch reject after reclaim.
	//   - scheduler.failJobWithError (dispatch-time fail): row is still
	//     'queued' (never got AssignJob'd) with agent_id=NULL. Passes
	//     NULL for expected_agent_id; the IS NOT DISTINCT FROM matches.
	//
	// Returns stage/run ids so the caller can cascade. ErrNoRows when
	// the predicate doesn't match — caller treats as "another path
	// handled this row already" and drops the message silently.
	// outputs is set on the SAME row update as status so a successful
	// CompleteJob atomically publishes the structured k/v outputs the
	// agent shipped (issue #10). Downstream jobs gated on this row's
	// needs: read both columns in one query, so the substitution path
	// sees the final state — no read-after-write race against
	// dispatch. NULL caller param falls back to '{}' so the legacy
	// non-output completion path stays a one-line change at the call
	// site.
	CompleteJobRun(ctx context.Context, arg CompleteJobRunParams) (CompleteJobRunRow, error)
	CompleteRun(ctx context.Context, arg CompleteRunParams) error
	CompleteStageRun(ctx context.Context, arg CompleteStageRunParams) error
	// Single-use: delete as we read. Returning nothing = no such state
	// (or it expired and the sweeper got to it first).
	ConsumeAuthState(ctx context.Context, stateHash []byte) (ConsumeAuthStateRow, error)
	// Matching total for the same filter set ListAuditEvents reads.
	// Surfaces the absolute count so the UI can render a
	// "showing X–Y of Z" header + Prev/Next bounds without a second
	// guess-and-check fetch.
	CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error)
	// Quorum check: how many approved votes (excluding rejects)
	// has this gate accumulated?
	CountJobRunApprovals(ctx context.Context, jobRunID pgtype.UUID) (int32, error)
	// Drives the "show local login form" decision on the login page:
	// no rows = zero local admins, the form stays hidden so the page
	// doesn't advertise a dead code path.
	CountLocalUsers(ctx context.Context) (int64, error)
	// Total log line count for a job_run. Powers the "(N lines omitted)"
	// divider between head and tail in the UI: omitted = total - head -
	// tail, clamped to >= 0 (when head+tail overlap or exceed total,
	// callers dedupe and zero the omitted count). Cheap row count
	// against the same (job_run_id, seq) index TailLogLinesByJob hits.
	CountLogLinesByJob(ctx context.Context, jobRunID pgtype.UUID) (int64, error)
	CountRunsByPipeline(ctx context.Context, pipelineID pgtype.UUID) (int64, error)
	// Paired with ListRunsGlobal so /runs can render "N of M" with the
	// same filter args. Returned as bigint to fit any table; UI only
	// needs int32 but this avoids cast noise.
	CountRunsGlobal(ctx context.Context, arg CountRunsGlobalParams) (int64, error)
	// One aggregate row per job_run covering all statuses — drives
	// the pill on each job card ("42 passed · 1 failed") without
	// pulling the full case list. Empty when the job didn't produce
	// reports.
	CountTestResultsByJobRun(ctx context.Context, jobRunIds []pgtype.UUID) ([]CountTestResultsByJobRunRow, error)
	// Pair for ListWebhookDeliveries so the UI can render "N of M".
	CountWebhookDeliveries(ctx context.Context, arg CountWebhookDeliveriesParams) (int64, error)
	// Median run duration in seconds across the last 7 days. NULL when
	// no finished runs.
	DashboardP50DurationSec7d(ctx context.Context) (float64, error)
	// Active backlog: every queued run across the system, plus queued
	// + running job_runs (the scheduler's work left to do).
	DashboardQueueDepth(ctx context.Context) (DashboardQueueDepthRow, error)
	// Count of runs created today (server-local day boundary via
	// now()::date).
	DashboardRunsToday(ctx context.Context) (int64, error)
	// Terminal runs in the last 7 days, broken down by outcome. The
	// caller computes rate = success / (success + failure). Returns
	// 0 when no terminal runs in the window.
	DashboardSuccessRate7d(ctx context.Context) (DashboardSuccessRate7dRow, error)
	DeleteAuthProvider(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredAuthStates(ctx context.Context) error
	DeleteExpiredUserSessions(ctx context.Context) error
	DeleteGlobalSecretByName(ctx context.Context, name string) (int64, error)
	DeleteGroup(ctx context.Context, id pgtype.UUID) error
	// Called after a successful reclaim so the retry starts with a clean log
	// window. Loses the old attempt's output — acceptable MVP trade for not
	// growing the schema to carry per-attempt log namespacing.
	DeleteLogLinesByJob(ctx context.Context, jobRunID pgtype.UUID) error
	DeleteMaterial(ctx context.Context, id pgtype.UUID) error
	DeletePipeline(ctx context.Context, id pgtype.UUID) error
	// Removes a setting; the boot path then falls back to env config.
	DeletePlatformSetting(ctx context.Context, key string) error
	// Returns the number of project rows deleted (0 or 1). ON DELETE
	// CASCADE on every foreign key that points at projects carries
	// the children (pipelines → materials → runs → artifacts, secrets,
	// scm_sources, etc.), so this single statement is enough.
	DeleteProjectBySlug(ctx context.Context, slug string) (int64, error)
	DeleteProjectCron(ctx context.Context, id pgtype.UUID) error
	// Caller MUST check no pipeline definition references this profile
	// before issuing the delete; the scheduler resolves profiles by
	// name at dispatch and a missing name fails the run.
	DeleteRunnerProfile(ctx context.Context, id pgtype.UUID) error
	DeleteSCMCredential(ctx context.Context, id pgtype.UUID) error
	DeleteSecretByName(ctx context.Context, arg DeleteSecretByNameParams) (int64, error)
	// ON DELETE CASCADE on api_tokens cleans up the token rows
	// automatically.
	DeleteServiceAccount(ctx context.Context, id pgtype.UUID) error
	// Called before an agent retry re-ingests a rerun's results, so
	// the UI doesn't show a mix of old and new outcomes. The FK's
	// ON DELETE CASCADE handles the job_run → test_results side;
	// this one targets the "same job_run_id, later agent attempt"
	// case where the row survives but its results shouldn't.
	DeleteTestResultsByJobRun(ctx context.Context, jobRunID pgtype.UUID) error
	DeleteUserSession(ctx context.Context, id []byte) error
	DeleteUserSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	DeleteVCSIntegration(ctx context.Context, id pgtype.UUID) error
	// Keep-last policy: per pipeline, rank the runs that produced
	// non-deleted artefacts by recency (run.created_at DESC); any run
	// beyond position N has ALL its non-pinned artefacts stamped with
	// expires_at = NOW(). The next TTL sweep picks them up. Pinned rows
	// are exempt; pinned runs don't consume a "slot" — they live forever
	// orthogonally to the N budget.
	ExpireArtifactsBeyondKeepLast(ctx context.Context, dollar_1 int32) (int64, error)
	ExpireOldestGloballyByExcess(ctx context.Context, dollar_1 int64) (int64, error)
	// Stamp expires_at = NOW() on the oldest non-pinned rows in a project,
	// stopping as soon as the demoted bytes cover `excess`. Uses a window
	// function so the cut-off is computed against the cumulative-up-to-
	// but-not-including-this-row (so we always demote enough, never
	// less).
	ExpireOldestInProjectByExcess(ctx context.Context, arg ExpireOldestInProjectByExcessParams) (int64, error)
	// Marks a still-queued job as `failed` (NOT `skipped`) when the
	// scheduler's needs-satisfaction gate determines it can never
	// run: an upstream is in a non-success terminal state (failed /
	// canceled / skipped / missing-from-run). `failed` is the right
	// semantic for the cascade: GetStageProgress / GetRunUserStageOutcome
	// only count `failed` toward stage + run failure aggregates, and
	// a job we EXPECTED to run that didn't IS a failure from the
	// operator's perspective (different from a notification skip,
	// which is "by design").
	//
	// The `error` column carries the human-readable reason
	// ("needs unmet: types-generate: failed") so the UI / API
	// distinguishes a true agent-side failure from a needs-cascade
	// failure. Operator grep is the audit surface.
	//
	// Was `SkipJobRunWithReason` setting status='skipped'; renamed
	// + status changed to plug a silent-green hole: a snapshot
	// drift (parser allowed it then, schema changed, manual DB
	// poke) where `needs:` references a non-existent job would
	// otherwise let the run finalize as success despite a job that
	// never ran.
	FailJobRunWithReason(ctx context.Context, arg FailJobRunWithReasonParams) (FailJobRunWithReasonRow, error)
	// Cap-exceeded path for the reaper / fence: flips a still-running
	// row to 'failed' with a fixed error message, IF the snapshot the
	// caller saw still matches. Snapshot validation has the same role
	// as in ReclaimJobForRetry — a concurrent rerun or redispatch could
	// have moved this row to a healthy state on another agent, and
	// failing it on our stale read would corrupt the run.
	//
	// We don't go through CompleteJobRun because that UPDATE is
	// intentionally permissive (accepts both queued+running so a
	// dispatch-time fail-from-queued path works), and adding the
	// snapshot check there would ripple across every result-handler
	// call site. The caller (FailJobIfStale in store/sweeper.go) wraps
	// this query + the existing cascadeAfterJobCompletion helper in
	// one transaction so the stage/run promotion stays identical to
	// the normal terminal path.
	//
	// Return columns mirror CompleteJobRun so the Go caller can
	// reuse the same JobCompletion struct + cascade helper.
	FailStaleJobAtMax(ctx context.Context, arg FailStaleJobAtMaxParams) (FailStaleJobAtMaxRow, error)
	FindAgentByName(ctx context.Context, name string) (Agent, error)
	// Same shape as ListAgentsWithRunning but for one row — reused by
	// the /agents/{id} page. Returns ErrNoRows when the UUID is not
	// an existing agent.
	FindAgentWithRunning(ctx context.Context, id pgtype.UUID) (FindAgentWithRunningRow, error)
	// For a completed stage on an upstream pipeline, find every "upstream"
	// material in OTHER pipelines of the same project that points at it. The
	// status filter respects `materials.config.status` (default 'success') so a
	// user can gate downstream on specific outcomes.
	FindDownstreamUpstreamMaterials(ctx context.Context, arg FindDownstreamUpstreamMaterialsParams) ([]FindDownstreamUpstreamMaterialsRow, error)
	// N rows per fingerprint by design: materials are uniqued on
	// (pipeline_id, fingerprint), so several pipelines that watch the
	// same (repo, branch) legitimately share a hash. ORDER BY pipeline_id
	// makes the dispatch order deterministic across replays / reaper
	// requeues / multi-replica races. An earlier :one LIMIT 1 form
	// silently kept only the first row, so only ONE pipeline fan-out
	// happened on every push and "which one" was non-deterministic.
	FindMaterialsByFingerprint(ctx context.Context, fingerprint string) ([]Material, error)
	FindProjectBySlug(ctx context.Context, slug string) (FindProjectBySlugRow, error)
	// Idempotency check for fanout: if we already created a downstream run for
	// this (pipeline, upstream_run_id) pair, skip.
	FindRunByUpstream(ctx context.Context, arg FindRunByUpstreamParams) (FindRunByUpstreamRow, error)
	// Rotation + UI detail views go project-slug → scm_source without
	// the caller having to resolve the project id first.
	FindScmSourceBySlug(ctx context.Context, slug string) (FindScmSourceBySlugRow, error)
	// Read path used by webhook drift detection and future UI
	// listings. Does NOT return webhook_secret — that's handled by
	// GetScmSourceWebhookSecret to keep ciphertext out of the general
	// read path.
	FindScmSourceByURL(ctx context.Context, url string) (FindScmSourceByURLRow, error)
	// Hot path: the bearer middleware probes this on every request.
	// Returns NOT FOUND when revoked or expired so the middleware
	// doesn't have to special-case those.
	GetAPITokenByHash(ctx context.Context, hash string) (GetAPITokenByHashRow, error)
	// Same, scoped to a service account (admin path).
	GetAPITokenForSAOwner(ctx context.Context, arg GetAPITokenForSAOwnerParams) (GetAPITokenForSAOwnerRow, error)
	// Used by handlers that need to verify "this token belongs to this
	// user before letting them revoke it" — not just any token.
	GetAPITokenForUserOwner(ctx context.Context, arg GetAPITokenForUserOwnerParams) (GetAPITokenForUserOwnerRow, error)
	// Single-row lookup for the JobResult confirmation path. Returns
	// ErrNoRows if the agent invented a key or the row was swept.
	GetArtifactByStorageKey(ctx context.Context, storageKey string) (GetArtifactByStorageKeyRow, error)
	GetAuthProviderByID(ctx context.Context, id pgtype.UUID) (AuthProvider, error)
	// Reporter needs owner/repo/check_run_id to patch a check when the
	// run finishes. Returns ErrNoRows when the run didn't produce a
	// check (most common path: no App installed, or feature disabled).
	GetGithubCheckRun(ctx context.Context, runID pgtype.UUID) (GithubCheckRun, error)
	// Resolver fallback: after GetSecretValuesByProject, names still
	// missing are looked up as globals. Kept as a separate call so
	// the resolver can short-circuit when every name was already
	// covered at project scope.
	GetGlobalSecretValues(ctx context.Context, dollar_1 []string) ([]GetGlobalSecretValuesRow, error)
	GetGroup(ctx context.Context, id pgtype.UUID) (Group, error)
	// Used on approve: gate carries group NAMES (not ids) so renames
	// propagate cleanly. Lookup translates name → id → members.
	GetGroupByName(ctx context.Context, name string) (Group, error)
	// Used by the reaper to disambiguate "at max attempts" from "already
	// handled" when ReclaimJobForRetry returned no rows.
	GetJobAttempt(ctx context.Context, id pgtype.UUID) (GetJobAttemptRow, error)
	// Returns the archive URI + timestamp for one job_run. NULL URI =
	// not archived; reads should fall through to log_lines.
	GetJobLogArchive(ctx context.Context, id pgtype.UUID) (GetJobLogArchiveRow, error)
	// Thin row used by the job-scoped cancel handler. Returns the
	// structural pointers cancel needs (run_id, stage_run_id) plus the
	// decision inputs (status, agent_id) — `running` jobs are signaled
	// via gRPC (handler dispatches CancelJob), `queued` jobs flip
	// directly here and feed cascadeAfterJobCompletion. Distinguishes
	// "not found" from "already terminal" via pgx.ErrNoRows vs the
	// status check in the caller.
	//
	// `FOR UPDATE` serialises against the scheduler's
	// ClaimJobForDispatch (which writes status='running' + agent_id
	// inside its own tx). Without the lock, a job_run that's queued
	// when we SELECT can be dispatched by the time CancelQueuedJobRun
	// UPDATEs — the UPDATE misses the predicate, we return 409
	// "already terminal" while the job is actually running. With the
	// lock, exactly one of (cancel commits / dispatch commits) wins;
	// the loser sees the post-commit state and routes correctly.
	GetJobRunForCancel(ctx context.Context, id pgtype.UUID) (GetJobRunForCancelRow, error)
	// Resolves pipeline_id + project_id + agent_id for a (job_run_id,
	// run_id) pair. Used by the RequestArtifactUpload handler to authorise
	// + derive the FKs. Returns ErrNoRows if job_run_id doesn't belong to
	// the claimed run_id. agent_id is NULL when the job hasn't been
	// dispatched yet (shouldn't happen on this code path but the column
	// nullability forces us to handle it).
	GetJobRunParents(ctx context.Context, arg GetJobRunParentsParams) (GetJobRunParentsRow, error)
	// Most recent modification across any material attached to a
	// pipeline. Powers "trigger latest" for manual runs. Ordered by
	// detected_at so the newest webhook delivery wins even when the
	// committer timestamp is older (rebases, fast-forwards of older
	// commits).
	GetLatestModificationForPipeline(ctx context.Context, pipelineID pgtype.UUID) (GetLatestModificationForPipelineRow, error)
	// Fetches the row we need to bcrypt-compare on a login POST.
	// Filtering by provider keeps an OIDC user with the same email
	// from accidentally answering to a password form.
	GetLocalUserForLogin(ctx context.Context, email string) (User, error)
	GetModificationByKey(ctx context.Context, arg GetModificationByKeyParams) (Modification, error)
	// Returns the pipeline's stored YAML snapshot AND the owning
	// project's notifications list — at run-create time the synth
	// stage needs both (pipeline's own notifications or, when
	// absent, the project-level inherited set). One round-trip is
	// cheaper than two for what's already the hottest path on
	// webhook-heavy workloads.
	GetPipelineDefinition(ctx context.Context, id pgtype.UUID) (GetPipelineDefinitionRow, error)
	// Single-row lookup by string key. Returns the full envelope so
	// the caller can decrypt the secret half locally with the cipher
	// (no plaintext crosses the store boundary unless the caller
	// explicitly decrypts).
	GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error)
	// Surfaces the per-project log_archive_enabled override (NULL =
	// inherit global). Used by the archiver when resolving effective
	// policy for a job.
	GetProjectArchiveFlag(ctx context.Context, id pgtype.UUID) (*bool, error)
	// Surfaces the per-project log_archive_enabled override by slug —
	// what the project-settings UI reads when populating the toggle.
	GetProjectArchiveFlagBySlug(ctx context.Context, slug string) (*bool, error)
	// Joins runs -> pipelines -> projects so the archive hook can
	// resolve a job_run's project flag in one query.
	GetProjectArchiveFlagForRun(ctx context.Context, id pgtype.UUID) (*bool, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (GetProjectByIDRow, error)
	GetProjectBySlug(ctx context.Context, slug string) (GetProjectBySlugRow, error)
	GetProjectCron(ctx context.Context, id pgtype.UUID) (ProjectCron, error)
	// Aggregated before the cascading delete so the caller can surface
	// "deleted N pipelines, M runs, K secrets" without probing each
	// table after the fact (by then the rows are gone). Kept as a
	// single round-trip so the delete flow stays two calls, not six.
	GetProjectDeletionCounts(ctx context.Context, slug string) (GetProjectDeletionCountsRow, error)
	// Returns the project-level notifications JSONB array. The run-
	// create path consults this when the pipeline's own `notifications:`
	// block is absent (pipeline nil means "inherit"; pipeline empty
	// list means "explicit opt-out" and we skip this entirely).
	GetProjectNotifications(ctx context.Context, id pgtype.UUID) ([]byte, error)
	// Thin row used by cancel/rerun handlers to check status + find the
	// pipeline + revisions without pulling the whole detail query.
	GetRunForAction(ctx context.Context, id pgtype.UUID) (GetRunForActionRow, error)
	// project_notifications tags along so the dispatcher can resolve
	// synth notification jobs that inherited their spec from the
	// project (pipeline didn't declare `notifications:`). Single
	// round-trip keeps the dispatch hot path tight.
	//
	// r.cause + r.cause_detail come along because scheduler/civars.go
	// materialises CI_CAUSE + CI_PULL_REQUEST_* env vars from them.
	// Adding the columns here costs one extra row width on a hot path
	// query that already loads the JSONB definition — negligible vs.
	// the round trip we'd otherwise need to fetch them separately.
	GetRunForDispatch(ctx context.Context, id pgtype.UUID) (GetRunForDispatchRow, error)
	GetRunProgress(ctx context.Context, runID pgtype.UUID) (GetRunProgressRow, error)
	// For a downstream run, extracts upstream_run_id + upstream pipeline
	// name from cause_detail JSON. Empty string / null UUID when this run
	// was NOT triggered by an upstream material (cause is 'webhook' /
	// 'manual'). Caller checks upstream_run_id.Valid.
	GetRunUpstreamContext(ctx context.Context, id pgtype.UUID) (GetRunUpstreamContextRow, error)
	// Aggregate job outcomes across USER stages only (everything except
	// the synthetic _notifications). The cascade uses this to decide the
	// final run.status when finalizing — notification success/failure
	// must not flip a user run from success to failed or vice versa.
	GetRunUserStageOutcome(ctx context.Context, runID pgtype.UUID) (GetRunUserStageOutcomeRow, error)
	// pl.definition is returned so the read path can decode the
	// notifications array and stamp on/uses onto synth job rows
	// without a second round-trip. Adds one JSONB column to the
	// response but avoids a per-run "did this pipeline have
	// notifications?" lookup.
	GetRunWithPipeline(ctx context.Context, id pgtype.UUID) (GetRunWithPipelineRow, error)
	GetRunnerProfile(ctx context.Context, id pgtype.UUID) (RunnerProfile, error)
	// Pipeline apply + scheduler dispatch both look up by name (the
	// stable identifier in YAML), not by id, so renames are deliberate
	// breaking changes — admins know what they're doing.
	GetRunnerProfileByName(ctx context.Context, name string) (RunnerProfile, error)
	// Resolver hot path. Nil rows silently fall through to
	// scm_source.auth_ref at the caller.
	GetSCMCredentialByProviderHost(ctx context.Context, arg GetSCMCredentialByProviderHostParams) (ScmCredential, error)
	GetScmSourceByProject(ctx context.Context, projectID pgtype.UUID) (GetScmSourceByProjectRow, error)
	// Webhook-handler path: pulls the sealed secret + the scm_source
	// id for a given clone_url so HandleGitHub can verify HMAC with
	// the right per-repo key. Returns an empty BYTEA when the row
	// has no secret configured yet (the caller then answers 401 —
	// "no webhook secret registered for this repo").
	GetScmSourceWebhookSecretByURL(ctx context.Context, url string) (GetScmSourceWebhookSecretByURLRow, error)
	// Used by the scheduler when a job declares `secrets: [FOO, BAR]`. Returns
	// the encrypted blobs; the caller decrypts and injects as env vars.
	GetSecretValuesByProject(ctx context.Context, arg GetSecretValuesByProjectParams) ([]GetSecretValuesByProjectRow, error)
	GetServiceAccountByID(ctx context.Context, id pgtype.UUID) (ServiceAccount, error)
	// Counts jobs still working vs already-failed within a stage — the numbers
	// the caller uses to decide whether to promote the stage. `awaiting_approval`
	// is unfinished too: the gate hasn't decided yet, so the stage can't close.
	GetStageProgress(ctx context.Context, stageRunID pgtype.UUID) (GetStageProgressRow, error)
	// Everything the fanout trigger needs to identify this stage's position
	// (pipeline + run + counter + revisions) without multiple round-trips.
	GetStageSummary(ctx context.Context, id pgtype.UUID) (GetStageSummaryRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// Returns the stored preferences blob for a user. Callers treat
	// the "no row" case as "empty preferences" (pgx.ErrNoRows); this
	// query stays minimal so the shape follows the JSONB document
	// rather than forcing a struct on every new key.
	GetUserPreferences(ctx context.Context, userID pgtype.UUID) (GetUserPreferencesRow, error)
	// Returns the session + its user row. Expired rows are filtered in
	// the query so a single round-trip tells the handler "yes/no".
	GetUserSession(ctx context.Context, id []byte) (GetUserSessionRow, error)
	GetVCSIntegrationByID(ctx context.Context, id pgtype.UUID) (VcsIntegration, error)
	// Expands a row with its headers + payload JSON for the drawer
	// view. Kept in a separate query so the list shot stays tiny
	// (payloads can be 100+ KB).
	GetWebhookDelivery(ctx context.Context, id int64) (WebhookDelivery, error)
	// Total live artefact bytes. Returns 0 when the artifacts table is
	// empty. Used for the global hard cap.
	GlobalArtifactUsage(ctx context.Context) (int64, error)
	// Returns the head (first $2 lines) of a job's logs in seq order.
	// Used together with TailLogLinesByJob to render the run detail's
	// log view as "first N + last M lines" — the verbose middle of
	// long jobs (Gradle test execution, kafka chatter) is rarely what
	// operators need first; the START (Gradle daemon setup, dependency
	// resolution from Nexus, classpath assembly) and the END (failure
	// + stack trace) are. Pre-v0.14.7 the cap-on-tail meant a 23k-line
	// job hid the entire startup; `kubectl logs` was the workaround.
	HeadLogLinesByJob(ctx context.Context, arg HeadLogLinesByJobParams) ([]HeadLogLinesByJobRow, error)
	// Stores a freshly-minted token. Caller passes the SHA-256 hex
	// digest in `hash`; the plaintext is shown to the user once at
	// creation time and never persisted. Either user_id OR
	// service_account_id is set (XOR enforced by the table check).
	InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) (InsertAPITokenRow, error)
	InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error)
	// Write-only hot path — every RBAC'd mutation fires one of these.
	// at is stamped by the DB so clock skew on multi-replica setups
	// doesn't re-order events inside a single tick.
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertAuthState(ctx context.Context, arg InsertAuthStateParams) error
	InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error)
	InsertJobRun(ctx context.Context, arg InsertJobRunParams) (InsertJobRunRow, error)
	// Records one vote on a gate. Unique (job_run_id, user_id) —
	// double-voting is a conflict, not a silent dup. Returns
	// (id, created) so the caller sees whether the vote actually
	// landed or was a re-post from the same user.
	InsertJobRunApproval(ctx context.Context, arg InsertJobRunApprovalParams) (InsertJobRunApprovalRow, error)
	// Strict create — fails with a unique-violation when the email
	// already belongs to a local account. Used by the admin
	// "New user" flow where silently re-writing someone else's
	// password would be a foot-gun. Callers map 23505 → 409.
	InsertLocalUser(ctx context.Context, arg InsertLocalUserParams) (InsertLocalUserRow, error)
	// Agents send log lines with a per-(job_run_id) monotonic seq plus the
	// timestamp the line was emitted on the runner. The PK is the triple
	// (job_run_id, seq, at) — partitioning the table by `at` ruled out a
	// pure (job_run_id, seq) UNIQUE — so retries dedupe on the same triple.
	// The agent caches the original `at` on every buffered line, which
	// makes the triple a tighter dedup key than the old pair anyway: a
	// reissued line keeps its first-emission timestamp.
	InsertLogLine(ctx context.Context, arg InsertLogLineParams) error
	InsertMaterial(ctx context.Context, arg InsertMaterialParams) (Material, error)
	InsertModification(ctx context.Context, arg InsertModificationParams) (Modification, error)
	// Inserts a row in `pending` status ahead of the agent's upload. The
	// storage_key is generated by the caller (UUID-based) so the row's id and
	// the backend's object key are decoupled — makes it safe to retry without
	// ending up with orphan objects keyed off a stale PK.
	InsertPendingArtifact(ctx context.Context, arg InsertPendingArtifactParams) (InsertPendingArtifactRow, error)
	InsertProjectCron(ctx context.Context, arg InsertProjectCronParams) (ProjectCron, error)
	// has_services is a snapshot of `pipeline.Services` non-emptiness
	// (migration 00036). Stamped here so the run-terminal cleanup
	// cascade can decide whether to broadcast CleanupRunServices
	// without re-reading the (possibly-drifted) current pipeline
	// definition. The Go layer (store.insertRunSkeleton) computes the
	// value from the SAME `domain.Pipeline` it just used to materialise
	// stages + jobs — without this, a concurrent ApplyProject between
	// the Go decode and a re-read inside SQL could give us mismatched
	// snapshots under READ COMMITTED.
	InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error)
	InsertRunnerProfile(ctx context.Context, arg InsertRunnerProfileParams) (RunnerProfile, error)
	InsertServiceAccount(ctx context.Context, arg InsertServiceAccountParams) (ServiceAccount, error)
	InsertStageRun(ctx context.Context, arg InsertStageRunParams) (InsertStageRunRow, error)
	// One INSERT per case. The agent batches N cases into a single
	// gRPC message; the server handler opens a tx and calls this N
	// times. Simpler than a COPY FROM for a workload that caps at
	// a few thousand cases per run.
	InsertTestResult(ctx context.Context, arg InsertTestResultParams) error
	InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error
	// Append-only audit row for every HTTP call that lands on
	// /api/webhooks/*. Rows outlive the request so the admin page can
	// show signature-rejected and drift-only deliveries too, not just
	// the ones that produced a modification.
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (InsertWebhookDeliveryRow, error)
	// Per-pipeline latest run with the triggering modification's
	// commit metadata (branch, message, author, short revision). The
	// runs.revisions JSONB is keyed by material_id; we unpack it and
	// match each (material_id, revision) to the modification row
	// that actually produced the run. LIMIT/DISTINCT ON at each level
	// keeps the output one row per pipeline even when a run snapshots
	// multiple materials — we pick the first match deterministically
	// (order by material_id) so the card shows a stable ref.
	LatestRunMetaByProjectSlug(ctx context.Context, slug string) ([]LatestRunMetaByProjectSlugRow, error)
	// Per-project commit metadata from the most recent run across all
	// of the project's pipelines. Same JSONB-expand pattern as the
	// per-slug variant, just without the slug filter so one query
	// serves the whole projects list. triggered_by is kept so the UI
	// can fall back to the manual-trigger user when author is null
	// (manual runs don't create webhook-driven modifications).
	LatestRunMetaPerProject(ctx context.Context) ([]LatestRunMetaPerProjectRow, error)
	// DISTINCT ON picks the most recent run per pipeline. Pipelines with
	// no runs yet are absent from the result; the handler merges with
	// ListPipelinesByProjectSlug to produce node entries.
	//
	// has_services comes from the snapshot stamped at run-create time
	// (migration 00036) — lets the project page client skip the
	// /api/v1/runs/:id/services fetch entirely on pipelines whose
	// latest run never declared a `services:` block. Without it the
	// project page issues one polling fetch per card.
	LatestRunPerPipelineByProjectSlug(ctx context.Context, slug string) ([]LatestRunPerPipelineByProjectSlugRow, error)
	ListAPITokensByServiceAccount(ctx context.Context, serviceAccountID pgtype.UUID) ([]ListAPITokensByServiceAccountRow, error)
	// Tokens this user owns, newest first. Used by /settings/api-tokens.
	ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ListAPITokensByUserRow, error)
	// Every distinct agent that ran (or is running) at least one job
	// of the given run, FILTERED to engines that can actually do the
	// cleanup work — k8s today. Used by the run-terminal
	// CleanupRunServices dispatch.
	//
	// Why the engine filter:
	//   - A mixed-engine run (job 1 on k8s, job 2 on docker) puts
	//     BOTH agents on the unfiltered list. The docker agent's
	//     CleanupRunServices is a no-op that returns
	//     success-with-0-deleted, which the server's ok-counter
	//     would mistakenly count as a successful cleanup,
	//     masking the fact that the disconnected k8s agent's pods
	//     never got reaped.
	//   - Filtering at the SQL layer means the ok-count surfaces
	//     ONLY engines that COULD have done useful work, so a "0
	//     successful dispatches" log line is operationally
	//     trustworthy.
	//
	// agents.engine='' (empty / legacy / pre-v0.4.35) passes the
	// filter defensively — a rolling upgrade window where old agents
	// haven't been redeployed yet still gets best-effort cleanup
	// coverage; the value is overwritten on the next Register.
	ListAgentsForRun(ctx context.Context, runID pgtype.UUID) ([]pgtype.UUID, error)
	// Dashboard + /agents list: every agent with its declared metadata
	// + a count of currently-running job_runs it's been assigned.
	// LEFT JOIN + FILTER gives 0 for idle agents without needing a
	// second roundtrip.
	ListAgentsWithRunning(ctx context.Context) ([]ListAgentsWithRunningRow, error)
	// Used by server-side JobResult reconciliation to match ArtifactRef
	// entries back to their pending rows. Also used later (E2c) to expose
	// downloads to downstream jobs in the same run.
	ListArtifactsByJobRun(ctx context.Context, jobRunID pgtype.UUID) ([]ListArtifactsByJobRunRow, error)
	// Used by E2c for intra-run downloads (`needs_artifacts:` resolution).
	// Only returns ready artefacts — pending/deleting must not leak as
	// dependable to downstream jobs.
	ListArtifactsByRun(ctx context.Context, runID pgtype.UUID) ([]ListArtifactsByRunRow, error)
	// Same as ListArtifactsByRun but joined with job_runs.name so the UI
	// can group artefacts by the job that produced them without an extra
	// per-artifact lookup. Returns ALL statuses — callers filter as needed.
	ListArtifactsWithJobByRun(ctx context.Context, runID pgtype.UUID) ([]ListArtifactsWithJobByRunRow, error)
	// Reverse-chrono listing with optional filters + offset
	// pagination. Empty string on action / target_type / actor
	// disables that filter; nil actor_id_filter disables actor
	// filtering (applied separately because typing empty UUID as
	// "no filter" leaks). from_at / to_at are nullable timestamps
	// — pass NULL on either end for open-ended ranges.
	// Half-open [from_at, to_at) so callers can pass midnight
	// boundaries ("2026-04-24T00:00" to "2026-04-25T00:00" = all
	// of 2026-04-24) without worrying about boundary overlap.
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	// Returns every row regardless of `enabled`. The UI filters on
	// the boolean so admins can see disabled providers they can re-
	// enable later.
	ListAuthProviders(ctx context.Context) ([]AuthProvider, error)
	// Loads every cron material in the system alongside its pipeline
	// / project id and its last-fired timestamp (NULL when never
	// fired). The ticker walks this list on every tick; N is bounded
	// by `pipelines × cron_materials_per_pipeline`, typically a few
	// dozen at most, so scanning in-process is fine.
	ListCronMaterials(ctx context.Context) ([]ListCronMaterialsRow, error)
	// Returns queued jobs in the lowest-ordinal stage that still has queued or
	// running work. The scheduler does needs-satisfaction checking in Go so the
	// query stays readable; the stage gate is the only SQL-level constraint.
	ListDispatchableJobs(ctx context.Context, runID pgtype.UUID) ([]ListDispatchableJobsRow, error)
	// Bootstrap path: just the ones that should be registered on
	// server start (or after a reload).
	ListEnabledAuthProviders(ctx context.Context) ([]AuthProvider, error)
	// Ticker path: every enabled schedule in the system + its
	// last-fired bookkeeping. N is small (projects × a handful of
	// schedules each), so full-scan-in-memory is fine.
	ListEnabledProjectCrons(ctx context.Context) ([]ListEnabledProjectCronsRow, error)
	// Bootstrap + reload path: rows the registry should actually
	// instantiate on startup.
	ListEnabledVCSIntegrations(ctx context.Context) ([]VcsIntegration, error)
	// Every type='git' material in the DB. Webhook tag-push routing
	// pulls this set and filters Go-side: NormalizeGitURL on each
	// config->>'url' matched against the canonical clone URL from the
	// webhook payload. URL drift across the operator-typed forms
	// (`.git` suffix, https vs ssh) is canonicalised on BOTH sides at
	// filter time so a material declared with `url:
	// https://github.com/x/y.git` matches a webhook for
	// `https://github.com/x/y` and vice versa.
	//
	// Why a full scan vs an indexed `WHERE config->>'url' = $1`:
	// material URLs are stored verbatim from the YAML (parser keeps the
	// operator's form so the agent's `git clone` reproduces what was
	// declared), so the in-DB string varies across rows. A JSONB
	// functional index would only help for the exact form; the
	// normalize-and-compare path covers all of them. At < 10k git
	// materials the scan is < 100ms; revisit with an `url_fingerprint`
	// column if larger deployments observe latency.
	ListGitMaterials(ctx context.Context) ([]Material, error)
	// Admin-only listing of every global (unscoped) secret. Same
	// "names + timestamps, never values" contract as project secrets.
	ListGlobalSecrets(ctx context.Context) ([]ListGlobalSecretsRow, error)
	// Join against users so the UI renders name/email without a
	// second round-trip. Orders by the user's display name so the
	// admin UI reads alphabetically.
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error)
	// UI: admin-only list of groups + a cheap member count so the
	// settings page can render "SRE (4 members)" without a second
	// query per group.
	ListGroups(ctx context.Context) ([]ListGroupsRow, error)
	// Reads (name, matrix_key, outputs) for every job_run in the given
	// run whose name appears in @names. Used by the scheduler during
	// dispatch to resolve `${{ needs.<job>.outputs.<key> }}` refs in a
	// downstream job's `with:` / `env:` / `script:` (issue #10).
	//
	// Outputs are NOT NULL DEFAULT '{}' on the column, so a job that
	// ran without writing outputs returns an empty map — the
	// substitution layer surfaces "key missing" as a hard error
	// (operator referenced a key the upstream never produced) rather
	// than silently substituting empty.
	//
	// Why scoped by run_id + name list (not just run_id): a typical
	// needs: list is 1–3 names, the run has 10–50 job_runs. Filtering
	// at SQL avoids dragging unrelated rows + their JSONB payloads
	// across the wire. matrix_key returns so a needs:[matrix-parent]
	// reference can still pick the right instance (today the
	// substitution path picks the matrix_key='' parent; sibling-
	// matrix-row refs are a follow-up).
	ListJobOutputsForRun(ctx context.Context, arg ListJobOutputsForRunParams) ([]ListJobOutputsForRunRow, error)
	// Detail trail for the UI: every vote in chronological order.
	ListJobRunApprovals(ctx context.Context, jobRunID pgtype.UUID) ([]ListJobRunApprovalsRow, error)
	ListJobRunsByRun(ctx context.Context, runID pgtype.UUID) ([]ListJobRunsByRunRow, error)
	ListJobRunsByRunFull(ctx context.Context, runID pgtype.UUID) ([]ListJobRunsByRunFullRow, error)
	// Batch-loads job_runs for every run whose id is in the input
	// array. The project detail page renders a GitLab-style pipeline
	// flow per pipeline, each stage box listing its jobs — fetching
	// these per pipeline would mean N queries. This single scan
	// covers the card set.
	ListJobRunsForRuns(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListJobRunsForRunsRow, error)
	// Lean projection (name + matrix_key + status) used by the scheduler's
	// needs-satisfaction gate. Loaded ONCE per dispatch tick and consulted
	// per-candidate to decide "all upstreams green?". A row-per-(name,
	// matrix_key) layout means matrix fanouts surface as multiple rows
	// under the same name, which the gate folds into "all matrix children
	// must succeed" — see scheduler/needs.go for the semantic.
	//
	// Ordering matches ListJobRunsByRun so the per-name slices the
	// scheduler builds are deterministic across runs (matrix combos
	// iterate in insert order, which sorted by matrix_key at row creation
	// per store/runs.go).
	ListJobStatusForRun(ctx context.Context, runID pgtype.UUID) ([]ListJobStatusForRunRow, error)
	// Recent jobs dispatched to this agent. Joined all the way up to
	// the project so the table can link to the owning run/project
	// without per-row lookups. LIMIT is caller-supplied to avoid
	// pagination complexity for now (UI caps at 100).
	ListJobsForAgent(ctx context.Context, arg ListJobsForAgentParams) ([]ListJobsForAgentRow, error)
	// Reconciliation #1: terminal job_runs that should have been archived
	// but weren't. The submit-on-terminal hook is best-effort; the queue
	// can drop on saturation, the server can crash mid-flight, the
	// artefact backend can be unreachable. The sweeper picks up the
	// stragglers. Joined to the project's archive flag so the sweeper
	// skips jobs whose project opted out — global=on policy may still
	// have per-project off overrides.
	//
	// "Terminal" here = finished_at IS NOT NULL AND status not in ('queued','running').
	// A grace window guards against racing the in-flight submit so the
	// sweeper doesn't spam the queue with jobs already being archived.
	ListJobsNeedingArchive(ctx context.Context, arg ListJobsNeedingArchiveParams) ([]ListJobsNeedingArchiveRow, error)
	ListMaterialsByPipeline(ctx context.Context, pipelineID pgtype.UUID) ([]Material, error)
	// All materials across pipelines of a project. VSM uses the
	// `upstream` ones to build edges between pipeline nodes; git ones
	// are informational (shown as entry points on the graph).
	ListMaterialsByProjectSlug(ctx context.Context, slug string) ([]ListMaterialsByProjectSlugRow, error)
	// Reconciliation #2: jobs whose URI is stamped but log_lines rows
	// still exist. Happens when the archiver's DELETE step fails after
	// the URI update lands. The read path already serves from the
	// archive, so the rows are pure cost — sweep them on a slow tick.
	ListOrphanedArchivedJobs(ctx context.Context, lim int32) ([]pgtype.UUID, error)
	// The agent calls this right after Register + Connect lands so
	// it picks up any cancels that were requested while its session
	// was being recycled. Returns (job_run_id, run_id) pairs the
	// agent can issue local-cancel-equivalent handling on. The
	// agent then sends the usual JobResult(status=canceled) to
	// close out each row server-side — the existing result handler
	// finalises the status, and the cancel_requested_at column
	// becomes operationally redundant on that row (kept for the
	// audit trail's at-time).
	//
	// Hits the partial index job_runs_pending_cancel_by_agent_idx;
	// index-only on the WHERE clause makes this a sub-millisecond
	// lookup even on a job_runs table in the millions.
	ListPendingCancelsForAgent(ctx context.Context, agentID pgtype.UUID) ([]ListPendingCancelsForAgentRow, error)
	ListPipelinesByProject(ctx context.Context, projectID pgtype.UUID) ([]ListPipelinesByProjectRow, error)
	// Returns definition alongside metadata so the card can pull
	// stage names from the YAML when the pipeline has never run
	// (no stage_runs yet → no history to render from).
	ListPipelinesByProjectSlug(ctx context.Context, slug string) ([]ListPipelinesByProjectSlugRow, error)
	// Every git material in the system + the project-level scm_source
	// context (provider, url, auth_ref, default_branch) the poller
	// needs to resolve branch HEAD, plus the per-material poll state.
	//
	// Effective-interval filtering (material-level poll_interval from
	// JSONB config OR scm_source fallback) happens in Go because a
	// WHERE clause can only see one side at a time and the JSONB-path
	// arithmetic gets ugly. N is bounded by `sum(git_materials per
	// pipeline)`, typically a few dozen, so scanning in-process is
	// fine. LEFT JOIN on scm_sources: a detached project (no binding)
	// simply has NULL columns and the Go layer skips polling it.
	ListPollableGitMaterials(ctx context.Context) ([]ListPollableGitMaterialsRow, error)
	// UI: list schedules bound to one project, newest first so
	// recently-added shows at the top.
	ListProjectCronsByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectCron, error)
	// Projects whose total live artefact bytes (pending + ready, non-
	// deleted, non-pinned) exceed the configured soft cap. Returned once
	// per tick so the sweeper can ExpireOldestInProjectByExcess against
	// each one individually.
	ListProjectsOverArtifactQuota(ctx context.Context, dollar_1 int64) ([]ListProjectsOverArtifactQuotaRow, error)
	// Project list used by the dashboard home. Joins enough aggregate info so the
	// UI renders without round-tripping per row.
	//
	// Extra columns feed the card-style layout on /projects:
	//   * provider: from the bound scm_source when present; empty string
	//     when the project has no repo yet (shown as "—" in the UI).
	//   * run_count: total runs across all pipelines — the card shows
	//     "5 pipelines · 123 runs" as a density signal.
	//   * status_agg: coarse health derived from the most recent run per
	//     pipeline. Pre-computed in a CTE (latest_per_pipeline) so the
	//     outer aggregate stays aggregate-only; correlated subqueries
	//     inside CASE/WHEN during GROUP BY are fragile in Postgres and
	//     blew up the previous version of this query.
	ListProjectsWithCounts(ctx context.Context) ([]ListProjectsWithCountsRow, error)
	// Runs the scheduler's tick reconsiders: both freshly queued ones and
	// already-running runs that may have a queued job waiting (re-queued by the
	// reaper, blocked waiting for a next stage, etc.).
	ListQueuedRunIDs(ctx context.Context) ([]pgtype.UUID, error)
	// Returns ready artefacts produced by a specific job name within a run,
	// optionally filtered by a path whitelist. Used by the scheduler when
	// resolving `needs_artifacts` on a downstream job. An empty paths
	// array returns all of that job's artefacts.
	ListReadyArtifactsByRunAndJobName(ctx context.Context, arg ListReadyArtifactsByRunAndJobNameParams) ([]ListReadyArtifactsByRunAndJobNameRow, error)
	// Admin UI hot path. Sorted by name so the table reads alphabetical.
	ListRunnerProfiles(ctx context.Context) ([]RunnerProfile, error)
	// Every running job currently assigned to a given agent_id. The
	// register-fence path uses this: when an agent re-registers (= the
	// prior process is gone), every still-'running' row attributed to it
	// is by definition orphaned and must be reclaimed before we accept
	// new assignments for the new session. This is the primary fix for
	// "agent restarts → job stuck running forever → reaper skips because
	// last_seen_at is fresh" (issue #4).
	//
	// Returned columns mirror ListStaleRunningJobs so the reaper-Go
	// side can reuse the same ReclaimResult shape.
	//
	// cancel_requested_at IS NULL guard: rows with a cancel intent
	// stamped don't belong to this reclaim path — they belong to the
	// agent_service.Register replay path
	// (ListPendingCancelsForAgent), which honors the cancel as a
	// terminal 'canceled' instead of dropping it back to 'queued' as
	// a retry. Without the guard, the reclaim wins the race and the
	// operator's cancel intent becomes a generic requeue; on hits
	// past max attempts it becomes a failed (not canceled) row,
	// mis-attributing the operator's deliberate stop as a process
	// crash.
	ListRunningJobsForAgent(ctx context.Context, agentID pgtype.UUID) ([]ListRunningJobsForAgentRow, error)
	ListRunsByProjectSlug(ctx context.Context, arg ListRunsByProjectSlugParams) ([]ListRunsByProjectSlugRow, error)
	// Cross-project timeline: most recent runs first. Carries the
	// pipeline + project names so list views can link without per-row
	// lookups. All filter params accept the empty string as "no filter"
	// so the same query drives the dashboard widget (no filters) and
	// the /runs page (every filter the UI exposes).
	ListRunsGlobal(ctx context.Context, arg ListRunsGlobalParams) ([]ListRunsGlobalRow, error)
	// Admin UI: list every org-level credential. Ciphertext comes
	// along because admins who can read this table already hold the
	// keys; the decrypt step lives in the store layer.
	ListSCMCredentials(ctx context.Context) ([]ScmCredential, error)
	// Lists names + timestamps only — values never leave the DB without going
	// through GetSecretValuesByProject below.
	ListSecretsByProject(ctx context.Context, projectID pgtype.UUID) ([]ListSecretsByProjectRow, error)
	// Newest first. Disabled SAs included; the UI dims them so admins
	// see the full picture without filtering.
	ListServiceAccounts(ctx context.Context) ([]ServiceAccount, error)
	// API: GET /api/runs/{id}/services. Sort by name for a stable
	// UI ordering — the YAML's declaration order isn't preserved in
	// the upsert path so alphabetical is the only stable choice.
	ListServiceRunsByRunID(ctx context.Context, runID pgtype.UUID) ([]ServiceRun, error)
	ListStageRunsByRun(ctx context.Context, runID pgtype.UUID) ([]ListStageRunsByRunRow, error)
	ListStageRunsByRunOrdered(ctx context.Context, runID pgtype.UUID) ([]ListStageRunsByRunOrderedRow, error)
	// Batch-loads stage_runs for every run whose id is in the input
	// array — the project detail page renders one pipeline card per
	// pipeline and each card needs the latest run's stage states.
	// Issuing one query per card would mean N+1 round trips; this
	// amortizes them into a single scan.
	ListStageRunsForRuns(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListStageRunsForRunsRow, error)
	// Running jobs the reaper should reclaim. Two distinct categories live
	// under the same SELECT so a single sweep tick handles both:
	//
	//   1) Has agent, agent is unhealthy: status='offline', missing
	//      last_seen_at, or last_seen_at older than @staleness. Original
	//      reaper case — agent process died and we wait the heartbeat
	//      grace window before declaring its jobs gone.
	//   2) Has NO agent (agent_id IS NULL) and the row has been sitting
	//      that way past @staleness. This state shouldn't be reachable
	//      via normal paths (AssignJob is atomic on both fields, and
	//      ReclaimJobForRetry flips status to 'queued' in the same UPDATE
	//      that NULLs the agent), but it surfaces from:
	//        - Manual DB intervention to scrub an agent without flipping
	//          status.
	//        - Future code regression that splits the agent/status update.
	//        - Partial migration that nulled agent_id mid-flight.
	//      The INNER JOIN variant this replaced was invisible to such
	//      orphans — they'd sit 'running' forever, blocking serial
	//      pipelines indefinitely. Issue #4 walks the operator-visibility
	//      consequences.
	//
	// agent_status / last_seen_at come back NULL for category (2); the
	// reaper-Go side doesn't act on those fields beyond logging.
	//
	// agent_session_generation is the per-agent monotonic epoch counter
	// snapshotted at SELECT time. The reaper-Go side passes this back to
	// SessionStore.FenceStaleSession so a successor Register that bumped
	// the counter between SELECT and fence (race that previously could
	// revoke a freshly-online healthy session) is correctly skipped.
	// COALESCE to 0 for category (2) so the Go side gets a stable int —
	// the NULL-agent fence path uses agent_id == uuid.Nil as its skip
	// predicate anyway.
	ListStaleRunningJobs(ctx context.Context, staleness pgtype.Interval) ([]ListStaleRunningJobsRow, error)
	// Returns the last N executions of a single case across every
	// run of every pipeline. Used by the Tests-tab "history" popup
	// so a dev chasing a flake can see the green/red pattern over
	// time. The (classname, name, created_at DESC) index covers
	// this access pattern directly.
	ListTestCaseHistory(ctx context.Context, arg ListTestCaseHistoryParams) ([]ListTestCaseHistoryRow, error)
	// Returns every case across every job in a run. The Tests tab
	// groups them by job_run_id in-memory — cheaper than JOINing
	// job_runs here because the UI already has the job list from
	// RunDetail.
	ListTestResultsByRun(ctx context.Context, jobRunIds []pgtype.UUID) ([]ListTestResultsByRunRow, error)
	// Per-project top-N (most recently updated) pipelines with their
	// latest run status. Used to render the "mini stack" inside each
	// project card without issuing one query per card (N+1). Capped at
	// 20 entries per project via ROW_NUMBER partition — the side-by-
	// side pipeline layout in the card fits comfortably up to ~10
	// pipelines; projects beyond that surface a "+K more" hint. Bump
	// the cap further if real-world projects regularly cross it.
	//
	// Also returns:
	//   * latest_run_id: zero-UUID when the pipeline has never run.
	//     Callers collect these to batch-load stage_runs.
	//   * definition: the pipeline's YAML snapshot (JSONB). The card
	//     renders grey "pending" stage pills from definition.Stages
	//     when latest_run_id is zero, and reconciles definition vs.
	//     stage_runs for mid-run/cancelled states.
	ListTopPipelinesPerProject(ctx context.Context) ([]ListTopPipelinesPerProjectRow, error)
	// Permission check hot path: "is this user in any group that's
	// in the gate's approver_groups?" — we fetch the user's group
	// names once per approve call and intersect in Go. Names (not
	// ids) match what the gate stores.
	ListUserGroupNames(ctx context.Context, userID pgtype.UUID) ([]string, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	// Admin feed. Returns every row regardless of `enabled` so the
	// /settings/integrations page can surface disabled rows the user
	// can re-enable.
	ListVCSIntegrations(ctx context.Context) ([]VcsIntegration, error)
	// Admin console feed. Most recent first; indexed on received_at.
	// Filter by provider + status keep the page useful even under
	// heavy traffic. Empty string = no filter on that axis.
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	// Generation-aware offline mark. Only flips status when the
	// closing handler's observed generation still matches the row.
	// A successor Register bumps session_generation, so an old
	// defer (which captured the prior value) finds no rows to
	// update and no-ops — preserving the successor's online state.
	MarkAgentOffline(ctx context.Context, arg MarkAgentOfflineParams) error
	// Called after the server HEADs the storage and confirms the object is
	// there. Bumps status + records size/sha. Safe to call once; subsequent
	// calls update nothing (status already 'ready'), returning 0 rows.
	MarkArtifactReady(ctx context.Context, arg MarkArtifactReadyParams) (int64, error)
	// Stamps the archive URI on the job_run and timestamps the moment.
	// The DELETE of log_lines for this job is a separate step in the
	// archiver so a failed update doesn't leak rows.
	MarkJobLogsArchived(ctx context.Context, arg MarkJobLogsArchivedParams) error
	// Called by the ticker after a successful evaluation+fire cycle.
	// Same-second fires are gated via the cron expression parser
	// reading last_fired_at — the store update closes that loop.
	MarkProjectCronFired(ctx context.Context, arg MarkProjectCronFiredParams) error
	MarkRunRunningIfQueued(ctx context.Context, id pgtype.UUID) error
	MarkStageRunningIfQueued(ctx context.Context, id pgtype.UUID) error
	NextRunCounter(ctx context.Context, pipelineID pgtype.UUID) (int64, error)
	// Returns the run_id of an in-flight predecessor blocking the
	// pipeline's serial-concurrency gate, or pgx.ErrNoRows if none.
	// Used by the scheduler for two things on one query: (1) the busy
	// decision (leave queued vs proceed), and (2) the predecessor id to
	// stamp on runs.queue_reason so the UI can render "waiting on #N".
	//
	// Replaces the prior boolean-returning OtherRunningRunExistsForPipeline
	// — the boolean was load-bearing for the decision alone, but the id
	// is needed for the operator-visibility surface (issue #4 path #2).
	// Excluded self so a re-entrant tick (scheduler evaluates the same
	// run twice) doesn't see itself as a blocker. LIMIT 1 is fine: any
	// one blocking run is enough to leave queued; we don't need the
	// full set.
	OtherRunningRunForPipeline(ctx context.Context, arg OtherRunningRunForPipelineParams) (pgtype.UUID, error)
	// Per-pipeline aggregate stats over the last $2 interval. Terminal
	// runs only — queued/running are excluded so the medians don't move
	// during active work. `process_time_p50_seconds` is the median of
	// the per-run sum of stage_run durations (actual busy time),
	// distinct from `lead_time_p50_seconds` (wall-clock run duration).
	PipelineMetricsByProjectSlug(ctx context.Context, arg PipelineMetricsByProjectSlugParams) ([]PipelineMetricsByProjectSlugRow, error)
	// Per-stage aggregates over the same window. Feeds the card's
	// per-stage duration badge (p50) and bottleneck call-out (success
	// rate under threshold). Only terminal stage_runs count — a
	// running/cancelled stage without finished_at would poison the
	// median.
	PipelineStageMetricsByProjectSlug(ctx context.Context, arg PipelineStageMetricsByProjectSlugParams) ([]PipelineStageMetricsByProjectSlugRow, error)
	// Per-project roll-up of terminal runs over the last $1 interval.
	// Same math as PipelineMetricsByProjectSlug but grouped by project
	// instead of pipeline — the projects list card shows one KPI strip
	// per project, so aggregating in SQL saves an N×round-trip dance
	// when compared with looping the per-slug query per project.
	ProjectMetricsAggregated(ctx context.Context, sinceWindow pgtype.Interval) ([]ProjectMetricsAggregatedRow, error)
	// Flips a running job back to queued, IF it is still running, still
	// under the retry cap, AND its (agent_id, attempt) STILL matches the
	// snapshot the caller observed when it decided the job was stale.
	//
	// Snapshot match is load-bearing: between ListStaleRunningJobs and
	// this UPDATE, a concurrent reaper / register-fence / rerun could
	// have flipped status=queued → scheduler dispatched → AssignJob set
	// (running, NEW_AGENT, attempt+1). Without snapshot validation, this
	// UPDATE would happily requeue a healthy job actively running on
	// the new agent, kicking off a cascade of unnecessary retries that
	// the operator perceives as "jobs randomly re-running for no reason".
	//
	// `agent_id IS NOT DISTINCT FROM` honours NULL equality — the
	// NULL-agent reaper category sees `expected_agent_id` as NULL and
	// only requeues rows that still have NULL there.
	//
	// ErrNoRows signals the caller should take a different code path
	// (failed-at-max, already-reclaimed, raced-out-of-window).
	// cancel_requested_at = NULL: defensive clear, mirrored from
	// RerunJob's reset list. ListRunningJobsForAgent already excludes
	// rows with cancel_requested_at IS NOT NULL from the
	// register-fence reclaim, so a stamped row should NEVER reach
	// this UPDATE — but the clear is cheap and closes the door on
	// an in-flight Phase 0 reaper losing a CAS race against this
	// one, which would otherwise leave the row queued with a stale
	// stamp and re-trigger the replay path on the next AssignJob.
	ReclaimJobForRetry(ctx context.Context, arg ReclaimJobForRetryParams) (ReclaimJobForRetryRow, error)
	// The reaper's path for cancels that never reached an agent
	// because the agent went offline and stayed offline past the
	// cancel grace window. Finalises every still-running row that
	// belongs to an offline agent AND was cancel-requested as
	// 'canceled' with finished_at=NOW().
	//
	// Why this lives in the reaper (not a hot path):
	//
	//   * The hot path (cancel handler) does not block on agent
	//     liveness — it stamps cancel_requested_at and returns
	//     202 immediately. The DB row stays 'running' from the
	//     handler's perspective; the reaper does the finalising
	//     when it's clear the agent isn't coming back.
	//
	//   * Latency of cancel finalisation = reaper tick interval +
	//     offline-grace window. Both are operator-tunable; default
	//     is ~5min total. Acceptable for a "we tried, agent gone"
	//     case; the operator-visible status is 'canceling' in the
	//     meantime via the cancel_requested_at column.
	//
	// Liveness predicate mirrors the reaper's main path
	// (ListStaleRunningJobs in sweeper.sql) so a heartbeat-stale
	// agent that's still marked online doesn't accumulate
	// cancel-pending rows forever. Three failure shapes catch
	// everything except a perfectly healthy agent the replay path
	// still owns:
	//
	//   1. a.status = 'offline'  — explicit liveness flip; the
	//      Connect-defer or the reaper has marked the row offline.
	//   2. a.last_seen_at IS NULL — agent never sent a heartbeat
	//      since this server started; either fresh-DB state or a
	//      truly dead row.
	//   3. a.last_seen_at < NOW() - grace — heartbeat stopped past
	//      the grace window. agents.status may still be 'online'
	//      if the offline-mark never fired (network partition;
	//      Connect-defer crashed), but the heartbeat signal is
	//      gone for real.
	//
	// A perfectly healthy agent (status=online AND last_seen_at
	// recent) is skipped — the replay path is still expected to
	// land the cancel on its next Connect frame.
	ReclaimPendingCancelsForOfflineAgent(ctx context.Context, graceInterval pgtype.Interval) ([]ReclaimPendingCancelsForOfflineAgentRow, error)
	// Called by the sweeper AFTER Store.Delete succeeded (or the object
	// was already gone). Removes the DB row.
	RemoveArtifactRow(ctx context.Context, id pgtype.UUID) (int64, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	// Soft-deletes every still-active artifact row attributed to a
	// job_run_id so a retry / reclaim / rerun can re-upload the same
	// paths without colliding with the prior attempt's rows. Called
	// from sweeper.requeueStaleJob and store.RerunJob in the same
	// transaction that bumps job_runs.attempt — same semantics as the
	// DeleteLogLinesByJob / DeleteTestResultsByJobRun calls already
	// there (issue #3).
	//
	// Flips status to 'deleting' so the sweeper picks the rows up via
	// its existing "stale 'deleting' rows" branch and removes the
	// storage objects too — without this, the orphaned S3/GCS object
	// has no DB row to GC it through and leaks until the bucket
	// lifecycle policy (if any) kicks in.
	//
	// deleted_at = NOW makes the row invisible to ListReadyArtifactsByRunAndJobName
	// (filters by deleted_at IS NULL), so the downstream's lookup sees
	// ONLY the new attempt's still-uploading rows — the moment the
	// new attempt's MarkArtifactReady commits, the downstream can
	// dispatch correctly. Without this, the lookup would see the old
	// ready row pointing at a soon-to-be-swept storage object and
	// happily hand the consumer a signed URL that 404s.
	//
	// expires_at = NOW shortens the sweeper's grace window for these
	// specific rows — they're not ordinary TTL expiries, the
	// predecessor attempt is over, no reason to wait the configured
	// retention before deleting.
	RetireArtifactsByJobRun(ctx context.Context, jobRunID pgtype.UUID) error
	// Idempotent: revoke-on-already-revoked is a no-op. Caller filters
	// by user_id or service_account_id to gate ownership.
	RevokeAPIToken(ctx context.Context, id pgtype.UUID) error
	// Snapshot read: was the run created with a non-empty `Services`
	// block in its pipeline definition? Persisted on insert
	// (migration 00036) rather than computed live from
	// pipelines.definition, so an ApplyProject that adds/removes
	// services mid-run doesn't lie to the cleanup cascade. Defaults
	// to false when the run row is missing (cleanup skipped, safer
	// than fail-open here — operator can run manual sweep if a stale
	// leak surfaces).
	RunHasServices(ctx context.Context, id pgtype.UUID) (bool, error)
	SetAuthProviderEnabled(ctx context.Context, arg SetAuthProviderEnabledParams) error
	// Replaces the project-level notifications list. Admin/maintainer
	// UI writes here; the column has a NOT NULL default of '[]' so a
	// fresh project never needs an initial INSERT against this field.
	SetProjectNotifications(ctx context.Context, arg SetProjectNotificationsParams) error
	// Sets runs.queue_reason on a still-queued run. Callers stamp this
	// AFTER the busy decision so the field reflects the latest tick's
	// reasoning. A run that flipped to a terminal status between the
	// scheduler's read and this write would write to a stale row;
	// the `status='queued'` guard turns that into a no-op rather than
	// planting a confusing message on a finished run.
	SetRunQueueReason(ctx context.Context, arg SetRunQueueReasonParams) error
	// Disabling stops new tokens from authenticating (the bearer
	// middleware loads the SA after token lookup and bounces 401 when
	// disabled_at is set). Existing tokens stay in the table — wipe
	// explicitly with DELETE if you want them gone.
	SetServiceAccountDisabled(ctx context.Context, arg SetServiceAccountDisabledParams) error
	SetVCSIntegrationEnabled(ctx context.Context, arg SetVCSIntegrationEnabledParams) error
	// Marks a still-queued job as 'skipped' with a terminal finish
	// time so GetStageProgress stops counting it as unfinished. The
	// scheduler calls this for synthetic notification jobs whose
	// `on:` trigger doesn't match the run's user-stage outcome —
	// skipped is the right semantic (the job was never attempted on
	// purpose) vs. canceled (user/system stopped it).
	SkipJobRun(ctx context.Context, id pgtype.UUID) (SkipJobRunRow, error)
	// Persists the cancel INTENT on a running job_run BEFORE the
	// handler attempts the gRPC dispatch. Decouples the cancel UX
	// from "is the agent's session alive in this instant" — even if
	// Dispatch fails because of a Revoke→Register race (the agent
	// pod is in flux), the intent survives. When the agent's new
	// session comes up it calls ListPendingCancelsForAgent and
	// honors the cancel; if it never comes back, the reaper
	// finalises the row via ReclaimPendingCancelsForOfflineAgent.
	//
	// Idempotent on the timestamp: COALESCE keeps the FIRST cancel
	// request's at-time so the audit trail matches the first click
	// (a re-click that lands in the brief window between dispatch
	// attempts shouldn't reset the requested-at clock).
	//
	// Predicate guards: only stamp when the row is STILL running
	// AND has an agent_id pinned (no-op on rows that finished
	// between the cancel handler's read and this write). The
	// handler ran GetJobRunForCancel under FOR UPDATE in the same
	// tx, so by definition the row was running at SELECT time —
	// but a result handler in another tx can have committed in
	// between if the cancel handler is using a separate tx. The
	// guards keep us honest in either calling shape.
	StampCancelRequestedAt(ctx context.Context, id pgtype.UUID) (StampCancelRequestedAtRow, error)
	// Batch variant of StampCancelRequestedAt used by the run-scoped
	// cancel path. Stamps cancel_requested_at on EVERY running job
	// belonging to the run that hasn't been stamped yet. The handler
	// then attempts gRPC dispatch per row; any dispatch that lands in
	// the Revoke→Register race window is rescued by the same replay
	// + reaper paths that cover the job-scoped cancel.
	//
	// COALESCE preserves the FIRST stamp's at-time across re-cancel
	// attempts (the same idempotency as the single-row variant).
	// Returns (id, agent_id) per stamped row so the handler can
	// correlate Dispatch failures with their owning agent.
	StampCancelRequestedAtForRun(ctx context.Context, runID pgtype.UUID) ([]StampCancelRequestedAtForRunRow, error)
	// Returns the tail (up to $2 lines) of a job's logs, oldest-first within the
	// returned window, so the UI can append-only render.
	TailLogLinesByJob(ctx context.Context, arg TailLogLinesByJobParams) ([]TailLogLinesByJobRow, error)
	// Best-effort `last_used_at` bump. Called from the middleware
	// when a Bearer token authenticates successfully — a stale value
	// doesn't break anything, just makes the audit trail less useful.
	TouchAPITokenLastUsed(ctx context.Context, id pgtype.UUID) error
	// Cheap idempotent update; called at most once per request via a
	// debounce in the middleware so we don't rewrite the row on every
	// 2s dashboard poll.
	TouchUserSession(ctx context.Context, id []byte) error
	// Rolls back an AssignJob whose Dispatch failed downstream (busy
	// session queue, session vanished between AssignJob commit and the
	// gRPC send). Snapshot-validating CAS — only undoes the row if it's
	// still (running, $agentID, $attempt), matching exactly what we
	// just claimed. Anything else means a reaper / fence already moved
	// the row out from under us and our undo would clobber legitimate
	// state. Returns the run_id so the caller can fire a NOTIFY to
	// nudge the scheduler back into the dispatch loop.
	//
	// The row goes back to (queued, NULL, attempt unchanged) — we do
	// NOT bump attempt here. The attempt counter exists to detect
	// crashes mid-execution; a dispatch failure that never reached the
	// agent doesn't count as an attempt.
	// cancel_requested_at = NULL: defensive clear in case a cancel
	// landed in the AssignJob→DispatchAssignment window (operator
	// raced the scheduler). The row is going back to 'queued' with
	// agent_id NULL — there's no agent to replay against, and the
	// next AssignJob may pick a different agent entirely; carrying
	// the stamp forward would let ListPendingCancelsForAgent honor
	// it against an agent that never received the cancel intent.
	UnassignJob(ctx context.Context, arg UnassignJobParams) (UnassignJobRow, error)
	// Called from the gRPC heartbeat handler so the reaper can tell which agents
	// are still alive. Tiny write per heartbeat (default cadence 30s).
	UpdateAgentLastSeen(ctx context.Context, id pgtype.UUID) error
	// Bumps the per-agent session_generation counter atomically with
	// the online-stamp. The new generation flows back to the caller
	// (Connect handler) which captures it for its eventual
	// MarkAgentOffline defer.
	//
	// Why this is monotonic int rather than session_id (TEXT):
	// session_id is a bearer credential used by Connect's auth — the
	// in-memory SessionStore.Lookup compares raw strings, so anything
	// holding the id can impersonate. Persisting it would mean a
	// read-only DB leak (backup, snapshot, log) effectively dumps live
	// session tokens. The CAS only needs an epoch indicator — a
	// counter carries exactly that signal with no auth power.
	UpdateAgentOnRegister(ctx context.Context, arg UpdateAgentOnRegisterParams) (int64, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	// Dedicated password-only write. Used when an admin changes their
	// own password from /settings/account — we never want to let the
	// admin also flip their role through that surface.
	UpdateLocalUserPassword(ctx context.Context, arg UpdateLocalUserPasswordParams) error
	// Sets the per-project log_archive_enabled override. NULL value
	// means "inherit global" — explicitly clearing the row by writing
	// a NULL works through the same path.
	UpdateProjectArchiveFlagBySlug(ctx context.Context, arg UpdateProjectArchiveFlagBySlugParams) error
	// Full-record update: UI saves the entire edited row so absent
	// fields mean "cleared". Intentionally does NOT touch
	// last_fired_at — that's bookkeeping the ticker owns.
	UpdateProjectCron(ctx context.Context, arg UpdateProjectCronParams) error
	UpdateRunnerProfile(ctx context.Context, arg UpdateRunnerProfileParams) error
	// Project-level poll fallback applied to the synthesized implicit
	// material. Zero nanoseconds disables polling (default). UI at
	// /projects/{slug}/settings writes through this. updated_at only
	// bumps because poll changes are rare but operationally visible.
	UpdateScmSourcePollInterval(ctx context.Context, arg UpdateScmSourcePollIntervalParams) error
	// Stamp the last successful config sync. Called after a drift re-apply so
	// operators can see whether the live config tracks HEAD.
	UpdateScmSourceSynced(ctx context.Context, arg UpdateScmSourceSyncedParams) error
	// Rotation path. Takes the newly sealed ciphertext and bumps
	// updated_at. Intended for POST /api/v1/projects/{slug}/scm-sources
	// /{id}/rotate-webhook-secret.
	UpdateScmSourceWebhookSecret(ctx context.Context, arg UpdateScmSourceWebhookSecretParams) error
	UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) error
	// Flip a user's role. The CHECK constraint on the column enforces
	// the enum; an admin calling this with a typo'd value gets a clean
	// error from Postgres instead of a silent wrong-role write.
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error)
	// ON CONFLICT (name) DO UPDATE bumps kind + display + id/secret
	// + issuer + api base + enabled. We never update created_at.
	UpsertAuthProvider(ctx context.Context, arg UpsertAuthProviderParams) (AuthProvider, error)
	// Records a fire time for a cron material. The ticker calls this
	// right after dispatching a run so a crashed server doesn't re-
	// fire the same tick when it comes back.
	UpsertCronFired(ctx context.Context, arg UpsertCronFiredParams) error
	// Called right after CreateCheckRun on GitHub responds; caller may
	// already have an entry from a previous retry so we upsert rather
	// than insert. updated_at bumps so we can spot stale rows later.
	UpsertGithubCheckRun(ctx context.Context, arg UpsertGithubCheckRunParams) error
	// Global scope: project_id = NULL, shadowed by a same-name project
	// secret at resolution time. Targets the partial UNIQUE index
	// secrets_global_name_idx — Postgres can't infer partial indexes
	// from ON CONFLICT (name) alone, so we spell out the predicate.
	UpsertGlobalSecret(ctx context.Context, arg UpsertGlobalSecretParams) (UpsertGlobalSecretRow, error)
	// Create/update a local account. Called from the CLI and the
	// admin self-service change-password endpoint. external_id is
	// the email so the (provider, external_id) unique key covers us.
	UpsertLocalUser(ctx context.Context, arg UpsertLocalUserParams) (UpsertLocalUserRow, error)
	UpsertMaterial(ctx context.Context, arg UpsertMaterialParams) (UpsertMaterialRow, error)
	// Records the outcome of one poll. Three cases, same query:
	//  - success, unchanged HEAD: last_head_sha unchanged, error NULL
	//  - success, new HEAD:       last_head_sha advanced,  error NULL
	//  - failure:                 last_head_sha unchanged (callers pass
	//                             the prior value), error message set
	// The "unchanged prior value" contract keeps the UI display
	// stable across transient provider blips — operators see the
	// last-known-good SHA alongside the error rather than a blank.
	UpsertMaterialPollState(ctx context.Context, arg UpsertMaterialPollStateParams) error
	UpsertPipeline(ctx context.Context, arg UpsertPipelineParams) (UpsertPipelineRow, error)
	// Idempotent write. Replaces value + credentials_enc on key
	// collision. updated_at refreshes on every write so audit / UI
	// "last changed" stays honest.
	UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error)
	// config_path defaults to '.gocdnext' at the SQL level. Apply
	// callers that don't set it (legacy path, drift re-apply) get
	// that default naturally via COALESCE on the column-side default.
	// Callers that DO set it override via ON CONFLICT.
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (UpsertProjectRow, error)
	// Insert-or-rotate. ON CONFLICT flips auth_ref_encrypted + api_base
	// + display_name but preserves id + created_at + created_by so
	// audit trails point to the original provisioning.
	UpsertSCMCredential(ctx context.Context, arg UpsertSCMCredentialParams) (UpsertSCMCredentialRow, error)
	// Bind a project to its SCM source. updated_at only bumps when
	// something meaningful changes, so idempotent re-applies don't
	// spam the timeline. webhook_secret and auth_ref both use
	// COALESCE "sticky" semantics: sending NULL means "keep the
	// existing value" so a re-apply that didn't re-enter the PAT
	// doesn't wipe the stored one. Rotation is explicit — callers
	// pass the new value to overwrite.
	UpsertScmSource(ctx context.Context, arg UpsertScmSourceParams) (UpsertScmSourceRow, error)
	// Upserts a (project_id, name) -> value_enc pair. updated_at always bumps on
	// update because the ciphertext changes (random nonce) even for identical
	// plaintext, making a "was this changed" diff unreliable; we bump
	// unconditionally on write.
	//
	// Targets the partial UNIQUE index secrets_project_name_idx (rows
	// where project_id IS NOT NULL). The global twin lives in
	// UpsertGlobalSecret below.
	UpsertSecret(ctx context.Context, arg UpsertSecretParams) (UpsertSecretRow, error)
	// Upsert the service tracking row for a (run_id, name) tuple.
	// Idempotent: re-issuing the same status is a no-op besides
	// updating started_at/ready_at/stopped_at as appropriate.
	//
	// Status transition shape:
	//   starting → ready → stopped
	//          ↘ failed   ↗ stopped
	// We don't enforce the order in SQL — the agent is the source of
	// truth, and a malformed sequence (e.g. `ready` arriving before
	// `starting` after a stream reconnect) is harmless: the row ends
	// up with both timestamps set, the UI renders the later state.
	// Guarding ready_at and stopped_at with COALESCE means an idempotent
	// re-send of `ready` doesn't reset the first-observed timestamp.
	UpsertServiceRun(ctx context.Context, arg UpsertServiceRunParams) (ServiceRun, error)
	// Either inserts a fresh row (new login) or bumps the profile
	// fields we pull from the IdP every time. Role is intentionally
	// NOT overwritten on conflict — it's admin-assigned and must not
	// revert to 'user' just because the IdP doesn't carry it.
	UpsertUserByProvider(ctx context.Context, arg UpsertUserByProviderParams) (UpsertUserByProviderRow, error)
	// Writes the full preferences document for a user. Upsert so the
	// caller doesn't have to branch on "first save vs. update" — the
	// web action uses a PUT-style full-document replace, not a
	// field-level merge, so this is the only write the domain needs.
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UpsertUserPreferencesRow, error)
	// ON CONFLICT (name) DO UPDATE refreshes every field EXCEPT
	// private_key + webhook_secret when the caller passes NULL.
	// The handler interprets an empty string from the dialog as
	// "keep existing ciphertext", mirroring auth_providers.
	UpsertVCSIntegration(ctx context.Context, arg UpsertVCSIntegrationParams) (VcsIntegration, error)
	// Median wait time per upstream→downstream edge in the project's
	// VSM. Wait = downstream.started_at − upstream.finished_at, over
	// terminal-or-dispatched runs where cause='upstream' and the
	// cause_detail's upstream_run_id resolves to a real upstream run.
	// Grouping by (from_pipeline_id, to_pipeline_id) so multiple edges
	// from the same upstream to different downstreams each get their
	// own median — the VSM graph labels arrows with these numbers.
	VSMEdgeTimingByProjectSlug(ctx context.Context, arg VSMEdgeTimingByProjectSlugParams) ([]VSMEdgeTimingByProjectSlugRow, error)
}

var _ Querier = (*Queries)(nil)
