// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runner_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRunnerProfile = `-- name: DeleteRunnerProfile :exec
DELETE FROM runner_profiles WHERE id = $1
`

// Caller MUST check no pipeline definition references this profile
// before issuing the delete; the scheduler resolves profiles by
// name at dispatch and a missing name fails the run.
func (q *Queries) DeleteRunnerProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunnerProfile, id)
	return err
}

const getRunnerProfile = `-- name: GetRunnerProfile :one
SELECT id, name, description, engine,
       default_image,
       default_cpu_request, default_cpu_limit,
       default_mem_request, default_mem_limit,
       max_cpu, max_mem,
       tags, config,
       created_at, updated_at
FROM runner_profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRunnerProfile(ctx context.Context, id pgtype.UUID) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, getRunnerProfile, id)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.DefaultImage,
		&i.DefaultCpuRequest,
		&i.DefaultCpuLimit,
		&i.DefaultMemRequest,
		&i.DefaultMemLimit,
		&i.MaxCpu,
		&i.MaxMem,
		&i.Tags,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunnerProfileByName = `-- name: GetRunnerProfileByName :one
SELECT id, name, description, engine,
       default_image,
       default_cpu_request, default_cpu_limit,
       default_mem_request, default_mem_limit,
       max_cpu, max_mem,
       tags, config,
       created_at, updated_at
FROM runner_profiles
WHERE name = $1
LIMIT 1
`

// Pipeline apply + scheduler dispatch both look up by name (the
// stable identifier in YAML), not by id, so renames are deliberate
// breaking changes — admins know what they're doing.
func (q *Queries) GetRunnerProfileByName(ctx context.Context, name string) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, getRunnerProfileByName, name)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.DefaultImage,
		&i.DefaultCpuRequest,
		&i.DefaultCpuLimit,
		&i.DefaultMemRequest,
		&i.DefaultMemLimit,
		&i.MaxCpu,
		&i.MaxMem,
		&i.Tags,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunnerProfile = `-- name: InsertRunnerProfile :one
INSERT INTO runner_profiles (
    name, description, engine,
    default_image,
    default_cpu_request, default_cpu_limit,
    default_mem_request, default_mem_limit,
    max_cpu, max_mem,
    tags, config
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6,
    $7, $8,
    $9, $10,
    $11, $12
)
RETURNING id, name, description, engine,
          default_image,
          default_cpu_request, default_cpu_limit,
          default_mem_request, default_mem_limit,
          max_cpu, max_mem,
          tags, config,
          created_at, updated_at
`

type InsertRunnerProfileParams struct {
	Name              string
	Description       string
	Engine            string
	DefaultImage      string
	DefaultCpuRequest string
	DefaultCpuLimit   string
	DefaultMemRequest string
	DefaultMemLimit   string
	MaxCpu            string
	MaxMem            string
	Tags              []string
	Config            []byte
}

func (q *Queries) InsertRunnerProfile(ctx context.Context, arg InsertRunnerProfileParams) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, insertRunnerProfile,
		arg.Name,
		arg.Description,
		arg.Engine,
		arg.DefaultImage,
		arg.DefaultCpuRequest,
		arg.DefaultCpuLimit,
		arg.DefaultMemRequest,
		arg.DefaultMemLimit,
		arg.MaxCpu,
		arg.MaxMem,
		arg.Tags,
		arg.Config,
	)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Engine,
		&i.DefaultImage,
		&i.DefaultCpuRequest,
		&i.DefaultCpuLimit,
		&i.DefaultMemRequest,
		&i.DefaultMemLimit,
		&i.MaxCpu,
		&i.MaxMem,
		&i.Tags,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunnerProfiles = `-- name: ListRunnerProfiles :many
SELECT id, name, description, engine,
       default_image,
       default_cpu_request, default_cpu_limit,
       default_mem_request, default_mem_limit,
       max_cpu, max_mem,
       tags, config,
       created_at, updated_at
FROM runner_profiles
ORDER BY name
`

// Admin UI hot path. Sorted by name so the table reads alphabetical.
func (q *Queries) ListRunnerProfiles(ctx context.Context) ([]RunnerProfile, error) {
	rows, err := q.db.Query(ctx, listRunnerProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunnerProfile{}
	for rows.Next() {
		var i RunnerProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Engine,
			&i.DefaultImage,
			&i.DefaultCpuRequest,
			&i.DefaultCpuLimit,
			&i.DefaultMemRequest,
			&i.DefaultMemLimit,
			&i.MaxCpu,
			&i.MaxMem,
			&i.Tags,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunnerProfile = `-- name: UpdateRunnerProfile :exec
UPDATE runner_profiles
SET name = $2,
    description = $3,
    engine = $4,
    default_image = $5,
    default_cpu_request = $6, default_cpu_limit = $7,
    default_mem_request = $8, default_mem_limit = $9,
    max_cpu = $10, max_mem = $11,
    tags = $12,
    config = $13,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRunnerProfileParams struct {
	ID                pgtype.UUID
	Name              string
	Description       string
	Engine            string
	DefaultImage      string
	DefaultCpuRequest string
	DefaultCpuLimit   string
	DefaultMemRequest string
	DefaultMemLimit   string
	MaxCpu            string
	MaxMem            string
	Tags              []string
	Config            []byte
}

func (q *Queries) UpdateRunnerProfile(ctx context.Context, arg UpdateRunnerProfileParams) error {
	_, err := q.db.Exec(ctx, updateRunnerProfile,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Engine,
		arg.DefaultImage,
		arg.DefaultCpuRequest,
		arg.DefaultCpuLimit,
		arg.DefaultMemRequest,
		arg.DefaultMemLimit,
		arg.MaxCpu,
		arg.MaxMem,
		arg.Tags,
		arg.Config,
	)
	return err
}
