// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runs_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveRun = `-- name: CancelActiveRun :one
UPDATE runs
SET status = 'canceled',
    finished_at = COALESCE(finished_at, NOW()),
    queue_reason = NULL
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id, service_generation
`

type CancelActiveRunRow struct {
	ID                pgtype.UUID
	ServiceGeneration int64
}

// Flips a run to 'canceled' only if it was still active. Idempotent:
// a second call on a terminal run returns no rows so the handler
// can answer 409. Returns the row id so the caller can tell the
// update happened.
//
// queue_reason is cleared in the same UPDATE so a canceled-while-
// queued run doesn't carry a "waiting on #N" message into the
// runs list. Doing it in this UPDATE (vs a follow-up
// ClearRunQueueReason call) keeps the cancel atomic and saves a
// round-trip.
// service_generation returned in the SAME UPDATE (#97): the cancel cleanup carries it
// as max_generation, so a rerun that revives this run into a higher generation keeps
// its fresh pods. Capturing it atomically with the flip to canceled (not a separate
// post-cancel read) closes the window where a revive bumps it before the read.
func (q *Queries) CancelActiveRun(ctx context.Context, id pgtype.UUID) (CancelActiveRunRow, error) {
	row := q.db.QueryRow(ctx, cancelActiveRun, id)
	var i CancelActiveRunRow
	err := row.Scan(&i.ID, &i.ServiceGeneration)
	return i, err
}

const cancelQueuedJobRun = `-- name: CancelQueuedJobRun :one
UPDATE job_runs
SET status      = 'canceled',
    finished_at = COALESCE(finished_at, NOW())
WHERE id = $1 AND status = 'queued'
RETURNING id
`

// Flips a single job_run to 'canceled' ONLY when it's still queued.
// `running` jobs go through the agent's gRPC CancelJob → JobResult
// path so the audit trail records the actual stop time. Returns the
// row id so the caller can tell whether the update happened (the
// predicate could miss in a race with the scheduler dispatch path).
//
// We DON'T pre-fill exit_code or error here — those columns are
// agent-driven on running cancels, and for a queued cancel the
// absence of an exit_code is the honest signal ("never started").
func (q *Queries) CancelQueuedJobRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelQueuedJobRun, id)
	err := row.Scan(&id)
	return id, err
}

const claimSupersedeEffects = `-- name: ClaimSupersedeEffects :one
WITH cur AS (
    SELECT runs.id AS run_id,
           runs.supersede_effects_claimed_at AS prev_claim,
           runs.supersede_effects_at AS effects_at,
           runs.superseded_by AS superseded_by
    FROM runs WHERE runs.id = $1 FOR UPDATE
)
UPDATE runs r
SET supersede_effects_claimed_at = NOW()
FROM cur
WHERE r.id = cur.run_id
  AND cur.superseded_by IS NOT NULL
  AND cur.effects_at IS NULL
  AND (cur.prev_claim IS NULL
       OR cur.prev_claim < NOW() - $2::INTERVAL)
RETURNING (cur.prev_claim IS NULL)::boolean AS first_claim
`

type ClaimSupersedeEffectsParams struct {
	ID    pgtype.UUID
	Lease pgtype.Interval
}

// Claim the right to fire a superseded run's external effects. Succeeds when the
// effects aren't already done AND no LIVE claim holds it — a claim older than the
// lease is reclaimable (the prior claimer crashed mid-effects). Stamps claimed_at
// so a concurrent replica/replay backs off. Exactly-one-claimer is what stops
// duplicate audit across replicas; a returned row means "you own the effects now".
//
// Returns first_claim = whether this is the FIRST-ever claim (no prior claimed_at)
// vs a lease-expiry RECLAIM. The CTE reads the pre-update claimed_at under FOR
// UPDATE so the caller can count gocdnext_runs_superseded_total exactly once per
// supersede event — a reclaim that re-fires effects (e.g. cleanup had no target yet)
// must not re-count. (A run revived then re-superseded clears claimed_at, so its
// next first claim counts again — correctly, it's a new supersede event.)
func (q *Queries) ClaimSupersedeEffects(ctx context.Context, arg ClaimSupersedeEffectsParams) (bool, error) {
	row := q.db.QueryRow(ctx, claimSupersedeEffects, arg.ID, arg.Lease)
	var first_claim bool
	err := row.Scan(&first_claim)
	return first_claim, err
}

const countPassedGates = `-- name: CountPassedGates :one
SELECT count(*) FROM job_runs
WHERE run_id = $1 AND name = ANY($2::text[]) AND approval_gate = true AND status = 'success'
`

type CountPassedGatesParams struct {
	RunID   pgtype.UUID
	Column2 []string
}

// How many of the named approval gates of a run have reached 'success'. The marker
// for an env is written only when this equals the count of gates governing it (all
// governing gates passed) — the just-approved gate is visible as success in the
// caller's tx. Gates are never matrix (parser rejects approval+matrix), so name
// uniquely identifies each gate's job_run.
func (q *Queries) CountPassedGates(ctx context.Context, arg CountPassedGatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPassedGates, arg.RunID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRunGatePassForEnvs = `-- name: DeleteRunGatePassForEnvs :exec
DELETE FROM run_gate_pass WHERE run_id = $1 AND environment = ANY($2::text[])
`

type DeleteRunGatePassForEnvsParams struct {
	RunID   pgtype.UUID
	Column2 []string
}

// Drop a run's gate-pass markers for the given envs — used on rerun-revive, when a
// re-armed gate makes the run's "cleared env" claim stale. Scoped to the run + the
// specific envs so markers for still-passed (upstream) gates survive.
func (q *Queries) DeleteRunGatePassForEnvs(ctx context.Context, arg DeleteRunGatePassForEnvsParams) error {
	_, err := q.db.Exec(ctx, deleteRunGatePassForEnvs, arg.RunID, arg.Column2)
	return err
}

const emitRunSupersededAudit = `-- name: EmitRunSupersededAudit :exec
INSERT INTO audit_events (actor_id, actor_email, action, target_type, target_id, metadata)
VALUES (NULL, '', 'run.superseded', 'run', $1, $2)
ON CONFLICT (target_id) WHERE action = 'run.superseded' DO NOTHING
`

type EmitRunSupersededAuditParams struct {
	TargetID string
	Metadata []byte
}

// Idempotent run.superseded audit — system actor, counters + superseding id only
// (never a branch/ref value). The partial unique index (target_id WHERE
// action='run.superseded') makes a second writer — a racing replica or a
// lease-expiry replay — a clean no-op.
func (q *Queries) EmitRunSupersededAudit(ctx context.Context, arg EmitRunSupersededAuditParams) error {
	_, err := q.db.Exec(ctx, emitRunSupersededAudit, arg.TargetID, arg.Metadata)
	return err
}

const getJobRunForCancel = `-- name: GetJobRunForCancel :one
SELECT id, run_id, stage_run_id, name, status, agent_id, attempt, cancel_requested_at
FROM job_runs
WHERE id = $1
FOR UPDATE
`

type GetJobRunForCancelRow struct {
	ID                pgtype.UUID
	RunID             pgtype.UUID
	StageRunID        pgtype.UUID
	Name              string
	Status            string
	AgentID           pgtype.UUID
	Attempt           int32
	CancelRequestedAt pgtype.Timestamptz
}

// Thin row used by the job-scoped cancel handler. Returns the
// structural pointers cancel needs (run_id, stage_run_id) plus the
// decision inputs (status, agent_id) — `running` jobs are signaled
// via gRPC (handler dispatches CancelJob), `queued` jobs flip
// directly here and feed cascadeAfterJobCompletion. Distinguishes
// "not found" from "already terminal" via pgx.ErrNoRows vs the
// status check in the caller.
//
// `FOR UPDATE` serialises against the scheduler's
// ClaimJobForDispatch (which writes status='running' + agent_id
// inside its own tx). Without the lock, a job_run that's queued
// when we SELECT can be dispatched by the time CancelQueuedJobRun
// UPDATEs — the UPDATE misses the predicate, we return 409
// "already terminal" while the job is actually running. With the
// lock, exactly one of (cancel commits / dispatch commits) wins;
// the loser sees the post-commit state and routes correctly.
func (q *Queries) GetJobRunForCancel(ctx context.Context, id pgtype.UUID) (GetJobRunForCancelRow, error) {
	row := q.db.QueryRow(ctx, getJobRunForCancel, id)
	var i GetJobRunForCancelRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageRunID,
		&i.Name,
		&i.Status,
		&i.AgentID,
		&i.Attempt,
		&i.CancelRequestedAt,
	)
	return i, err
}

const getLatestModificationForPipeline = `-- name: GetLatestModificationForPipeline :one
SELECT m.id, m.material_id, m.revision, m.branch
FROM modifications m
JOIN materials mat ON mat.id = m.material_id
WHERE mat.pipeline_id = $1
ORDER BY m.detected_at DESC
LIMIT 1
`

type GetLatestModificationForPipelineRow struct {
	ID         int64
	MaterialID pgtype.UUID
	Revision   string
	Branch     *string
}

// Most recent modification across any material attached to a
// pipeline. Powers "trigger latest" for manual runs. Ordered by
// detected_at so the newest webhook delivery wins even when the
// committer timestamp is older (rebases, fast-forwards of older
// commits).
func (q *Queries) GetLatestModificationForPipeline(ctx context.Context, pipelineID pgtype.UUID) (GetLatestModificationForPipelineRow, error) {
	row := q.db.QueryRow(ctx, getLatestModificationForPipeline, pipelineID)
	var i GetLatestModificationForPipelineRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Revision,
		&i.Branch,
	)
	return i, err
}

const getRunForAction = `-- name: GetRunForAction :one
SELECT id, pipeline_id, status, revisions, cause, cause_detail
FROM runs
WHERE id = $1
`

type GetRunForActionRow struct {
	ID          pgtype.UUID
	PipelineID  pgtype.UUID
	Status      string
	Revisions   []byte
	Cause       string
	CauseDetail []byte
}

// Thin row used by cancel/rerun handlers to check status + find the
// pipeline + revisions without pulling the whole detail query. cause +
// cause_detail let RerunRun reproduce the original run's CI-var context
// (CI_TAG_NAME, CI_CAUSE, PR metadata) instead of demoting it to manual.
func (q *Queries) GetRunForAction(ctx context.Context, id pgtype.UUID) (GetRunForActionRow, error) {
	row := q.db.QueryRow(ctx, getRunForAction, id)
	var i GetRunForActionRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Status,
		&i.Revisions,
		&i.Cause,
		&i.CauseDetail,
	)
	return i, err
}

const getRunServiceGeneration = `-- name: GetRunServiceGeneration :one
SELECT service_generation FROM runs WHERE id = $1
`

// Current service_generation of a run (#97). Read INSIDE the completion tx by
// cascadeAfterJobCompletion so the run-terminal service cleanup carries the pre-revive
// generation (a rerun that revives the run into a higher generation keeps its fresh
// pods). The API-cancel path captures its own generation via CancelActiveRun's
// RETURNING; the supersede path uses GetSupersededRunGeneration.
func (q *Queries) GetRunServiceGeneration(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRunServiceGeneration, id)
	var service_generation int64
	err := row.Scan(&service_generation)
	return service_generation, err
}

const getRunSupersedeContext = `-- name: GetRunSupersedeContext :one
SELECT pipeline_id, definition, ref, counter
FROM runs
WHERE id = $1
`

type GetRunSupersedeContextRow struct {
	PipelineID pgtype.UUID
	Definition []byte
	Ref        string
	Counter    int64
}

// Run's OWN definition snapshot (migration 00067) + lane key (ref) + order
// (counter), for the cascade supersede fire and the gate-pass marker. Reads
// runs.definition — NOT pipelines.definition — so gate->env resolution matches the
// shape the run was materialised from even after a later ApplyProject edits the
// live pipeline.
func (q *Queries) GetRunSupersedeContext(ctx context.Context, id pgtype.UUID) (GetRunSupersedeContextRow, error) {
	row := q.db.QueryRow(ctx, getRunSupersedeContext, id)
	var i GetRunSupersedeContextRow
	err := row.Scan(
		&i.PipelineID,
		&i.Definition,
		&i.Ref,
		&i.Counter,
	)
	return i, err
}

const getStageRunOrdinal = `-- name: GetStageRunOrdinal :one
SELECT ordinal FROM stage_runs WHERE id = $1
`

// The 0-based ordinal of a stage_run within its run. The cascade fire uses the
// just-completed stage's ordinal to find the NEXT stage's ready gates.
func (q *Queries) GetStageRunOrdinal(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getStageRunOrdinal, id)
	var ordinal int32
	err := row.Scan(&ordinal)
	return ordinal, err
}

const getSupersededRunGeneration = `-- name: GetSupersededRunGeneration :one
SELECT service_generation FROM runs WHERE id = $1 AND superseded_by IS NOT NULL
`

// The service_generation of a run ONLY while it is still superseded (#97). Returns
// no row once RerunJob revives it (clears superseded_by). The supersede cleanup uses
// this as a combined "still superseded?" + "which generation am I tearing down?" read:
// gating the generation on superseded_by IN ONE ROW is load-bearing, because a revive
// clears superseded_by AND bumps service_generation in a single UPDATE — reading the
// two separately could straddle the revive and tear down the revived generation's pods.
func (q *Queries) GetSupersededRunGeneration(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSupersededRunGeneration, id)
	var service_generation int64
	err := row.Scan(&service_generation)
	return service_generation, err
}

const insertRunGatePass = `-- name: InsertRunGatePass :exec
INSERT INTO run_gate_pass (run_id, pipeline_id, ref, counter, environment)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, environment) DO NOTHING
`

type InsertRunGatePassParams struct {
	RunID       pgtype.UUID
	PipelineID  pgtype.UUID
	Ref         string
	Counter     int64
	Environment string
}

// Record that a run cleared the approval gate(s) governing a concrete deploy env
// (#97 Phase 2). Written at approve time under the lane-env advisory lock; the
// dispatch backstop reads it to refuse a stale deploy. ON CONFLICT DO NOTHING makes
// a re-approve / replica race idempotent (a run passes a given env exactly once).
func (q *Queries) InsertRunGatePass(ctx context.Context, arg InsertRunGatePassParams) error {
	_, err := q.db.Exec(ctx, insertRunGatePass,
		arg.RunID,
		arg.PipelineID,
		arg.Ref,
		arg.Counter,
		arg.Environment,
	)
	return err
}

const listAwaitingGateNamesForRun = `-- name: ListAwaitingGateNamesForRun :many
SELECT name FROM job_runs
WHERE run_id = $1 AND approval_gate = true AND status = 'awaiting_approval'
`

// The names of a run's still-pending approval gates. Supersede resolves the
// deploy environments a run is awaiting clearance for from these (via the
// gate-governance graph), to intersect against the newer run's ready gate.
func (q *Queries) ListAwaitingGateNamesForRun(ctx context.Context, runID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAwaitingGateNamesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCancelsForAgent = `-- name: ListPendingCancelsForAgent :many
SELECT id, run_id
FROM job_runs
WHERE agent_id = $1
  AND status = 'running'
  AND cancel_requested_at IS NOT NULL
`

type ListPendingCancelsForAgentRow struct {
	ID    pgtype.UUID
	RunID pgtype.UUID
}

// The agent calls this right after Register + Connect lands so
// it picks up any cancels that were requested while its session
// was being recycled. Returns (job_run_id, run_id) pairs the
// agent can issue local-cancel-equivalent handling on. The
// agent then sends the usual JobResult(status=canceled) to
// close out each row server-side — the existing result handler
// finalises the status, and the cancel_requested_at column
// becomes operationally redundant on that row (kept for the
// audit trail's at-time).
//
// Hits the partial index job_runs_pending_cancel_by_agent_idx;
// index-only on the WHERE clause makes this a sub-millisecond
// lookup even on a job_runs table in the millions.
func (q *Queries) ListPendingCancelsForAgent(ctx context.Context, agentID pgtype.UUID) ([]ListPendingCancelsForAgentRow, error) {
	rows, err := q.db.Query(ctx, listPendingCancelsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCancelsForAgentRow{}
	for rows.Next() {
		var i ListPendingCancelsForAgentRow
		if err := rows.Scan(&i.ID, &i.RunID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSupersedeEffects = `-- name: ListPendingSupersedeEffects :many
SELECT id FROM runs
WHERE superseded_by IS NOT NULL AND supersede_effects_at IS NULL
  AND (supersede_effects_claimed_at IS NULL
       OR supersede_effects_claimed_at < NOW() - $1::INTERVAL)
ORDER BY finished_at
LIMIT $2
`

type ListPendingSupersedeEffectsParams struct {
	Lease   pgtype.Interval
	MaxRows int32
}

// Superseded runs whose effects haven't completed AND are claimable right now — the
// replay work-list (missed NOTIFY or a claim past its lease). Filtering out LIVE
// claims (within the lease) matters: with LIMIT, a block of in-flight claims would
// otherwise starve later never-notified rows. Oldest-first, bounded. Rides
// runs_supersede_effects_pending_idx.
func (q *Queries) ListPendingSupersedeEffects(ctx context.Context, arg ListPendingSupersedeEffectsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingSupersedeEffects, arg.Lease, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningCancelRequestedForRun = `-- name: ListRunningCancelRequestedForRun :many
SELECT id, agent_id
FROM job_runs
WHERE run_id = $1
  AND status = 'running'
  AND agent_id IS NOT NULL
  AND cancel_requested_at IS NOT NULL
`

type ListRunningCancelRequestedForRunRow struct {
	ID      pgtype.UUID
	AgentID pgtype.UUID
}

// Running jobs of a run that carry a pending cancel intent (supersede stamped
// cancel_requested_at). The supersede effects listener pushes a CancelJob frame
// per row so the container stops promptly instead of waiting for the agent's next
// reconnect. agent_id is non-null by the predicate, so the listener can address a
// frame to it directly.
func (q *Queries) ListRunningCancelRequestedForRun(ctx context.Context, runID pgtype.UUID) ([]ListRunningCancelRequestedForRunRow, error) {
	rows, err := q.db.Query(ctx, listRunningCancelRequestedForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningCancelRequestedForRunRow{}
	for rows.Next() {
		var i ListRunningCancelRequestedForRunRow
		if err := rows.Scan(&i.ID, &i.AgentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSupersedeEffectsDone = `-- name: MarkSupersedeEffectsDone :exec
UPDATE runs SET supersede_effects_at = NOW()
WHERE id = $1 AND superseded_by IS NOT NULL
`

// Mark a superseded run's DURABLE effects COMPLETE (cleanup + audit resolved), after
// which the replay stops retrying. Guarded on superseded_by so the method can't mark
// a non-superseded row done if ever misused. Until this lands the replay keeps
// retrying (via the lease), so a crash — or a cleanup that had no target yet — is
// recovered rather than silently dropped.
func (q *Queries) MarkSupersedeEffectsDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSupersedeEffectsDone, id)
	return err
}

const reclaimPendingCancelsForOfflineAgent = `-- name: ReclaimPendingCancelsForOfflineAgent :many
UPDATE job_runs jr
SET status      = 'canceled',
    finished_at = COALESCE(finished_at, NOW())
FROM agents a
WHERE jr.agent_id = a.id
  AND jr.status = 'running'
  AND jr.cancel_requested_at IS NOT NULL
  AND (
        a.status = 'offline'
        OR a.last_seen_at IS NULL
        OR a.last_seen_at < NOW() - $1::INTERVAL
      )
RETURNING jr.id, jr.run_id, jr.stage_run_id, jr.agent_id, jr.cancel_requested_at, jr.name
`

type ReclaimPendingCancelsForOfflineAgentRow struct {
	ID                pgtype.UUID
	RunID             pgtype.UUID
	StageRunID        pgtype.UUID
	AgentID           pgtype.UUID
	CancelRequestedAt pgtype.Timestamptz
	Name              string
}

// The reaper's path for cancels that never reached an agent
// because the agent went offline and stayed offline past the
// cancel grace window. Finalises every still-running row that
// belongs to an offline agent AND was cancel-requested as
// 'canceled' with finished_at=NOW().
//
// Why this lives in the reaper (not a hot path):
//
//   - The hot path (cancel handler) does not block on agent
//     liveness — it stamps cancel_requested_at and returns
//     202 immediately. The DB row stays 'running' from the
//     handler's perspective; the reaper does the finalising
//     when it's clear the agent isn't coming back.
//
//   - Latency of cancel finalisation = reaper tick interval +
//     offline-grace window. Both are operator-tunable; default
//     is ~5min total. Acceptable for a "we tried, agent gone"
//     case; the operator-visible status is 'canceling' in the
//     meantime via the cancel_requested_at column.
//
// Liveness predicate mirrors the reaper's main path
// (ListStaleRunningJobs in sweeper.sql) so a heartbeat-stale
// agent that's still marked online doesn't accumulate
// cancel-pending rows forever. Three failure shapes catch
// everything except a perfectly healthy agent the replay path
// still owns:
//
//  1. a.status = 'offline'  — explicit liveness flip; the
//     Connect-defer or the reaper has marked the row offline.
//  2. a.last_seen_at IS NULL — agent never sent a heartbeat
//     since this server started; either fresh-DB state or a
//     truly dead row.
//  3. a.last_seen_at < NOW() - grace — heartbeat stopped past
//     the grace window. agents.status may still be 'online'
//     if the offline-mark never fired (network partition;
//     Connect-defer crashed), but the heartbeat signal is
//     gone for real.
//
// A perfectly healthy agent (status=online AND last_seen_at
// recent) is skipped — the replay path is still expected to
// land the cancel on its next Connect frame.
func (q *Queries) ReclaimPendingCancelsForOfflineAgent(ctx context.Context, graceInterval pgtype.Interval) ([]ReclaimPendingCancelsForOfflineAgentRow, error) {
	rows, err := q.db.Query(ctx, reclaimPendingCancelsForOfflineAgent, graceInterval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReclaimPendingCancelsForOfflineAgentRow{}
	for rows.Next() {
		var i ReclaimPendingCancelsForOfflineAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageRunID,
			&i.AgentID,
			&i.CancelRequestedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runHasSupersededBy = `-- name: RunHasSupersededBy :one
SELECT (superseded_by IS NOT NULL)::boolean FROM runs WHERE id = $1
`

// Whether a run is still marked superseded. The effects worker re-checks this right
// before the DESTRUCTIVE service cleanup: RerunJob can revive a run (clearing
// superseded_by) after a worker claimed its effects, and a stale cleanup keyed on
// the same run_id would delete the revived run's pods.
func (q *Queries) RunHasSupersededBy(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, runHasSupersededBy, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const stampCancelRequestedAt = `-- name: StampCancelRequestedAt :one
UPDATE job_runs
SET cancel_requested_at = COALESCE(cancel_requested_at, NOW())
WHERE id = $1
  AND status = 'running'
  AND agent_id IS NOT NULL
RETURNING id, agent_id, cancel_requested_at
`

type StampCancelRequestedAtRow struct {
	ID                pgtype.UUID
	AgentID           pgtype.UUID
	CancelRequestedAt pgtype.Timestamptz
}

// Persists the cancel INTENT on a running job_run BEFORE the
// handler attempts the gRPC dispatch. Decouples the cancel UX
// from "is the agent's session alive in this instant" — even if
// Dispatch fails because of a Revoke→Register race (the agent
// pod is in flux), the intent survives. When the agent's new
// session comes up it calls ListPendingCancelsForAgent and
// honors the cancel; if it never comes back, the reaper
// finalises the row via ReclaimPendingCancelsForOfflineAgent.
//
// Idempotent on the timestamp: COALESCE keeps the FIRST cancel
// request's at-time so the audit trail matches the first click
// (a re-click that lands in the brief window between dispatch
// attempts shouldn't reset the requested-at clock).
//
// Predicate guards: only stamp when the row is STILL running
// AND has an agent_id pinned (no-op on rows that finished
// between the cancel handler's read and this write). The
// handler ran GetJobRunForCancel under FOR UPDATE in the same
// tx, so by definition the row was running at SELECT time —
// but a result handler in another tx can have committed in
// between if the cancel handler is using a separate tx. The
// guards keep us honest in either calling shape.
func (q *Queries) StampCancelRequestedAt(ctx context.Context, id pgtype.UUID) (StampCancelRequestedAtRow, error) {
	row := q.db.QueryRow(ctx, stampCancelRequestedAt, id)
	var i StampCancelRequestedAtRow
	err := row.Scan(&i.ID, &i.AgentID, &i.CancelRequestedAt)
	return i, err
}

const stampCancelRequestedAtForRun = `-- name: StampCancelRequestedAtForRun :many
UPDATE job_runs
SET cancel_requested_at = COALESCE(cancel_requested_at, NOW())
WHERE run_id = $1
  AND status = 'running'
  AND agent_id IS NOT NULL
RETURNING id, agent_id
`

type StampCancelRequestedAtForRunRow struct {
	ID      pgtype.UUID
	AgentID pgtype.UUID
}

// Batch variant of StampCancelRequestedAt used by the run-scoped
// cancel path. Stamps cancel_requested_at on EVERY running job
// belonging to the run that hasn't been stamped yet. The handler
// then attempts gRPC dispatch per row; any dispatch that lands in
// the Revoke→Register race window is rescued by the same replay
// + reaper paths that cover the job-scoped cancel.
//
// COALESCE preserves the FIRST stamp's at-time across re-cancel
// attempts (the same idempotency as the single-row variant).
// Returns (id, agent_id) per stamped row so the handler can
// correlate Dispatch failures with their owning agent.
func (q *Queries) StampCancelRequestedAtForRun(ctx context.Context, runID pgtype.UUID) ([]StampCancelRequestedAtForRunRow, error) {
	rows, err := q.db.Query(ctx, stampCancelRequestedAtForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StampCancelRequestedAtForRunRow{}
	for rows.Next() {
		var i StampCancelRequestedAtForRunRow
		if err := rows.Scan(&i.ID, &i.AgentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeCandidatesBranch = `-- name: SupersedeCandidatesBranch :many
SELECT r.id, r.counter
FROM runs r
WHERE r.pipeline_id = $1 AND r.ref = $2 AND r.counter < $3
  AND r.status IN ('queued', 'running')
  AND EXISTS (SELECT 1 FROM job_runs j
              WHERE j.run_id = r.id AND j.approval_gate = true AND j.status = 'awaiting_approval')
ORDER BY r.counter DESC
`

type SupersedeCandidatesBranchParams struct {
	PipelineID pgtype.UUID
	Ref        string
	Counter    int64
}

type SupersedeCandidatesBranchRow struct {
	ID      pgtype.UUID
	Counter int64
}

// Older pending runs in a (pipeline, ref) lane that still hold a pending gate —
// the supersede victim candidates for `supersede: branch`. counter DESC so
// concurrent supersede passes lock runs.id rows in one consistent descending
// order (current is the highest, already locked by its own tx) and can't cycle.
func (q *Queries) SupersedeCandidatesBranch(ctx context.Context, arg SupersedeCandidatesBranchParams) ([]SupersedeCandidatesBranchRow, error) {
	rows, err := q.db.Query(ctx, supersedeCandidatesBranch, arg.PipelineID, arg.Ref, arg.Counter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupersedeCandidatesBranchRow{}
	for rows.Next() {
		var i SupersedeCandidatesBranchRow
		if err := rows.Scan(&i.ID, &i.Counter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeCandidatesPipeline = `-- name: SupersedeCandidatesPipeline :many
SELECT r.id, r.counter
FROM runs r
WHERE r.pipeline_id = $1 AND r.counter < $2
  AND r.status IN ('queued', 'running')
  AND EXISTS (SELECT 1 FROM job_runs j
              WHERE j.run_id = r.id AND j.approval_gate = true AND j.status = 'awaiting_approval')
ORDER BY r.counter DESC
`

type SupersedeCandidatesPipelineParams struct {
	PipelineID pgtype.UUID
	Counter    int64
}

type SupersedeCandidatesPipelineRow struct {
	ID      pgtype.UUID
	Counter int64
}

// Same, for `supersede: pipeline` (lane ignores ref) — no ref predicate so it
// rides the (pipeline_id, counter) partial index.
func (q *Queries) SupersedeCandidatesPipeline(ctx context.Context, arg SupersedeCandidatesPipelineParams) ([]SupersedeCandidatesPipelineRow, error) {
	rows, err := q.db.Query(ctx, supersedeCandidatesPipeline, arg.PipelineID, arg.Counter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupersedeCandidatesPipelineRow{}
	for rows.Next() {
		var i SupersedeCandidatesPipelineRow
		if err := rows.Scan(&i.ID, &i.Counter); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeRun = `-- name: SupersedeRun :one
UPDATE runs
SET status = 'canceled',
    finished_at = COALESCE(finished_at, NOW()),
    queue_reason = NULL,
    superseded_by = $2,
    cancel_reason = $3
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id
`

type SupersedeRunParams struct {
	ID           pgtype.UUID
	SupersededBy pgtype.UUID
	CancelReason *string
}

// Latest-wins supersede (#97): flip an older pending run to canceled + stamp the
// superseding run id + reason. Same shape/guard as CancelActiveRun (idempotent —
// a second call on a terminal run returns 0 rows), plus superseded_by so the UI
// renders "superseded by #N" and the Phase-2 backstop's active-marker check can
// exclude it. cancel_reason cites the counter (#N) only — never a branch/ref value.
func (q *Queries) SupersedeRun(ctx context.Context, arg SupersedeRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, supersedeRun, arg.ID, arg.SupersededBy, arg.CancelReason)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const supersededAuditInfo = `-- name: SupersededAuditInfo :one
SELECT v.counter AS superseded_counter, v.superseded_by AS by_run_id, n.counter AS by_counter
FROM runs v JOIN runs n ON n.id = v.superseded_by
WHERE v.id = $1 AND v.superseded_by IS NOT NULL
`

type SupersededAuditInfoRow struct {
	SupersededCounter int64
	ByRunID           pgtype.UUID
	ByCounter         int64
}

// Counters for the run.superseded audit the effects listener emits: the victim's
// own counter, plus the superseding run's id + counter (via superseded_by). One
// row only when the run is actually superseded, so a spurious NOTIFY emits nothing.
func (q *Queries) SupersededAuditInfo(ctx context.Context, id pgtype.UUID) (SupersededAuditInfoRow, error) {
	row := q.db.QueryRow(ctx, supersededAuditInfo, id)
	var i SupersededAuditInfoRow
	err := row.Scan(&i.SupersededCounter, &i.ByRunID, &i.ByCounter)
	return i, err
}
