// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunsByPipeline = `-- name: CountRunsByPipeline :one
SELECT COUNT(*) FROM runs WHERE pipeline_id = $1
`

func (q *Queries) CountRunsByPipeline(ctx context.Context, pipelineID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunsByPipeline, pipelineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPipelineDefinition = `-- name: GetPipelineDefinition :one
SELECT id, project_id, name, definition, definition_version, config_path
FROM pipelines
WHERE id = $1
LIMIT 1
`

type GetPipelineDefinitionRow struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	Name              string
	Definition        []byte
	DefinitionVersion int32
	ConfigPath        string
}

func (q *Queries) GetPipelineDefinition(ctx context.Context, id pgtype.UUID) (GetPipelineDefinitionRow, error) {
	row := q.db.QueryRow(ctx, getPipelineDefinition, id)
	var i GetPipelineDefinitionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Definition,
		&i.DefinitionVersion,
		&i.ConfigPath,
	)
	return i, err
}

const insertJobRun = `-- name: InsertJobRun :one
INSERT INTO job_runs (run_id, stage_run_id, name, matrix_key, image, needs)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, stage_run_id, name, matrix_key, image, status, needs
`

type InsertJobRunParams struct {
	RunID      pgtype.UUID
	StageRunID pgtype.UUID
	Name       string
	MatrixKey  *string
	Image      *string
	Needs      []string
}

type InsertJobRunRow struct {
	ID         pgtype.UUID
	RunID      pgtype.UUID
	StageRunID pgtype.UUID
	Name       string
	MatrixKey  *string
	Image      *string
	Status     string
	Needs      []string
}

func (q *Queries) InsertJobRun(ctx context.Context, arg InsertJobRunParams) (InsertJobRunRow, error) {
	row := q.db.QueryRow(ctx, insertJobRun,
		arg.RunID,
		arg.StageRunID,
		arg.Name,
		arg.MatrixKey,
		arg.Image,
		arg.Needs,
	)
	var i InsertJobRunRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageRunID,
		&i.Name,
		&i.MatrixKey,
		&i.Image,
		&i.Status,
		&i.Needs,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO runs (
    pipeline_id, counter, cause, cause_detail, status, revisions, triggered_by
) VALUES (
    $1, $2, $3, $4, 'queued', $5, $6
)
RETURNING id, pipeline_id, counter, cause, status, created_at
`

type InsertRunParams struct {
	PipelineID  pgtype.UUID
	Counter     int64
	Cause       string
	CauseDetail []byte
	Revisions   []byte
	TriggeredBy *string
}

type InsertRunRow struct {
	ID         pgtype.UUID
	PipelineID pgtype.UUID
	Counter    int64
	Cause      string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (InsertRunRow, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.PipelineID,
		arg.Counter,
		arg.Cause,
		arg.CauseDetail,
		arg.Revisions,
		arg.TriggeredBy,
	)
	var i InsertRunRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Counter,
		&i.Cause,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertStageRun = `-- name: InsertStageRun :one
INSERT INTO stage_runs (run_id, name, ordinal)
VALUES ($1, $2, $3)
RETURNING id, run_id, name, ordinal, status
`

type InsertStageRunParams struct {
	RunID   pgtype.UUID
	Name    string
	Ordinal int32
}

type InsertStageRunRow struct {
	ID      pgtype.UUID
	RunID   pgtype.UUID
	Name    string
	Ordinal int32
	Status  string
}

func (q *Queries) InsertStageRun(ctx context.Context, arg InsertStageRunParams) (InsertStageRunRow, error) {
	row := q.db.QueryRow(ctx, insertStageRun, arg.RunID, arg.Name, arg.Ordinal)
	var i InsertStageRunRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Ordinal,
		&i.Status,
	)
	return i, err
}

const listJobRunsByRun = `-- name: ListJobRunsByRun :many
SELECT id, run_id, stage_run_id, name, matrix_key, image, status, needs
FROM job_runs
WHERE run_id = $1
ORDER BY name, matrix_key NULLS FIRST
`

type ListJobRunsByRunRow struct {
	ID         pgtype.UUID
	RunID      pgtype.UUID
	StageRunID pgtype.UUID
	Name       string
	MatrixKey  *string
	Image      *string
	Status     string
	Needs      []string
}

func (q *Queries) ListJobRunsByRun(ctx context.Context, runID pgtype.UUID) ([]ListJobRunsByRunRow, error) {
	rows, err := q.db.Query(ctx, listJobRunsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobRunsByRunRow{}
	for rows.Next() {
		var i ListJobRunsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageRunID,
			&i.Name,
			&i.MatrixKey,
			&i.Image,
			&i.Status,
			&i.Needs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageRunsByRun = `-- name: ListStageRunsByRun :many
SELECT id, run_id, name, ordinal, status
FROM stage_runs
WHERE run_id = $1
ORDER BY ordinal
`

type ListStageRunsByRunRow struct {
	ID      pgtype.UUID
	RunID   pgtype.UUID
	Name    string
	Ordinal int32
	Status  string
}

func (q *Queries) ListStageRunsByRun(ctx context.Context, runID pgtype.UUID) ([]ListStageRunsByRunRow, error) {
	rows, err := q.db.Query(ctx, listStageRunsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageRunsByRunRow{}
	for rows.Next() {
		var i ListStageRunsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Ordinal,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunCounter = `-- name: NextRunCounter :one
SELECT (COALESCE(MAX(counter), 0) + 1)::BIGINT AS next
FROM runs
WHERE pipeline_id = $1
`

func (q *Queries) NextRunCounter(ctx context.Context, pipelineID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextRunCounter, pipelineID)
	var next int64
	err := row.Scan(&next)
	return next, err
}
