// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runs_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveRun = `-- name: CancelActiveRun :one
UPDATE runs
SET status = 'canceled', finished_at = COALESCE(finished_at, NOW())
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id
`

// Flips a run to 'canceled' only if it was still active. Idempotent:
// a second call on a terminal run returns no rows so the handler
// can answer 409. Returns the row id so the caller can tell the
// update happened.
func (q *Queries) CancelActiveRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelActiveRun, id)
	err := row.Scan(&id)
	return id, err
}

const getLatestModificationForPipeline = `-- name: GetLatestModificationForPipeline :one
SELECT m.id, m.material_id, m.revision, m.branch
FROM modifications m
JOIN materials mat ON mat.id = m.material_id
WHERE mat.pipeline_id = $1
ORDER BY m.detected_at DESC
LIMIT 1
`

type GetLatestModificationForPipelineRow struct {
	ID         int64
	MaterialID pgtype.UUID
	Revision   string
	Branch     *string
}

// Most recent modification across any material attached to a
// pipeline. Powers "trigger latest" for manual runs. Ordered by
// detected_at so the newest webhook delivery wins even when the
// committer timestamp is older (rebases, fast-forwards of older
// commits).
func (q *Queries) GetLatestModificationForPipeline(ctx context.Context, pipelineID pgtype.UUID) (GetLatestModificationForPipelineRow, error) {
	row := q.db.QueryRow(ctx, getLatestModificationForPipeline, pipelineID)
	var i GetLatestModificationForPipelineRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Revision,
		&i.Branch,
	)
	return i, err
}

const getRunForAction = `-- name: GetRunForAction :one
SELECT id, pipeline_id, status, revisions
FROM runs
WHERE id = $1
`

type GetRunForActionRow struct {
	ID         pgtype.UUID
	PipelineID pgtype.UUID
	Status     string
	Revisions  []byte
}

// Thin row used by cancel/rerun handlers to check status + find the
// pipeline + revisions without pulling the whole detail query.
func (q *Queries) GetRunForAction(ctx context.Context, id pgtype.UUID) (GetRunForActionRow, error) {
	row := q.db.QueryRow(ctx, getRunForAction, id)
	var i GetRunForActionRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Status,
		&i.Revisions,
	)
	return i, err
}
