// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runs_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveRun = `-- name: CancelActiveRun :one
UPDATE runs
SET status = 'canceled',
    finished_at = COALESCE(finished_at, NOW()),
    queue_reason = NULL
WHERE id = $1 AND status IN ('queued', 'running')
RETURNING id
`

// Flips a run to 'canceled' only if it was still active. Idempotent:
// a second call on a terminal run returns no rows so the handler
// can answer 409. Returns the row id so the caller can tell the
// update happened.
//
// queue_reason is cleared in the same UPDATE so a canceled-while-
// queued run doesn't carry a "waiting on #N" message into the
// runs list. Doing it in this UPDATE (vs a follow-up
// ClearRunQueueReason call) keeps the cancel atomic and saves a
// round-trip.
func (q *Queries) CancelActiveRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelActiveRun, id)
	err := row.Scan(&id)
	return id, err
}

const cancelQueuedJobRun = `-- name: CancelQueuedJobRun :one
UPDATE job_runs
SET status      = 'canceled',
    finished_at = COALESCE(finished_at, NOW())
WHERE id = $1 AND status = 'queued'
RETURNING id
`

// Flips a single job_run to 'canceled' ONLY when it's still queued.
// `running` jobs go through the agent's gRPC CancelJob → JobResult
// path so the audit trail records the actual stop time. Returns the
// row id so the caller can tell whether the update happened (the
// predicate could miss in a race with the scheduler dispatch path).
//
// We DON'T pre-fill exit_code or error here — those columns are
// agent-driven on running cancels, and for a queued cancel the
// absence of an exit_code is the honest signal ("never started").
func (q *Queries) CancelQueuedJobRun(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelQueuedJobRun, id)
	err := row.Scan(&id)
	return id, err
}

const getJobRunForCancel = `-- name: GetJobRunForCancel :one
SELECT id, run_id, stage_run_id, name, status, agent_id, attempt
FROM job_runs
WHERE id = $1
`

type GetJobRunForCancelRow struct {
	ID         pgtype.UUID
	RunID      pgtype.UUID
	StageRunID pgtype.UUID
	Name       string
	Status     string
	AgentID    pgtype.UUID
	Attempt    int32
}

// Thin row used by the job-scoped cancel handler. Returns the
// structural pointers cancel needs (run_id, stage_run_id) plus the
// decision inputs (status, agent_id) — `running` jobs are signaled
// via gRPC (handler dispatches CancelJob), `queued` jobs flip
// directly here and feed cascadeAfterJobCompletion. Distinguishes
// "not found" from "already terminal" via pgx.ErrNoRows vs the
// status check in the caller.
func (q *Queries) GetJobRunForCancel(ctx context.Context, id pgtype.UUID) (GetJobRunForCancelRow, error) {
	row := q.db.QueryRow(ctx, getJobRunForCancel, id)
	var i GetJobRunForCancelRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageRunID,
		&i.Name,
		&i.Status,
		&i.AgentID,
		&i.Attempt,
	)
	return i, err
}

const getLatestModificationForPipeline = `-- name: GetLatestModificationForPipeline :one
SELECT m.id, m.material_id, m.revision, m.branch
FROM modifications m
JOIN materials mat ON mat.id = m.material_id
WHERE mat.pipeline_id = $1
ORDER BY m.detected_at DESC
LIMIT 1
`

type GetLatestModificationForPipelineRow struct {
	ID         int64
	MaterialID pgtype.UUID
	Revision   string
	Branch     *string
}

// Most recent modification across any material attached to a
// pipeline. Powers "trigger latest" for manual runs. Ordered by
// detected_at so the newest webhook delivery wins even when the
// committer timestamp is older (rebases, fast-forwards of older
// commits).
func (q *Queries) GetLatestModificationForPipeline(ctx context.Context, pipelineID pgtype.UUID) (GetLatestModificationForPipelineRow, error) {
	row := q.db.QueryRow(ctx, getLatestModificationForPipeline, pipelineID)
	var i GetLatestModificationForPipelineRow
	err := row.Scan(
		&i.ID,
		&i.MaterialID,
		&i.Revision,
		&i.Branch,
	)
	return i, err
}

const getRunForAction = `-- name: GetRunForAction :one
SELECT id, pipeline_id, status, revisions
FROM runs
WHERE id = $1
`

type GetRunForActionRow struct {
	ID         pgtype.UUID
	PipelineID pgtype.UUID
	Status     string
	Revisions  []byte
}

// Thin row used by cancel/rerun handlers to check status + find the
// pipeline + revisions without pulling the whole detail query.
func (q *Queries) GetRunForAction(ctx context.Context, id pgtype.UUID) (GetRunForActionRow, error) {
	row := q.db.QueryRow(ctx, getRunForAction, id)
	var i GetRunForActionRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Status,
		&i.Revisions,
	)
	return i, err
}
