// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scm_credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSCMCredential = `-- name: DeleteSCMCredential :exec
DELETE FROM scm_credentials WHERE id = $1
`

func (q *Queries) DeleteSCMCredential(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSCMCredential, id)
	return err
}

const getSCMCredentialByProviderHost = `-- name: GetSCMCredentialByProviderHost :one
SELECT id, provider, host, api_base, display_name,
       auth_ref_encrypted, created_by, created_at, updated_at
FROM scm_credentials
WHERE provider = $1 AND host = $2
LIMIT 1
`

type GetSCMCredentialByProviderHostParams struct {
	Provider string
	Host     string
}

// Resolver hot path. Nil rows silently fall through to
// scm_source.auth_ref at the caller.
func (q *Queries) GetSCMCredentialByProviderHost(ctx context.Context, arg GetSCMCredentialByProviderHostParams) (ScmCredential, error) {
	row := q.db.QueryRow(ctx, getSCMCredentialByProviderHost, arg.Provider, arg.Host)
	var i ScmCredential
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Host,
		&i.ApiBase,
		&i.DisplayName,
		&i.AuthRefEncrypted,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSCMCredentials = `-- name: ListSCMCredentials :many
SELECT id, provider, host, api_base, display_name,
       auth_ref_encrypted, created_by, created_at, updated_at
FROM scm_credentials
ORDER BY provider, host
`

// Admin UI: list every org-level credential. Ciphertext comes
// along because admins who can read this table already hold the
// keys; the decrypt step lives in the store layer.
func (q *Queries) ListSCMCredentials(ctx context.Context) ([]ScmCredential, error) {
	rows, err := q.db.Query(ctx, listSCMCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScmCredential{}
	for rows.Next() {
		var i ScmCredential
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Host,
			&i.ApiBase,
			&i.DisplayName,
			&i.AuthRefEncrypted,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSCMCredential = `-- name: UpsertSCMCredential :one
INSERT INTO scm_credentials
    (provider, host, api_base, display_name, auth_ref_encrypted, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (provider, host) DO UPDATE SET
    api_base           = EXCLUDED.api_base,
    display_name       = EXCLUDED.display_name,
    auth_ref_encrypted = EXCLUDED.auth_ref_encrypted,
    updated_at         = NOW()
RETURNING id, provider, host, api_base, display_name,
          auth_ref_encrypted, created_by, created_at, updated_at,
          (xmax = 0) AS created
`

type UpsertSCMCredentialParams struct {
	Provider         string
	Host             string
	ApiBase          string
	DisplayName      string
	AuthRefEncrypted []byte
	CreatedBy        pgtype.UUID
}

type UpsertSCMCredentialRow struct {
	ID               pgtype.UUID
	Provider         string
	Host             string
	ApiBase          string
	DisplayName      string
	AuthRefEncrypted []byte
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Created          bool
}

// Insert-or-rotate. ON CONFLICT flips auth_ref_encrypted + api_base
// + display_name but preserves id + created_at + created_by so
// audit trails point to the original provisioning.
func (q *Queries) UpsertSCMCredential(ctx context.Context, arg UpsertSCMCredentialParams) (UpsertSCMCredentialRow, error) {
	row := q.db.QueryRow(ctx, upsertSCMCredential,
		arg.Provider,
		arg.Host,
		arg.ApiBase,
		arg.DisplayName,
		arg.AuthRefEncrypted,
		arg.CreatedBy,
	)
	var i UpsertSCMCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Host,
		&i.ApiBase,
		&i.DisplayName,
		&i.AuthRefEncrypted,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
