// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scm_sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findScmSourceByURL = `-- name: FindScmSourceByURL :one
SELECT id, project_id, provider, url, default_branch, webhook_secret, auth_ref,
       last_synced_at, last_synced_revision, created_at, updated_at
FROM scm_sources
WHERE url = $1
LIMIT 1
`

func (q *Queries) FindScmSourceByURL(ctx context.Context, url string) (ScmSource, error) {
	row := q.db.QueryRow(ctx, findScmSourceByURL, url)
	var i ScmSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Url,
		&i.DefaultBranch,
		&i.WebhookSecret,
		&i.AuthRef,
		&i.LastSyncedAt,
		&i.LastSyncedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScmSourceByProject = `-- name: GetScmSourceByProject :one
SELECT id, project_id, provider, url, default_branch, webhook_secret, auth_ref,
       last_synced_at, last_synced_revision, created_at, updated_at
FROM scm_sources
WHERE project_id = $1
LIMIT 1
`

func (q *Queries) GetScmSourceByProject(ctx context.Context, projectID pgtype.UUID) (ScmSource, error) {
	row := q.db.QueryRow(ctx, getScmSourceByProject, projectID)
	var i ScmSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Url,
		&i.DefaultBranch,
		&i.WebhookSecret,
		&i.AuthRef,
		&i.LastSyncedAt,
		&i.LastSyncedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScmSource = `-- name: UpsertScmSource :one
INSERT INTO scm_sources (project_id, provider, url, default_branch, webhook_secret, auth_ref)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id) DO UPDATE SET
    provider       = EXCLUDED.provider,
    url            = EXCLUDED.url,
    default_branch = EXCLUDED.default_branch,
    webhook_secret = EXCLUDED.webhook_secret,
    auth_ref       = EXCLUDED.auth_ref,
    updated_at = CASE
        WHEN scm_sources.provider = EXCLUDED.provider
             AND scm_sources.url = EXCLUDED.url
             AND scm_sources.default_branch = EXCLUDED.default_branch
             AND scm_sources.webhook_secret IS NOT DISTINCT FROM EXCLUDED.webhook_secret
             AND scm_sources.auth_ref IS NOT DISTINCT FROM EXCLUDED.auth_ref
        THEN scm_sources.updated_at
        ELSE NOW()
    END
RETURNING id, project_id, provider, url, default_branch, webhook_secret, auth_ref,
          last_synced_at, last_synced_revision, created_at, updated_at, (xmax = 0) AS created
`

type UpsertScmSourceParams struct {
	ProjectID     pgtype.UUID
	Provider      string
	Url           string
	DefaultBranch string
	WebhookSecret *string
	AuthRef       *string
}

type UpsertScmSourceRow struct {
	ID                 pgtype.UUID
	ProjectID          pgtype.UUID
	Provider           string
	Url                string
	DefaultBranch      string
	WebhookSecret      *string
	AuthRef            *string
	LastSyncedAt       pgtype.Timestamptz
	LastSyncedRevision *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Created            bool
}

// Bind a project to its SCM source. updated_at only bumps when something
// meaningful changes, so idempotent re-applies don't spam the timeline.
func (q *Queries) UpsertScmSource(ctx context.Context, arg UpsertScmSourceParams) (UpsertScmSourceRow, error) {
	row := q.db.QueryRow(ctx, upsertScmSource,
		arg.ProjectID,
		arg.Provider,
		arg.Url,
		arg.DefaultBranch,
		arg.WebhookSecret,
		arg.AuthRef,
	)
	var i UpsertScmSourceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.Url,
		&i.DefaultBranch,
		&i.WebhookSecret,
		&i.AuthRef,
		&i.LastSyncedAt,
		&i.LastSyncedRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Created,
	)
	return i, err
}
