// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: service_accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServiceAccount = `-- name: DeleteServiceAccount :exec
DELETE FROM service_accounts WHERE id = $1
`

// ON DELETE CASCADE on api_tokens cleans up the token rows
// automatically.
func (q *Queries) DeleteServiceAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceAccount, id)
	return err
}

const getServiceAccountByID = `-- name: GetServiceAccountByID :one
SELECT id, name, description, role, created_by, disabled_at,
       created_at, updated_at
FROM service_accounts
WHERE id = $1
`

func (q *Queries) GetServiceAccountByID(ctx context.Context, id pgtype.UUID) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, getServiceAccountByID, id)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.CreatedBy,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertServiceAccount = `-- name: InsertServiceAccount :one
INSERT INTO service_accounts (name, description, role, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, role, created_by, disabled_at,
          created_at, updated_at
`

type InsertServiceAccountParams struct {
	Name        string
	Description string
	Role        string
	CreatedBy   pgtype.UUID
}

func (q *Queries) InsertServiceAccount(ctx context.Context, arg InsertServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, insertServiceAccount,
		arg.Name,
		arg.Description,
		arg.Role,
		arg.CreatedBy,
	)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.CreatedBy,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceAccounts = `-- name: ListServiceAccounts :many
SELECT id, name, description, role, created_by, disabled_at,
       created_at, updated_at
FROM service_accounts
ORDER BY created_at DESC
`

// Newest first. Disabled SAs included; the UI dims them so admins
// see the full picture without filtering.
func (q *Queries) ListServiceAccounts(ctx context.Context) ([]ServiceAccount, error) {
	rows, err := q.db.Query(ctx, listServiceAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceAccount{}
	for rows.Next() {
		var i ServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.CreatedBy,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceAccountDisabled = `-- name: SetServiceAccountDisabled :exec
UPDATE service_accounts
SET disabled_at = $2, updated_at = NOW()
WHERE id = $1
`

type SetServiceAccountDisabledParams struct {
	ID         pgtype.UUID
	DisabledAt pgtype.Timestamptz
}

// Disabling stops new tokens from authenticating (the bearer
// middleware loads the SA after token lookup and bounces 401 when
// disabled_at is set). Existing tokens stay in the table — wipe
// explicitly with DELETE if you want them gone.
func (q *Queries) SetServiceAccountDisabled(ctx context.Context, arg SetServiceAccountDisabledParams) error {
	_, err := q.db.Exec(ctx, setServiceAccountDisabled, arg.ID, arg.DisabledAt)
	return err
}

const updateServiceAccount = `-- name: UpdateServiceAccount :exec
UPDATE service_accounts
SET description = $2, role = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateServiceAccountParams struct {
	ID          pgtype.UUID
	Description string
	Role        string
}

func (q *Queries) UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) error {
	_, err := q.db.Exec(ctx, updateServiceAccount, arg.ID, arg.Description, arg.Role)
	return err
}
