// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sweeper.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLogLinesByJob = `-- name: DeleteLogLinesByJob :exec
DELETE FROM log_lines WHERE job_run_id = $1
`

// Called after a successful reclaim so the retry starts with a clean log
// window. Loses the old attempt's output — acceptable MVP trade for not
// growing the schema to carry per-attempt log namespacing.
func (q *Queries) DeleteLogLinesByJob(ctx context.Context, jobRunID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLogLinesByJob, jobRunID)
	return err
}

const getJobAttempt = `-- name: GetJobAttempt :one
SELECT id, status, attempt FROM job_runs WHERE id = $1 LIMIT 1
`

type GetJobAttemptRow struct {
	ID      pgtype.UUID
	Status  string
	Attempt int32
}

// Used by the reaper to disambiguate "at max attempts" from "already
// handled" when ReclaimJobForRetry returned no rows.
func (q *Queries) GetJobAttempt(ctx context.Context, id pgtype.UUID) (GetJobAttemptRow, error) {
	row := q.db.QueryRow(ctx, getJobAttempt, id)
	var i GetJobAttemptRow
	err := row.Scan(&i.ID, &i.Status, &i.Attempt)
	return i, err
}

const listStaleRunningJobs = `-- name: ListStaleRunningJobs :many
SELECT j.id, j.run_id, j.stage_run_id, j.name, j.attempt, j.agent_id,
       a.status AS agent_status, a.last_seen_at
FROM job_runs j
JOIN agents a ON a.id = j.agent_id
WHERE j.status = 'running'
  AND (a.status = 'offline' OR a.last_seen_at IS NULL
       OR a.last_seen_at < NOW() - $1::INTERVAL)
`

type ListStaleRunningJobsRow struct {
	ID          pgtype.UUID
	RunID       pgtype.UUID
	StageRunID  pgtype.UUID
	Name        string
	Attempt     int32
	AgentID     pgtype.UUID
	AgentStatus string
	LastSeenAt  pgtype.Timestamptz
}

// Running jobs whose agent is either offline or hasn't been seen within
// @staleness. The reaper walks this list every tick and either re-queues or
// fails them.
func (q *Queries) ListStaleRunningJobs(ctx context.Context, staleness pgtype.Interval) ([]ListStaleRunningJobsRow, error) {
	rows, err := q.db.Query(ctx, listStaleRunningJobs, staleness)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleRunningJobsRow{}
	for rows.Next() {
		var i ListStaleRunningJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageRunID,
			&i.Name,
			&i.Attempt,
			&i.AgentID,
			&i.AgentStatus,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimJobForRetry = `-- name: ReclaimJobForRetry :one
UPDATE job_runs
SET status = 'queued', agent_id = NULL, started_at = NULL, finished_at = NULL,
    exit_code = NULL, error = NULL, attempt = attempt + 1
WHERE id = $1 AND status = 'running' AND attempt < $2::int
RETURNING id, run_id, stage_run_id, name, attempt
`

type ReclaimJobForRetryParams struct {
	ID          pgtype.UUID
	MaxAttempts int32
}

type ReclaimJobForRetryRow struct {
	ID         pgtype.UUID
	RunID      pgtype.UUID
	StageRunID pgtype.UUID
	Name       string
	Attempt    int32
}

// Flips a running job back to queued, IF it is still running AND still under
// the retry cap. Returns the new attempt number; ErrNoRows signals the caller
// should take a different code path (failed-at-max or already-handled).
func (q *Queries) ReclaimJobForRetry(ctx context.Context, arg ReclaimJobForRetryParams) (ReclaimJobForRetryRow, error) {
	row := q.db.QueryRow(ctx, reclaimJobForRetry, arg.ID, arg.MaxAttempts)
	var i ReclaimJobForRetryRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageRunID,
		&i.Name,
		&i.Attempt,
	)
	return i, err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :exec
UPDATE agents SET last_seen_at = NOW() WHERE id = $1
`

// Called from the gRPC heartbeat handler so the reaper can tell which agents
// are still alive. Tiny write per heartbeat (default cadence 30s).
func (q *Queries) UpdateAgentLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAgentLastSeen, id)
	return err
}
