// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: vcs_integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVCSIntegration = `-- name: DeleteVCSIntegration :exec
DELETE FROM vcs_integrations WHERE id = $1
`

func (q *Queries) DeleteVCSIntegration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVCSIntegration, id)
	return err
}

const getVCSIntegrationByID = `-- name: GetVCSIntegrationByID :one
SELECT id, kind, name, display_name, app_id, private_key,
       webhook_secret, api_base, enabled, created_at, updated_at
FROM vcs_integrations
WHERE id = $1
`

func (q *Queries) GetVCSIntegrationByID(ctx context.Context, id pgtype.UUID) (VcsIntegration, error) {
	row := q.db.QueryRow(ctx, getVCSIntegrationByID, id)
	var i VcsIntegration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.DisplayName,
		&i.AppID,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.ApiBase,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledVCSIntegrations = `-- name: ListEnabledVCSIntegrations :many
SELECT id, kind, name, display_name, app_id, private_key,
       webhook_secret, api_base, enabled, created_at, updated_at
FROM vcs_integrations
WHERE enabled = TRUE
ORDER BY name ASC
`

// Bootstrap + reload path: rows the registry should actually
// instantiate on startup.
func (q *Queries) ListEnabledVCSIntegrations(ctx context.Context) ([]VcsIntegration, error) {
	rows, err := q.db.Query(ctx, listEnabledVCSIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VcsIntegration{}
	for rows.Next() {
		var i VcsIntegration
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.DisplayName,
			&i.AppID,
			&i.PrivateKey,
			&i.WebhookSecret,
			&i.ApiBase,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVCSIntegrations = `-- name: ListVCSIntegrations :many
SELECT id, kind, name, display_name, app_id, private_key,
       webhook_secret, api_base, enabled, created_at, updated_at
FROM vcs_integrations
ORDER BY name ASC
`

// Admin feed. Returns every row regardless of `enabled` so the
// /settings/integrations page can surface disabled rows the user
// can re-enable.
func (q *Queries) ListVCSIntegrations(ctx context.Context) ([]VcsIntegration, error) {
	rows, err := q.db.Query(ctx, listVCSIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VcsIntegration{}
	for rows.Next() {
		var i VcsIntegration
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.DisplayName,
			&i.AppID,
			&i.PrivateKey,
			&i.WebhookSecret,
			&i.ApiBase,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVCSIntegrationEnabled = `-- name: SetVCSIntegrationEnabled :exec
UPDATE vcs_integrations
SET enabled = $2, updated_at = NOW()
WHERE id = $1
`

type SetVCSIntegrationEnabledParams struct {
	ID      pgtype.UUID
	Enabled bool
}

func (q *Queries) SetVCSIntegrationEnabled(ctx context.Context, arg SetVCSIntegrationEnabledParams) error {
	_, err := q.db.Exec(ctx, setVCSIntegrationEnabled, arg.ID, arg.Enabled)
	return err
}

const upsertVCSIntegration = `-- name: UpsertVCSIntegration :one
INSERT INTO vcs_integrations (
    kind, name, display_name, app_id,
    private_key, webhook_secret, api_base, enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    kind            = EXCLUDED.kind,
    display_name    = EXCLUDED.display_name,
    app_id          = EXCLUDED.app_id,
    private_key     = COALESCE(EXCLUDED.private_key, vcs_integrations.private_key),
    webhook_secret  = COALESCE(EXCLUDED.webhook_secret, vcs_integrations.webhook_secret),
    api_base        = EXCLUDED.api_base,
    enabled         = EXCLUDED.enabled,
    updated_at      = NOW()
RETURNING id, kind, name, display_name, app_id, private_key,
          webhook_secret, api_base, enabled, created_at, updated_at
`

type UpsertVCSIntegrationParams struct {
	Kind          string
	Name          string
	DisplayName   string
	AppID         *int64
	PrivateKey    []byte
	WebhookSecret []byte
	ApiBase       string
	Enabled       bool
}

// ON CONFLICT (name) DO UPDATE refreshes every field EXCEPT
// private_key + webhook_secret when the caller passes NULL.
// The handler interprets an empty string from the dialog as
// "keep existing ciphertext", mirroring auth_providers.
func (q *Queries) UpsertVCSIntegration(ctx context.Context, arg UpsertVCSIntegrationParams) (VcsIntegration, error) {
	row := q.db.QueryRow(ctx, upsertVCSIntegration,
		arg.Kind,
		arg.Name,
		arg.DisplayName,
		arg.AppID,
		arg.PrivateKey,
		arg.WebhookSecret,
		arg.ApiBase,
		arg.Enabled,
	)
	var i VcsIntegration
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.DisplayName,
		&i.AppID,
		&i.PrivateKey,
		&i.WebhookSecret,
		&i.ApiBase,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
